#!/bin/bash
# Easy install script for TSGL on OS X
# Last updated: 08/10/16
#
# -SUBJECT TO CHANGE-
###############################

VER_XQ="XQuartz-2.7.11"

#Function for checking command availability
has () {
  (command -v "$1" >/dev/null 2>&1 && echo 1) || echo 0
}

#FIXME: probably need to make it so X11 autoupdates. this currently seems super broken.
#Print X11 warning
if [ $(ls /Applications/Utilities | grep XQuartz.app | wc -l) -eq 0 ]; then
  echo "Installing X11"
  curl -L -O "http://xquartz.macosforge.org/downloads/SL/$VER_XQ.dmg"
  open -W "$VER_XQ.dmg"
  echo "Please continue the installation process by double-clicking XQuartz.pkg and following the instructions on screen."
  echo "Please enter to continue once XQuartz has finished installing."
  read
fi

#Install Xcode command line tools (will do nothing if already installed)
if [ ! -e "/Library/Developer/CommandLineTools" ]; then
  cmd="xcode-select --install"
  $cmd # Fix for vim syntax highlighting bugginess
  echo "Please select \"Install\" from the confirmation window that appears, and Agree to the license terms."
  echo "Press enter to continue once Xcode command line tools has finished installing"
  read
fi

#Install brew
if [ $(has brew) = 0 ]; then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  export PATH=/usr/local/bin:$PATH
else
  echo "Homebrew detected."
  export PATH=/usr/local/bin:$PATH
fi

echo
echo "Using Homebrew to install dependencies..."
echo

brew update

#brew tap homebrew/versions

#Install glfw3 (will do nothing if already installed)
echo "Installing GLFW..."
brew install glfw3

#GLEW
echo "Installing GLEW..."
brew install glew

#Freetype
echo "Installing Freetype2..."
brew install freetype

#Doxygen
echo "Installing Doxygen..."
brew install doxygen

#cxxopts
echo "Installing cxxopts..."
brew install cxxopts

#g++
gVers=$(g++ -v 2>&1)
gVeres=$(g++ -v 2>&1 | grep "gcc version" | cut -f 3 -d ' ' | tr -d .)

echo "$gVers" | grep "clang" > check.txt

version=490

#First, check if we need to move an existing g++ compiler
if [ -e /usr/local/bin/g++ ] && [ ! -e /usr/local/Cellar/gcc49 ];
then
	sudo mv /usr/local/bin/g++ /usr/local/bin/g++old
	sudo mv /usr/local/bin/gcc /usr/local/bin/gccold

fi

#Now check if we need to install gcc10
if grep --quiet clang check.txt; then
	echo "Installing g++...this may take a while!"
	brew install gcc
  sudo rm /usr/local/bin/gcc
  sudo rm /usr/local/bin/g++
	sudo ln -s /usr/local/Cellar/gcc/10.2.0/bin/gcc-10 /usr/local/bin/gcc
	sudo ln -s /usr/local/Cellar/gcc/10.2.0/bin/g++-10 /usr/local/bin/g++
else
	echo "Installing g++...this may take a while!"
	brew install gcc
  sudo rm /usr/local/bin/gcc
  sudo rm /usr/local/bin/g++
	sudo ln -s /usr/local/Cellar/gcc/10.2.0/bin/gcc-10 /usr/local/bin/gcc
	sudo ln -s /usr/local/Cellar/gcc/10.2.0/bin/g++-10 /usr/local/bin/g++
fi

#Symlinks
echo "Fixing missing symlinks..."
if [ ! -e /usr/X11/lib/libX11.dylib ]; then
  sudo ln -s /usr/X11/lib/libX11.6.dylib /usr/X11/lib/libX11.dylib
fi

if [ ! -e /usr/X11/lib/libXrandr.dylib ]; then
  sudo ln -s /usr/X11/lib/libXrandr.2.dylib /usr/X11/lib/libXrandr.dylib
fi

#Remove any broken symlinks before installing
sudo rm -f /usr/local/lib/libtsgl.* 
sudo rm -rf /usr/local/include/TSGL

#Build TSGL and install
echo "Building TSGL..."
echo

make

echo "Installing..."
echo

sudo make install

echo

echo "Installation complete!"
echo "Run \"./runtests\" to verify everything is working."
