#!/bin/bash
# Easy install script for TSGL on OS X

VER_XQ="XQuartz-2.7.7"
VER_MP="MacPorts-2.3.3"

#Function for checking command availability
has () {
  (command -v "$1" >/dev/null 2>&1 && echo 1) || echo 0
}

#Needed for some bugs that occurred when we couldn't have permissions to these directory paths
sudo chmod -R 777 /usr/local/Cellar /usr/local /Library/Caches/Homebrew/Formula /usr/local/lib

#Remove any broken symlinks
sudo rm -f /usr/local/lib/libtsgl.* 
sudo rm -rf /usr/local/include/TSGL

#Print X11 warning
if [ $(ls /Applications/Utilities | grep XQuartz.app | wc -l) -eq 0 ]; then
  echo "Installing X11"
  curl -L -O "http://xquartz.macosforge.org/downloads/SL/$VER_XQ.dmg"
  open -W "$VER_XQ.dmg"
  echo "Please continue the installation process by double-clicking XQuartz.pkg and following the instructions on screen."
  echo "Please enter to continue once XQuartz has finished installing."
  read
fi

#Install Xcode command line tools (will do nothing if already installed)
if [ ! -e "/Library/Developer/CommandLineTools" ]; then
  cmd="xcode-select --install"
  $cmd # Fix for vim syntax highlighting bugginess
  echo "Please select \"Install\" from the confirmation window that appears, and Agree to the license terms."
  echo "Press enter to continue once Xcode command line tools has finished installing"
  read
fi

#Make and cd into a workspace
mkdir workspace
cd workspace

#Install brew
if [ $(has brew) = 0 ]; then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "Homebrew detected."
fi

#Install glfw3 (will do nothing if already installed)
echo "Installing GLFW..."
brew install homebrew/versions/glfw3

#Install port
if [ $(has port) = 0 ]; then
  echo "Installing Macports..."
  curl -O "https://distfiles.macports.org/MacPorts/$VER_MP.tar.bz2"
  tar xf "$VER_MP.tar.bz2"
  cd "$VER_MP/"
  ./configure
  make
  sudo make install
  cd ..
else
  echo "Macports detected."
fi

#Get port packages
echo "Installing GLEW..."
sudo port install glew
echo "Installing Freetype2..."
sudo port install freetype
gver=$(g++ -v 2>&1 | grep "gcc version" | cut -f 3 -d ' ' | tr -d .)
if [ $gver -lt 490 ]; then
  echo "Installing GCC 4.9...this may take a while, please be patient..."
  sudo port install gcc49
fi
echo "Switiching default compiler to mp-gcc49"
sudo port select --set gcc mp-gcc49
echo "Fixing missing symlinks"
if [ ! -e /usr/X11/lib/libX11.dylib ]; then
  sudo ln -s /usr/X11/lib/libX11.6.dylib /usr/X11/lib/libX11.dylib
fi
if [ ! -e /usr/X11/lib/libXrandr.dylib ]; then
  sudo ln -s /usr/X11/lib/libXrandr.2.dylib /usr/X11/lib/libXrandr.dylib
fi
if [ -e /usr/lib/libstdc++.dylib ]; then
  sudo mv /usr/lib/libstdc++.dylib /usr/lib/libstdc++.dylib-old
fi
if [ ! -e /usr/bin/gcc_tsglbak ]; then
  sudo mv /usr/bin/gcc /usr/bin/gcc_tsglbak
  sudo ln -s /opt/local/bin/gcc-mp-4.9 /usr/bin/gcc
fi
if [ ! -e /usr/bin/g++_tsglbak ]; then
  sudo mv /usr/bin/g++ /usr/bin/g++_tsglbak
  sudo ln -s /opt/local/bin/g++-mp-4.9 /usr/bin/g++
fi

#Clone and make TSGL
echo "Making TSGL"
git clone https://github.com/Calvin-CS/TSGL
cd TSGL

#http://stackoverflow.com/questions/2527496/how-can-i-write-a-makefile-to-auto-detect-and-parallelize-the-build-with-gnu-mak
NPROCS:=1
OS:=$(shell uname -s)

ifeq($(OS),Linux)
  NPROCS:=$(shell grep -c ^processor /proc/cpuinfo)
endif
ifeq($(OS),Darwin) # Assume Mac OS X
  NPROCS:=$(shell system_profiler | awk '/Number Of CPUs/{print $4}{next;}')
endif

make $(NPROCS) debug

cd ..

#Move the necessary files needed
cp -r TSGL/lib/ /usr/local/lib/

mkdir /usr/local/include/TSGL

cp -r TSGL/src/TSGL/*.h /usr/local/include/TSGL

echo
echo "Installation complete! Navigate into $(pwd) and run \"./runtests\" to verify everything is working."

sudo chmod -R 755 /usr/local/Cellar /usr/local /Library/Caches/Homebrew/Formula /usr/local/lib
