#!/bin/sh

#make clean
make clean

#Take out the lib and bin folders
rm -rf bin lib

#Take out the TSGL lib.a and lib.so files
rm $(TSGL_HOME)/lib/libtsgl.*

#Take out the TSGL folder containing the .h files
rm -rf $(TSGL_HOME)/include/TSGL

#Done.
echo "\n Uninstall complete!\n"
