#!/bin/bash
#Uninstall script for TSGL on Mac

#Clean out TSGL source code
make clean

#Remove the bin and lib folders
rm -rf bin lib

#Get permissions to access certain directory paths
sudo chmod -R 777 /usr/local/include/ /usr/local/lib/

#Take out the TSGL header files
rm -rf /usr/local/include/TSGL

#Take out the TSGL lib files
rm /usr/local/lib/libtsgl.*

#Restore permissions back to their normal status
sudo chmod -R 755 /usr/local/include/ /usr/local/lib/

#Tell user we're done uninstalling things
echo "Uninstall complete!

