#!/bin/bash

sudo make clean

sudo rm -rf bin lib

sudo rm -rf $(TSGL_HOME)/include/TSGL
sudo rm $(TSGL_HOME)/lib/libtsgl.*

#Remove the symlink made by install-fedora
sudo unlink $(TSGL_HOME)/lib64/libGL.so

echo "Uninstall complete!"
