#!/bin/bash
#Uninstall script for TSGL on Mac

#Clean out TSGL source code
make clean

#Remove the bin and lib folders
rm -rf bin lib

#Remove the copy of stb from /usr/include
sudo rm -rf $(TSGL_HOME)/include/stb

#Take out the TSGL header files
sudo rm -rf $(TSGL_HOME)/include/TSGL

#Take out the TSGL lib files
rm $(TSGL_HOME)/lib/libtsgl.*

#Check if we need to move the old g++ compiler back into place
if [ -e /usr/bin/g++old ];
then
	sudo unlink /usr/bin/g++
	sudo unlink /usr/bin/gcc

	sudo mv /usr/bin/g++old /usr/bin/g++
	sudo mv /usr/bin/gccold /usr/bin/gcc

fi

#Tell user we're done uninstalling things
echo "Uninstall complete!"

