#!/bin/bash
#Uninstall script for TSGL on Mac

#Clean out TSGL source code
make clean

#Remove the bin and lib folders
rm -rf bin lib

#Remove the copy of stb from /usr/local/include
sudo rm -rf /usr/local/include/stb

#Take out the TSGL header files
sudo rm -rf /usr/local/include/TSGL

#Take out the TSGL lib files
rm /usr/local/lib/libtsgl.*

#Check if we need to move the old g++ compiler back into place
if [ -e /usr/local/bin/g++old ];
then
	sudo unlink /usr/local/bin/g++
	sudo unlink /usr/local/bin/gcc

	sudo mv /usr/local/bin/g++old /usr/local/bin/g++
	sudo mv /usr/local/bin/gccold /usr/local/bin/gcc

fi

#Tell user we're done uninstalling things
echo "Uninstall complete!"

