#!/bin/bash

sudo make clean

sudo rm -rf bin lib

sudo rm -rf /usr/include/TSGL
sudo rm /usr/lib/libtsgl.*

#Remove the symlink made by install-fedora
sudo unlink /usr/lib64/libGL.so

echo "Uninstall complete! Please re-run install-fedora.sh if you wish to install again!"
