#!/bin/bash

sudo make clean

sudo rm -rf bin lib

sudo rm -rf /usr/include/TSGL
sudo rm /usr/lib/libtsgl.*

#Remove the symlink made by install-centos
sudo unlink /usr/lib/libGl.so

echo "Uninstall complete! Please re-run install-centos.sh if you wish to install again!"
