#!/bin/sh

#make clean
sudo make clean

#Take out the lib and bin folders
sudo rm -rf bin lib

#Take out the TSGL lib.a and lib.so files
sudo rm /usr/local/lib/libtsgl.*

#Take out the TSGL folder containing the .h files
sudo rm -rf /usr/local/include/TSGL

#Done.
echo "\n Uninstall complete!\n"
