CartesianCanvas Class Reference
Canvas extended for graphic support.
#include <CartesianCanvas.h>
Public Member Functions
CartesianCanvas (unsigned int b)
Constructs a new CartesianCanvas.
CartesianCanvas (int xx, int yy, int w, int h, Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax, unsigned int b, std::string=``)
Explicitly constructs a new CartesianCanvas.
void drawAxes (Decimal x, Decimal y, Decimal dx, Decimal dy)
Draw axes.
void drawCircle (Decimal x, Decimal y, Decimal radius, int res, ColorFloat color=BLACK, bool filled=true)
Draw a circle.
void drawColoredPolygon (int size, int x[], int y[], ColorFloat color[], bool filled=true)
Draw an arbitrary polygon with colored vertices.
void drawFunction (const Function &f)
Plots a function on the screen.
void drawImage (std::string fname, Decimal x, Decimal y, Decimal w, Decimal h, float a=1.0f)
Draw an image.
void drawLine (Decimal x1, Decimal y1, Decimal x2, Decimal y2, ColorFloat color=BLACK)
Draw a line.
void drawPoint (Decimal x, Decimal y, ColorFloat color=BLACK)
Draw a single pixel.
void drawRectangle (Decimal x, Decimal y, Decimal w, Decimal h, ColorFloat color=BLACK, bool filled=true)
Draw a rectangle.
void drawText (std::wstring s, Decimal x, Decimal y, unsigned int size, ColorFloat color=BLACK)
Draw a string of text.
void drawTriangle (Decimal x1, Decimal y1, Decimal x2, Decimal y2, Decimal x3, Decimal y3, ColorFloat color=BLACK, bool filled=true)
Draw a triangle.
void getCartesianCoordinates (int screenX, int screenY, Decimal &cartX, Decimal &cartY)
Translates Cartesian coordinates into window coordinates.
Decimal getCartHeight ()
Accessor for the CartesianCanvas's Cartesian height.
Decimal getCartWidth ()
Accessor for the CartesianCanvas's Cartesian width.
Decimal getPixelWidth ()
Accessor for the CartesianCanvas's effective pixel width.
Decimal getPixelHeight ()
Accessor for the CartesianCanvas's effective pixel height.
Decimal getMaxX ()
Accessor for the CartesianCanvas's right bound.
Decimal getMaxY ()
Accessor for the CartesianCanvas's top bound.
Decimal getMinX ()
Accessor for the CartesianCanvas's left bound.
Decimal getMinY ()
Accessor for the CartesianCanvas's bottom bound.
void getScreenCoordinates (Decimal cartX, Decimal cartY, int &screenX, int &screenY)
Translates window coordinates into Cartesian coordinates.
void recomputeDimensions (Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax)
Recomputes the CartesianCanvas's bounds.
void zoom (Decimal x, Decimal y, Decimal scale)
Zoom the CartesianCanvas with a given center.
void zoom (Decimal x1, Decimal y1, Decimal x2, Decimal y2)
Zoom the CartesianCanvas with the given bounding (Cartesian) coordinates.
Additional Inherited Members
Detailed Description
Canvas extended for graphic support.
CartesianCanvas provides a Canvas with a Cartesian coordinate system for ease of plotting.
Constructor & Destructor Documentation
CartesianCanvas::CartesianCanvas (unsigned int b)
Constructs a new CartesianCanvas.
This is the default constructor for the CartesianCanvas class
Parameters
b The size of the Canvas's internal vertex buffer.
Returns
A new 800x600 CartesianCanvas, unscaled (stretching from -400 to +400 on the x axis and -300 to +300 on the y axis) in the middle of the screen with no title.
CartesianCanvas::CartesianCanvas (int xx, int yy, int w, int h, Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax, unsigned int b, std::string t = ``)
Explicitly constructs a new CartesianCanvas.
This is an explicit constructor for the CartesianCanvas class.
Parameters
xx The x position of the CartesianCanvas window.
yy The y position of the CartesianCanvas window.
w The x dimension of the CartesianCanvas window.
h The y dimension of the CartesianCanvas window.
xMin The Cartestian coordinates of the CartesianCanvas's left bound.
yMin The Cartestian coordinates of the CartesianCanvas's bottom bound.
xMax The Cartestian coordinates of the CartesianCanvas's right bound.
yMax The Cartestian coordinates of the CartesianCanvas's top bound.
b The size of the Canvas's internal vertex buffer.
title The title of the window.
Returns
a new CartesianCanvas with the specified positional/scaling data, buffer size, and title
Member Function Documentation
void CartesianCanvas::drawAxes (Decimal x, Decimal y, Decimal dx = 0, Decimal dy = 0)
Draw axes.
This function draws axes (with tick marks) on the CartesianCanvas, centered at the given (Cartesian) coordinates
Parameters
x The horizontal location of the y-axis line.
y The vertical location of the x-axis line.
dx The distance between marks on the x-axis.
dy The distance between marks on the y-axis.
void CartesianCanvas::drawCircle (Decimal x, Decimal y, Decimal radius, int res, ColorFloat color = BLACK, bool filled = true)
Draw a circle.
This function draws a circle with the given origin coordinates, radius, resolution (number of sides), and color.
Parameters
x The x coordinate of the circle's origin.
y The y coordinate of the circle's origin.
radius The radius of the circle in pixels.
res The number of sides to use in the circle.
color The color of the circle.
filled Whether the circle should be filled.
Note
Identical to Canvas::drawCircle()
void CartesianCanvas::drawColoredPolygon (int size, int x[], int y[], ColorFloat color[], bool filled = true) [virtual]
Draw an arbitrary polygon with colored vertices.
This function draws a ColoredPolygon with the given vertex data
Parameters
size the number of vertices in the polygon
x an array of x positions of the vertices
y an array of y positions of the vertices
color an array of colors for the vertices
filled whether the colored polygon should be filled (true) or not (false)
Note
Identical to Canvas::drawColoredPolygon()
Reimplemented from Canvas.
void CartesianCanvas::drawFunction (const Function & f)
Plots a function on the screen.
This function receives a Function as a parameter and plots the function on the CartesianCanvas.
Parameters
f The function to plot.
Note
The passed function must receive exactly one Decimal parameter, and return a Decimal.
void CartesianCanvas::drawImage (std::string fname, Decimal x, Decimal y, Decimal w, Decimal h, float a = 1.0f)
Draw an image.
This function draws an Image with the given coordinates and dimensions.
Parameters
fname The name of the file to load the image from.
x The x coordinate of the Image's left edge.
y The y coordinate of the Image's top edge.
w The width of the Image.
h The height of the Image.
a The alpha with which to draw the Image.
Note
Identical to Canvas::drawImage()
void CartesianCanvas::drawLine (Decimal x1, Decimal y1, Decimal x2, Decimal y2, ColorFloat color = BLACK)
Draw a line.
This function draws a Line at the given coordinates with the given color.
Parameters
x1 The x position of the start of the line.
y1 The y position of the start of the line.
x2 The x position of the end of the line.
y2 The y position of the end of the line.
color The color of the line.
Note
Identical to Canvas::drawLine()
Referenced by drawAxes().
void CartesianCanvas::drawPoint (Decimal x, Decimal y, ColorFloat color = BLACK)
Draw a single pixel.
This function draws a Point at the given coordinates with the given color.
Parameters
x The x position of the point.
y The y position of the point.
color The color of the point.
Note
Identical to Canvas::drawPoint()
void CartesianCanvas::drawRectangle (Decimal x, Decimal y, Decimal w, Decimal h, ColorFloat color = BLACK, bool filled = true)
Draw a rectangle.
This function draws a Rectangle with the given coordinates, dimensions, and color.
Parameters
x The x coordinate of the Rectangle's left edge.
y The y coordinate of the Rectangle's top edge.
w The width of the Rectangle.
h The height of the Rectangle.
color The color of the rectangle.
filled Whether the rectangle should be filled.
Note
Identical to Canvas::drawRectangle()
void CartesianCanvas::drawText (std::wstring s, Decimal x, Decimal y, unsigned int size, ColorFloat color = BLACK)
Draw a string of text.
This function draws a given string of Text at the given coordinates with the given color.
Parameters
s The string to draw.
x The x coordinate of the text's left bound.
y The y coordinate of the text's left bound.
size The size of the text in pixels.
color The color of the Text.
Note
Identical to Canvas::drawText().
void CartesianCanvas::drawTriangle (Decimal x1, Decimal y1, Decimal x2, Decimal y2, Decimal x3, Decimal y3, ColorFloat color = BLACK, bool filled = true)
Draw a triangle.
This function draws a Triangle with the given vertices.
Parameters
x1 the x coordinate of the first vertex of the Triangle.
y1 the y coordinate of the first vertex of the Triangle.
x2 the x coordinate of the second vertex of the Triangle.
y2 the y coordinate of the second vertex of the Triangle.
x3 the x coordinate of the third vertex of the Triangle.
y3 the y coordinate of the third vertex of the Triangle.
color the color of the Triangle.
filled Whether the Triangle should be filled.
Note
Identical to Canvas::drawTriangle()
void CartesianCanvas::getCartesianCoordinates (int screenX, int screenY, Decimal & cartX, Decimal & cartY)
Translates Cartesian coordinates into window coordinates.
getCartesianCoordinates takes a pair of on-screen coordinates and translates them to Cartesian coordinates.
Parameters
screenX The window's x coordinate.
screenY The window's y coordinate.
cartX A reference variable to be filled with screenX's Cartesian position.
cartY A reference variable to be filled with screenY's Cartesian position.
Decimal CartesianCanvas::getCartHeight ()
Accessor for the CartesianCanvas's Cartesian height.
Returns
The Cartesian height of the CartesianCanvas.
Decimal CartesianCanvas::getCartWidth ()
Accessor for the CartesianCanvas's Cartesian width.
Returns
The Cartesian width of the CartesianCanvas.
Decimal CartesianCanvas::getMaxX ()
Accessor for the CartesianCanvas's right bound.
Returns
The real number corresponding the right of the CartesianCanvas.
Decimal CartesianCanvas::getMaxY ()
Accessor for the CartesianCanvas's top bound.
Returns
The real number corresponding the top of the CartesianCanvas.
Decimal CartesianCanvas::getMinX ()
Accessor for the CartesianCanvas's left bound.
Returns
The real number corresponding the left of the CartesianCanvas.
Decimal CartesianCanvas::getMinY ()
Accessor for the CartesianCanvas's bottom bound.
Returns
The real number corresponding the bottom of the CartesianCanvas.
Decimal CartesianCanvas::getPixelHeight ()
Accessor for the CartesianCanvas's effective pixel height.
Returns
The height corresponding to a single pixel in the current CartesianCanvas.
Decimal CartesianCanvas::getPixelWidth ()
Accessor for the CartesianCanvas's effective pixel width.
Returns
The width corresponding to a single pixel in the current CartesianCanvas.
void CartesianCanvas::getScreenCoordinates (Decimal cartX, Decimal cartY, int & screenX, int & screenY)
Translates window coordinates into Cartesian coordinates.
getScreenCoordinates takes a pair of Cartesian coordinates and translates them to on-screen coordinates.
Parameters
cartX The Cartesian x coordinate.
cartY The Cartesian y coordinate.
screenX A reference variable to be filled with cartX's window position.
screenY A reference variable to be filled with cartY's window position.
Referenced by drawCircle(), drawColoredPolygon(), drawFunction(), drawImage(), drawLine(), drawPoint(), drawRectangle(), drawText(), and drawTriangle().
void CartesianCanvas::recomputeDimensions (Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax)
Recomputes the CartesianCanvas's bounds.
This function recomputes the size variables of CartesianCanvas according to new bounds.
Parameters
xMin A real number corresponding to the new left edge of the CartesianCanvas.
YMin A real number corresponding to the new bottom edge of the CartesianCanvas.
xMax A real number corresponding to the new right edge of the CartesianCanvas.
xMax A real number corresponding to the new top edge of the CartesianCanvas.
Referenced by CartesianCanvas(), and zoom().
void CartesianCanvas::zoom (Decimal x, Decimal y, Decimal scale)
Zoom the CartesianCanvas with a given center.
This function will re-center the CartesianCanvas at the given coordinates, then zoom with respect to the given scale.
Parameters
x The coordinate to re-center the screen on.
y The coordinate to re-center the screen on.
scale The part to zoom in by. Less than 1 zooms in, greater than 1 zooms out.
Note
This function will automatically maintain the current aspect ratio.
Referenced by zoom().
void CartesianCanvas::zoom (Decimal x1, Decimal y1, Decimal x2, Decimal y2)
Zoom the CartesianCanvas with the given bounding (Cartesian) coordinates.
This function will zoom the CartesianCanvas with respect to the given bounding coordinates.
Parameters
x1 The left Cartesian bound.
y1 The bottom Cartesian bound.
x2 The right Cartesian bound.
y2 The top Cartesian bound.
Note
Setting the right bound lower than the left bound or the top lower than the bottom will just swap the variables.
Warning
This function will NOT automatically maintain the previous aspect ratio.
Change the aspect ratio on-the-fly only with caution.
The documentation for this class was generated from the following files:
CartesianCanvas.h
CartesianCanvas.cpp