tsgl::ConcavePolygon Class Reference
Draw an arbitrary Concave polygon with colored vertices.
#include <ConcavePolygon.h>
Public Member Functions
ConcavePolygon (int v)
Explicitly constructs a new ConcavePolygon.
~ConcavePolygon ()
Destroys a ConcavePolygon object.
bool intersects (float p0_x, float p0_y, float p1_x, float p1_y, float p2_x, float p2_y, float p3_x, float p3_y)
Determines if two lines intersect.
bool pointInTriangle (float px, float py, float x1, float y1, float x2, float y2, float x3, float y3)
Determines whether a point resides inside of a Triangle.
void addVertex (int x, int y, const ColorFloat &color)
Adds another vertex to a ConcavePolygon.
void draw ()
Draw the ConcavePolygon.
Static Public Member Functions
static void runTests ()
Runs the Unit tests.
Additional Inherited Members
Detailed Description
Draw an arbitrary Concave polygon with colored vertices.
ConcavePolygon is a class for holding vertex data for a triangle strip with colored vertices.
Vertices are drawn in triangle strip format, where the first three vertices make up the first triangle, the next vertex plus the previous two make up the second triangle, and so on.
This method is optimized for long lists and offers a marked improvement over drawing individual Triangle instances.
Note
The addVertex() method must be called the same number of times as specified in the constructor.
Calling addVertex() after all vertices have been added will do nothing.
Calling draw() before all vertices have been added will do nothing.
Constructor & Destructor Documentation
tsgl::ConcavePolygon::ConcavePolygon (int v)
Explicitly constructs a new ConcavePolygon.
Explicit constructor for a ConcavePolygon object.
Parameters
v The number of vertices the complete ConcavePolygon will have.
Warning
An invariant is held where if v is less than 3 then an error message is given.
Returns
A new ConcavePolygon with a buffer for storing the specified number of vertices.
tsgl::ConcavePolygon::~ConcavePolygon ()
Destroys a ConcavePolygon object.
Destructor for a ConcavePolygon object.
Frees up memory that was allocated to a ConcavePolygon object.
Member Function Documentation
void tsgl::ConcavePolygon::addVertex (int x, int y, const ColorFloat & color)
Adds another vertex to a ConcavePolygon.
This function initializes the next vertex in the Polyline and adds it to a ConcavePolygon buffer.
Parameters
x The x position of the vertex.
y The y position of the vertex.
color The reference variable of the color of the vertex.
Note
This function does nothing if the vertex buffer is already full.
A message is given indicating that the vertex buffer is full.
Referenced by tsgl::Canvas::drawConcavePolygon().
void tsgl::ConcavePolygon::draw () [virtual]
Draw the ConcavePolygon.
This function actually draws the ConcavePolygon to the Canvas.
Note
This function does nothing if the vertex buffer is not yet full.
A message is given indicating that the ConcavePolygon is NOT ready to be drawn yet (vertex buffer = not full).
Warning
This is an order of n-cubed operation, and is thus VERY SLOW.
Implements tsgl::Shape.
bool tsgl::ConcavePolygon::intersects (float p0_x, float p0_y, float p1_x, float p1_y, float p2_x, float p2_y, float p3_x, float p3_y)
Determines if two lines intersect.
Simulates two lines inside of a ConcavePolygon object and determines whether those two lines intersect.
Parameters
p0_x The x coordinate of the first point of the first line.
p0_y The y coordinate of the first point of the first line.
p1_x The x coordinate of the second point of the first line.
p1_y The y coordinate of the second point of the first line.
p2_x The x coordinate of the first point of the second line.
p2_y The y coordinate of the first point of the second line.
p3_x The x coordinate of the second point of the second line.
p3_y The y coordinate of the second point of the second line.
Returns
true if the lines do intersect, false if otherwise.
Referenced by draw().
bool tsgl::ConcavePolygon::pointInTriangle (float px, float py, float x1, float y1, float x2, float y2, float x3, float y3)
Determines whether a point resides inside of a Triangle.
Simulates a Triangle and point inside of a ConcavePolygon object and determines whether the point resides inside of the Triangle.
Parameters
px The x coordinate of the point.
py The y coordinate of the point.
x1 The x coordinate of the first vertex of the Triangle.
y1 The y coordinate of the first vertex of the Triangle.
x2 The x coordinate of the second vertex of the Triangle.
y2 The y coordinate of the second vertex of the Triangle.
x3 The x coordinate of the third vertex of the Triangle.
y3 The y coordinate of the third vertex of the Triangle.
Returns
true if the point does reside in the Triangle, false if otherwise.
Referenced by draw().
void tsgl::ConcavePolygon::runTests () [static]
Runs the Unit tests.
Runs the Unit tests for the ConcavePolygon class. intersects() and pointInTriangle() are tested.
The documentation for this class was generated from the following files:
ConcavePolygon.h
ConcavePolygon.cpp