Polyline Class Reference
Draw multiple lines chained together.
#include <Polyline.h>
Public Member Functions
Polyline (int v)
Explicitly constructor a new Polyline.
void addNextVertex (int x, int y, const ColorFloat &color=BLACK)
Add another vertex to the Polyline.
void draw ()
Draw the Polyline.
Additional Inherited Members
Detailed Description
Draw multiple lines chained together.
Polyline is a class for holding vertex data for multiple lines whose endpoints are connected.
This method is optimized for long lists and offers a marked improvement over drawing individual Line instances.
Note
The addVertex() method must be called the same number of times as specified in the constructor.
Calling addVertex() after all vertices have been added will do nothing.
Calling draw() before all vertices have been added will do nothing.
Constructor & Destructor Documentation
Polyline::Polyline (int v)
Explicitly constructor a new Polyline.
Parameters
v,the number of vertices the complete Polyline will have.
Returns
a new Polyline with a buffer for storing the specified numbered of vertices.
Member Function Documentation
void Polyline::addNextVertex (int x, int y, const ColorFloat & color = BLACK)
Add another vertex to the Polyline.
This function initalizes the next vertex in the Polyline and adds it to the Polyline's buffer.
Parameters
x The x position of the vertex.
y The y position of the vertex.
color The color of the vertex.
Note
This function does nothing if the vertex buffer is already full.
Referenced by Canvas::drawCircle(), Canvas::drawColoredPolygon(), CartesianCanvas::drawFunction(), Canvas::drawRectangle(), and Canvas::drawTriangle().
void Polyline::draw () [virtual]
Draw the Polyline.
This function actually draws the Polyline to the Canvas.
Note
This function does nothing if the vertex buffer is not yet full.
Implements Shape.
The documentation for this class was generated from the following files:
Polyline.h
Polyline.cpp