Canvas Class Reference
A GL window with numerous built-in, thread-safe drawing operations.
#include <Canvas.h>
Public Member Functions
Canvas (unsigned int b)
Constructs a new Canvas.
Canvas (int xx, int yy, int w, int h, unsigned int b, std::string title=``)
Explicitly constructs a new Canvas.
virtual ~Canvas ()
Destructor for the Canvas class.
void bindToButton (Key button, Action a, voidFunction f)
Binds a key or button to a function.
void bindToScroll (std::function< void(double, double)> f)
Binds the mouse wheel to a function.
void clear ()
Clears the Canvas.
int close ()
Waits for the user to close the Canvas.
virtual void drawCircle (int x, int y, int radius, int res, ColorFloat color=BLACK, bool filled=true)
Draw a circle.
virtual void drawColoredPolygon (int size, int x[], int y[], ColorFloat color[], bool filled=true)
Draw an arbitrary polygon with colored vertices.
virtual void drawImage (std::string fname, int x, int y, int w, int h, float a=1.0f)
Draw an image.
virtual void drawLine (int x1, int y1, int x2, int y2, ColorFloat color=BLACK)
Draw a line.
virtual void drawPoint (int x, int y, ColorFloat color=BLACK)
Draw a single pixel.
virtual void drawRectangle (int x, int y, int w, int h, ColorFloat color=BLACK, bool filled=true)
Draw a rectangle.
virtual void drawText (std::wstring s, int x, int y, unsigned int size, ColorFloat color=BLACK)
Draw a string of text.
virtual void drawTriangle (int x1, int y1, int x2, int y2, int x3, int y3, ColorFloat color=BLACK, bool filled=true)
Draw a triangle.
void end ()
Stops the Canvas.
int getFrameNumber ()
Accessor for the current frame number.
float getFPS ()
Accessor for the current FPS.
bool getIsOpen ()
Accessor for window's closed status.
int getMouseX ()
Accessor for the mouse's x-position.
int getMouseY ()
Accessor for the mouse's y-position.
uint8_t * getScreenBuffer ()
Accessor for the Canvas's currently drawn image.
double getTime ()
Accessor for the time since the Canvas was initialized.
int getWindowWidth ()
Accessor for the Canvas's width.
int getWindowHeight ()
Accessor for the Canvas's height.
int getWindowX ()
Accessor for the Canvas's x=position.
int getWindowY ()
Accessor for the Canvas's y-position.
void recordForNumFrames (unsigned int num_frames)
Records the Canvas for a specified number of frames.
void setBackgroundColor (ColorFloat color)
Mutator for the background color.
void setFont (std::string filename)
Mutator for the currently loaded font.
void setShowFPS (bool b)
Mutator for showing the FPS.
void setUpdateScreenCopy (bool b)
Mutator for keeping track of the screen's drawn buffer.
void stopRecording ()
Stops recording the Canvas.
int start ()
Opens the Canvas.
void takeScreenShot ()
Takes a screenshot.
Protected Member Functions
void drawShape (Shape *s)
Detailed Description
A GL window with numerous built-in, thread-safe drawing operations.
Canvas provides an easy-to-set-up, easy-to-use class for drawing various shapes.
With libpng and libjpeg, Canvas also supports the drawing of images.
On top of being easy to use, Canvas is also thread-safe, so any number of images may be drawn at once.
Constructor & Destructor Documentation
Canvas::Canvas (unsigned int b)
Constructs a new Canvas.
This is the default constructor for the Canvas class
Parameters
b The size of the Canvas's internal vertex buffer.
Returns
A new 800x600 Canvas in the middle of the screen with no title.
Canvas::Canvas (int xx, int yy, int w, int h, unsigned int b, std::string title = ``)
Explicitly constructs a new Canvas.
This is an explicit constructor for the Canvas class.
Parameters
xx The x position of the Canvas window.
yy The y position of the Canvas window.
w The x dimension of the Canvas window.
h The y dimension of the Canvas window.
b The size of the Canvas's internal vertex buffer.
title The title of the window.
Returns
A new Canvas with the specified positional data and title.
Member Function Documentation
void Canvas::bindToButton (Key button, Action a, voidFunction f)
Binds a key or button to a function.
This function binds a key or mouse button to a function pointer. Upon pressing or releasing the given key, Canvas will call the specified function.
Parameters
button The key or button to bind, as specified in the Key enum.
a The action to look out for (PG_PRESS or PG_RELEASE).
f The function to call upon action a on button.
Warning
PG_KEY_ESCAPE is automatically bound to closing the window. Overriding PG_KEY_ESCAPE will likely make you unable to close the window.
void Canvas::bindToScroll (std::function< void(double, double)> f)
Binds the mouse wheel to a function.
This function binds the mouse wheel to a function pointer. Upon scrolling, Canvas will call the specified function.
Parameters
f A function taking x and y parameters to be called when the mouse is scrolled.
void Canvas::clear ()
Clears the Canvas.
This function removes all shapes and sets the background to the color specified in setBackgroundColor().
int Canvas::close ()
Waits for the user to close the Canvas.
This function blocks until the user closes the Canvas. This function has no effect and will not request for close. Use end() before this to make that request.
Returns
0 if exit is successful, -1 if the canvas has not started yet.
See also
start(), end()
void Canvas::drawCircle (int x, int y, int radius, int res, ColorFloat color = BLACK, bool filled = true) [virtual]
Draw a circle.
This function draws a circle with the given origin coordinates, radius, resolution (number of sides), and color.
Parameters
x The x coordinate of the circle's origin.
y The y coordinate of the circle's origin.
radius The radius of the circle in pixels.
res The number of sides to use in the circle.
color The color of the circle.
filled Whether the circle should be filled.
Referenced by CartesianCanvas::drawCircle().
void Canvas::drawColoredPolygon (int size, int x[], int y[], ColorFloat color[], bool filled = true) [virtual]
Draw an arbitrary polygon with colored vertices.
This function draws a ColoredPolygon with the given vertex data
Parameters
size the number of vertices in the polygon
x an array of x positions of the vertices
y an array of y positions of the vertices
color an array of colors for the vertices
filled whether the colored polygon should be filled (true) or not (false)
Reimplemented in CartesianCanvas.
Referenced by CartesianCanvas::drawColoredPolygon().
void Canvas::drawImage (std::string fname, int x, int y, int w, int h, float a = 1.0f) [virtual]
Draw an image.
This function draws an Image with the given coordinates and dimensions.
Parameters
fname The name of the file to load the image from.
x The x coordinate of the Image's left edge.
y The y coordinate of the Image's top edge.
w The width of the Image.
h The height of the Image.
a The alpha with which to draw the Image.
Referenced by CartesianCanvas::drawImage().
void Canvas::drawLine (int x1, int y1, int x2, int y2, ColorFloat color = BLACK) [virtual]
Draw a line.
This function draws a Line at the given coordinates with the given color.
Parameters
x1 The x position of the start of the line.
y1 The y position of the start of the line.
x2 The x position of the end of the line.
y2 The y position of the end of the line.
color The color of the line.
Referenced by CartesianCanvas::drawLine().
void Canvas::drawPoint (int x, int y, ColorFloat color = BLACK) [virtual]
Draw a single pixel.
This function draws a Point at the given coordinates with the given color.
Parameters
x The x position of the point.
y The y position of the point.
color The color of the point.
Referenced by CartesianCanvas::drawPoint().
void Canvas::drawRectangle (int x, int y, int w, int h, ColorFloat color = BLACK, bool filled = true) [virtual]
Draw a rectangle.
This function draws a Rectangle with the given coordinates, dimensions, and color.
Parameters
x The x coordinate of the Rectangle's left edge.
y The y coordinate of the Rectangle's top edge.
w The width of the Rectangle.
h The height of the Rectangle.
color The color of the rectangle.
filled Whether the rectangle should be filled.
Referenced by CartesianCanvas::drawRectangle().
void Canvas::drawText (std::wstring s, int x, int y, unsigned int size, ColorFloat color = BLACK) [virtual]
Draw a string of text.
This function draws a given string of Text at the given coordinates with the given color.
Parameters
s The string to draw.
x The x coordinate of the text's left bound.
y The y coordinate of the text's left bound.
size The size of the text in pixels.
color The color of the Text.
Referenced by CartesianCanvas::drawText().
void Canvas::drawTriangle (int x1, int y1, int x2, int y2, int x3, int y3, ColorFloat color = BLACK, bool filled = true) [virtual]
Draw a triangle.
This function draws a Triangle with the given vertices.
Parameters
x1 the x coordinate of the first vertex of the Triangle.
y1 the y coordinate of the first vertex of the Triangle.
x2 the x coordinate of the second vertex of the Triangle.
y2 the y coordinate of the second vertex of the Triangle.
x3 the x coordinate of the third vertex of the Triangle.
y3 the y coordinate of the third vertex of the Triangle.
color the color of the Triangle.
filled Whether the Triangle should be filled.
Referenced by CartesianCanvas::drawTriangle().
void Canvas::end ()
Stops the Canvas.
This function stops rendering the Canvas. This does not close the Canvas; it will stay open. To rejoin the threads and complete the close, close() must be called. end() is not required to close the Canvas, closing the window by hitting escape or with the window manager does the same thing.
Once end() has been called, either manually, by the window manager, or by pressing escape, getIsOpen() will return false, and your computation should exit.
See also
start(), close()
float Canvas::getFPS ()
Accessor for the current FPS.
Returns
The current actual FPS.
int Canvas::getFrameNumber ()
Accessor for the current frame number.
Returns
The number of frames rendered so far.
bool Canvas::getIsOpen ()
Accessor for window's closed status.
Returns
Whether the window is still open (that is, the user has not closed it).
int Canvas::getMouseX ()
Accessor for the mouse's x-position.
Returns
The x coordinates of the mouse on the Canvas.
int Canvas::getMouseY ()
Accessor for the mouse's y-position.
Returns
The y coordinates of the mouse on the Canvas.
uint8_t * Canvas::getScreenBuffer ()
Accessor for the Canvas's currently drawn image.
Returns
A pointer to the RGB pixel buffer for the current Canvas.
double Canvas::getTime ()
Accessor for the time since the Canvas was initialized.
Returns
The time elapsed since the Canvas has started drawing (in microseconds).
int Canvas::getWindowHeight ()
Accessor for the Canvas's height.
Returns
The height in pixels of the Canvas.
Referenced by CartesianCanvas::getCartesianCoordinates(), CartesianCanvas::getScreenCoordinates(), and CartesianCanvas::recomputeDimensions().
int Canvas::getWindowWidth ()
Accessor for the Canvas's width.
Returns
The width in pixels of the Canvas.
Referenced by CartesianCanvas::getCartesianCoordinates(), CartesianCanvas::getScreenCoordinates(), and CartesianCanvas::recomputeDimensions().
int Canvas::getWindowX ()
Accessor for the Canvas's x=position.
Returns
The x coordinate in pixels of the Canvas (0 = left of monitor).
int Canvas::getWindowY ()
Accessor for the Canvas's y-position.
Returns
The y coordinate in pixels of the Canvas (0 = top of monitor).
void Canvas::recordForNumFrames (unsigned int num_frames)
Records the Canvas for a specified number of frames.
This function starts dumping screenshots of the Canvas to the file system every draw cycle. The function automatically terminates after num_frames cycles have completed.
void Canvas::setBackgroundColor (ColorFloat color)
Mutator for the background color.
This function sets the color to clear to when Canvas::clear() is called.
Parameters
color The color to clear to.
Note
The alpha channel of the color is ignored
void Canvas::setFont (std::string filename)
Mutator for the currently loaded font.
This function sets the loaded font, loading from the file or from disk if the file was loaded previously. Subsequent calls to drawText() will use this font to print.
Parameters
filename The filename of the font to load.
Note
Supports all font types that FreeType supports, which is almost anything.
void Canvas::setShowFPS (bool b)
Mutator for showing the FPS.
Parameters
b Whether to print the FPS to stdout every draw cycle (for debugging purposes).
void Canvas::setUpdateScreenCopy (bool b)
Mutator for keeping track of the screen's drawn buffer.
Parameters
b Whether to copy the screen's contents to an RGB color buffer every draw cycle.
Note
The buffer in question can be accessed with getScreenBuffer().
takeScreenShot() and recordForNumFrames() automatically sets this to true.
int Canvas::start ()
Opens the Canvas.
This function starts rendering the Canvas.
Returns
0 if start is successful, -1 if the canvas has already started.
See also
close(), end()
void Canvas::stopRecording ()
Stops recording the Canvas.
This function stops dumping images to the file system.
void Canvas::takeScreenShot ()
Takes a screenshot.
This function saves a screenshot of the current Canvas to the working directory.
Bug
Bug Multiple calls to this function in rapid succession seem to make the FPS counter inaccurate and make rendering slowdown.
The documentation for this class was generated from the following files:
Canvas.h
Canvas.cpp