tsgl::Canvas Class Reference
A GL window with numerous built-in, thread-safe drawing operations.
#include <Canvas.h>
Public Member Functions
Canvas (double timerLength=0.0f)
Default Canvas constructor method.
Canvas (int x, int y, int width, int height, std::string title, double timerLength=0.0f)
Explicit Canvas constructor method.
virtual ~Canvas ()
Canvas destructor method.
void bindToButton (Key button, Action action, voidFunction function)
Binds a key or button to a function.
void bindToScroll (std::function< void(double, double)> function)
Binds the mouse wheel to a function.
void clear ()
Clears the Canvas.
void close ()
Closes the Canvas window.
virtual void drawCircle (int x, int y, int radius, int sides, ColorFloat color=BLACK, bool filled=true)
Draws a circle.
virtual void drawConcavePolygon (int size, int xverts[], int yverts[], ColorFloat color[], bool filled=true)
Draws a concave polygon with colored vertices.
virtual void drawConvexPolygon (int size, int xverts[], int yverts[], ColorFloat color[], bool filled=true)
Draws a convex polygon with colored vertices.
virtual void drawImage (std::string filename, int x, int y, int width, int height, float alpha=1.0f)
Draws an image.
virtual void drawLine (int x1, int y1, int x2, int y2, ColorFloat color=BLACK)
Draws a line.
virtual void drawPixel (int row, int col, ColorFloat color=BLACK)
Draws a single pixel, specified in row,column format.
virtual void drawPoint (int x, int y, ColorFloat color=BLACK)
Draws a single pixel, specified in x,y format.
virtual void drawProgress (ProgressBar *p)
Draws a progress bar.
virtual void drawRectangle (int x1, int y1, int x2, int y2, ColorFloat color=BLACK, bool filled=true)
Draws a rectangle.
virtual void drawText (std::string text, int x, int y, unsigned size, ColorFloat color=BLACK)
Draw a string of text.
virtual void drawText (std::wstring text, int x, int y, unsigned int size, ColorFloat color)
Draws a string of text.
virtual void drawTriangle (int x1, int y1, int x2, int y2, int x3, int y3, ColorFloat color=BLACK, bool filled=true)
Draws a triangle.
virtual void drawTriangleStrip (int size, int xverts[], int yverts[], ColorFloat color[], bool filled=true)
Draws an arbitrary triangle strip with colored vertices.
ColorFloat getBackgroundColor ()
Accessor for the current background color.
int getFrameNumber ()
Accessor for the current frame number.
float getFPS ()
Accessor for the current FPS.
bool getIsOpen ()
Accessor for window's closed status.
int getMouseX ()
Accessor for the mouse's x-position.
int getMouseY ()
Accessor for the mouse's y-position.
ColorInt getPixel (int row, int col)
Gets the color of the pixel drawn on the current Canvas at the given screen coordinates, specified in row,column format.
ColorInt getPoint (int x, int y)
Gets the color of the pixel drawn on the current Canvas at the given screen coordinates, specified in x,y format.
unsigned int getReps () const
Accessor for the number of theoretical draw cycles that have elapsed.
uint8_t * getScreenBuffer ()
Accessor for the Canvas's currently drawn image.
double getTime ()
Accessor for the time since the Canvas was initialized.
double getTimeBetweenSleeps () const
Accessor that gets the time between two sleep times of the internal drawing timer of a Canvas object.
int getWindowHeight ()
Accessor for the Canvas's window height.
int getWindowWidth ()
Accessor for the Canvas's window width.
int getWindowX ()
Accessor for the Canvas's x-position.
int getWindowY ()
Accessor for the Canvas's y-position.
void handleIO ()
Manually handles keyboard/mouse I/O.
void pauseDrawing ()
Pauses the rendering thread of the Canvas.
void recordForNumFrames (unsigned int num_frames)
Records the Canvas for a specified number of frames.
void reset ()
Resets the internal drawing timer of a Canvas instance.
void resumeDrawing ()
Resumes the rendering thread of the Canvas.
virtual void run (void(*myFunction)(Canvas &))
Start the Canvas, run a function on it, and wait for the user to close it.
virtual void run (void(*myFunction)(Canvas &, int), int i)
Overload for run()
virtual void run (void(*myFunction)(Canvas &, unsigned), unsigned u)
Overload for run()
virtual void run (void(*myFunction)(Canvas &, int, int), int i1, int i2)
Overload for run()
virtual void run (void(*myFunction)(Canvas &, unsigned, unsigned), unsigned u1, unsigned u2)
Overload for run()
virtual void run (void(*myFunction)(Canvas &, std::string), std::string s)
Overload for run()
virtual void run (void(*myFunction)(Canvas &, int, std::string), int i, std::string s)
Overload for run()
virtual void run (void(*myFunction)(Canvas &, std::string, int), std::string s, int i)
Overload for run()
void setBackgroundColor (ColorFloat color)
Mutator for the background color.
void setFont (std::string filename)
Mutator for the currently loaded font.
void setShowFPS (bool b)
Mutator for showing the FPS.
void sleep ()
Sleeps the calling thread to sync with the Canvas.
void sleepFor (float seconds)
Sleeps the calling thread for a set amount of time.
int start ()
Opens the Canvas.
void stop ()
Begins the process of closing the Canvas.
void stopRecording ()
Stops recording the Canvas.
void takeScreenShot ()
Takes a screenshot.
int wait ()
Waits for the user to close the Canvas.
Static Public Member Functions
static int getDisplayHeight ()
Accessor for the height of the user's primary monitor.
static int getDisplayWidth ()
Accessor for the width of the user's primary monitor.
static void runTests ()
Runs unit tests for the Canvas.
Protected Member Functions
void drawShape (Shape *s)
Protected Attributes
bool atiCard
Detailed Description
A GL window with numerous built-in, thread-safe drawing operations.
Canvas provides an easy-to-set-up, easy-to-use class for drawing various shapes.
Using STB, Canvas also supports the drawing of images.
On top of being easy to use, Canvas is also thread-safe, so any number of images may be drawn at once.
Note
OS X: Due to the way OS X handles I/O, either sleep() or handleIO() must be manually called whenever the user wants to handle any input/output events (keyboard/mouse presses). Whenever a window is created using OpenGL, OS X requires the main thread to handle I/O calls.
OS X: OS X also uses p_thread instead of std::thread for threading.
Bug
Bug Linux: X forwarding does not work properly with TSGL.
Constructor & Destructor Documentation
tsgl::Canvas::Canvas (double timerLength = 0.0f)
Default Canvas constructor method.
This is the default constructor for the Canvas class.
Parameters
timerLength The minimum number of seconds between draw cycles for the Canvas. A value less than or equal to 0 sets it to automatic.
Returns
A new Canvas in the middle of the screen with no title. The created Canvas will take up approximately 90% of the monitor's height, and will have a 4:3 aspect ratio.
tsgl::Canvas::Canvas (int x, int y, int width, int height, std::string title, double timerLength = 0.0f)
Explicit Canvas constructor method.
This is the explicit constructor for the Canvas class.
Parameters
x The x position of the Canvas window.
y The y position of the Canvas window.
width The x dimension of the Canvas window.
height The y dimension of the Canvas window.
title The title of the window.
timerLength The minimum number of seconds between draw cycles for the Canvas. A value less than or equal to 0 sets it to automatic.
Returns
A new Canvas with the specified position, dimensions, title, and draw cycle length.
tsgl::Canvas::~Canvas () [virtual]
Canvas destructor method.
This is the destructor for the Canvas class.
Frees up memory that was allocated to a Canvas instance.
Member Function Documentation
void tsgl::Canvas::bindToButton (Key button, Action action, voidFunction function)
Binds a key or button to a function.
This function binds a key or mouse button to a function pointer.
Upon pressing or releasing the given key, Canvas will call the specified function.
Parameters
button The key or button to bind, as specified in Keynums.h.
action The action to look out for (TSGL_PRESS or TSGL_RELEASE).
function The function to call upon action a on button.
Warning
TSGL_KEY_ESCAPE is automatically bound to closing the window. Overriding TSGL_KEY_ESCAPE will likely make you unable to close the window through the escape key.
void tsgl::Canvas::bindToScroll (std::function< void(double, double)> function)
Binds the mouse wheel to a function.
This function binds the mouse wheel to a function pointer.
Upon scrolling, Canvas will call the specified function.
Parameters
function A function taking x and y parameters to be called when the mouse is scrolled.
void tsgl::Canvas::clear ()
Clears the Canvas.
This function clears the screen to the color specified in setBackgroundColor().
Referenced by tsgl::Spectrogram::draw().
void tsgl::Canvas::close ()
Closes the Canvas window.
This function tells the Canvas to stop rendering and to close its rendering window.
Any threads that have called wait() will continue.
See also
start(), stop(), wait()
Referenced by tsgl::VisualTaskQueue::close(), and stop().
void tsgl::Canvas::drawCircle (int x, int y, int radius, int sides, ColorFloat color = BLACK, bool filled = true) [virtual]
Draws a circle.
This function draws a circle with the given center, radius, resolution (number of sides), color, and fill status.
Parameters
x The x coordinate of the circle's center.
y The y coordinate of the circle's center.
radius The radius of the circle in pixels.
sides The number of sides to use in the circle.
color The color of the circle (set to BLACK by default).
filled Whether the circle should be filled (set to true by default).
Referenced by tsgl::CartesianCanvas::drawCircle().
void tsgl::Canvas::drawConcavePolygon (int size, int xverts[], int yverts[], ColorFloat color[], bool filled = true) [virtual]
Draws a concave polygon with colored vertices.
This function draws a ConcavePolygon with the given vertex data, specified as the outer perimeter of the polygon.
Parameters
size The number of vertices in the polygon.
xverts An array of x positions of said vertices.
yverts An array of y positions of said vertices.
color An array of colors for the said vertices.
filled Whether the Concave polygon should be filled in or not (set to true by default).
Warning
This function is significantly slower than drawConvexPolygon(). It is not recommended that you draw convex polygons with this function.
See also
drawConvexPolygon().
Referenced by tsgl::CartesianCanvas::drawConcavePolygon().
void tsgl::Canvas::drawConvexPolygon (int size, int xverts[], int yverts[], ColorFloat color[], bool filled = true) [virtual]
Draws a convex polygon with colored vertices.
This function draws a ConvexPolygon with the given vertex data, specified as the outer perimeter of the polygon.
Parameters
size The number of vertices in the polygon.
xverts An array of the x positions of said vertices.
yverts An array of the y positions of said vertices.
color An array of colors for the said vertices.
filled Whether the ConvexPolygon should be filled in or not (set to true by default).
Note
The difference between a convex polygon and a concave polygon is that a convex polygon has all interior angles less than 180 degrees (see http://www.mathopenref.com/polygonconvex.html).
Referenced by tsgl::Spectrogram::draw(), and tsgl::CartesianCanvas::drawConvexPolygon().
void tsgl::Canvas::drawImage (std::string filename, int x, int y, int width, int height, float alpha = 1.0f) [virtual]
Draws an image.
This function draws an Image with the given coordinates and dimensions.
Parameters
filename The name of the file to load the image from.
x The x coordinate of the Image's left edge.
y The y coordinate of the Image's top edge.
width The width of the Image.
height The height of the Image.
alpha The alpha with which to draw the Image
Referenced by tsgl::CartesianCanvas::drawImage().
void tsgl::Canvas::drawLine (int x1, int y1, int x2, int y2, ColorFloat color = BLACK) [virtual]
Draws a line.
This function draws a Line at the given coordinates with the given color.
Parameters
x1 The x position of the start of the line.
y1 The y position of the start of the line.
x2 The x position of the end of the line.
y2 The y position of the end of the line.
color The color of the line (set to BLACK by default).
Referenced by tsgl::Spectrogram::draw(), and tsgl::CartesianCanvas::drawLine().
void tsgl::Canvas::drawPixel (int row, int col, ColorFloat color = BLACK) [inline], [virtual]
Draws a single pixel, specified in row,column format.
This function draws a pixel at the given screen coordinates with the given color.
Note
(0,0) signifies the top-left of the screen when working with a Canvas object.
(0,0) signifies the bottom-left of the screen when working with a CartesianCanvas object.
Parameters
row The row (y-position) of the pixel.
col The column (x-position) of the pixel.
color The color of the point (set to BLACK by default).
See also
drawPoint()
void tsgl::Canvas::drawPoint (int x, int y, ColorFloat color = BLACK) [virtual]
Draws a single pixel, specified in x,y format.
This function draws a pixel at the given Cartesian coordinates with the given color.
Note
(0,0) signifies the left-top of the screen when working with a Canvas object.
(0,0) signifies the left-bottom of the screen when working with a CartesianCanvas object.
Parameters
x The x position of the point.
y The y position of the point.
color The color of the point (set to BLACK by default).
See also
drawPixel()
Referenced by drawPixel(), and tsgl::CartesianCanvas::drawPoint().
void tsgl::Canvas::drawProgress (ProgressBar * p) [virtual]
Draws a progress bar.
This function draws a previously created ProgressBar to the Canvas, as specified in that ProgressBar's constructor.
Parameters
p A pointer to a ProgressBar.
Note
There is no equivalent function for CartesianCanvas. If you'd like to draw a ProgressBar on a CartesianCanvas, you can still use this function, but you must use absolute Canvas coordinates rather than the scaled CartesianCanvas coordinates.
void tsgl::Canvas::drawRectangle (int x1, int y1, int x2, int y2, ColorFloat color = BLACK, bool filled = true) [virtual]
Draws a rectangle.
This function draws a Rectangle with the given coordinates, dimensions, and color.
Parameters
x1 The x coordinate of the Rectangle's left edge.
y1 The y coordinate of the Rectangle's top edge.
x2 The x coordinate of the Rectangle's right edge.
y2 The y coordinate of the Rectangle's bottom edge.
color The color of the rectangle (set to BLACK by default).
filled Whether the rectangle should be filled (set to true by default).
Bug
Bug The bottom-right pixel of a non-filled rectangle may not get drawn on some machines.
Referenced by tsgl::CartesianCanvas::drawRectangle(), tsgl::VisualTaskQueue::reset(), tsgl::VisualTaskQueue::showLegend(), and tsgl::VisualTaskQueue::update().
void tsgl::Canvas::drawText (std::string text, int x, int y, unsigned size, ColorFloat color = BLACK) [virtual]
Draw a string of text.
This function draws a given string of Text at the given coordinates with the given color.
Parameters
text The string to draw.
x The x coordinate of the text's left bound.
y The y coordinate of the text's left bound.
size The size of the text in pixels.
color The color of the Text (set to BLACK by default).
Referenced by drawProgress(), tsgl::CartesianCanvas::drawText(), and tsgl::VisualTaskQueue::showLegend().
virtual void tsgl::Canvas::drawText (std::wstring text, int x, int y, unsigned int size, ColorFloat color) [virtual]
Draws a string of text.
This function draws a given string of Text at the given coordinates with the given color.
Parameters
text The UTF8-encoded string to draw.
x The x coordinate of the text's left bound.
y The y coordinate of the text's left bound.
size The size of the text in pixels.
color The color of the Text (set to BLACK by default).
Note
Identical to the drawText(std::string, ...) aside from the first parameter.
See also
drawText(std::string s, int x, int y, unsigned size, ColorFloat color = BLACK)
void tsgl::Canvas::drawTriangle (int x1, int y1, int x2, int y2, int x3, int y3, ColorFloat color = BLACK, bool filled = true) [virtual]
Draws a triangle.
This function draws a Triangle with the given vertices.
Parameters
x1 The x coordinate of the first vertex of the Triangle.
y1 The y coordinate of the first vertex of the Triangle.
x2 The x coordinate of the second vertex of the Triangle.
y2 The y coordinate of the second vertex of the Triangle.
x3 The x coordinate of the third vertex of the Triangle.
y3 The y coordinate of the third vertex of the Triangle.
color The color of the Triangle (set to BLACK by default).
filled Whether the Triangle should be filled (set to true by default).
Referenced by tsgl::CartesianCanvas::drawTriangle().
void tsgl::Canvas::drawTriangleStrip (int size, int xverts[], int yverts[], ColorFloat color[], bool filled = true) [virtual]
Draws an arbitrary triangle strip with colored vertices.
This function draws a TriangleStrip with the given vertex data, specified as a triangle strip.
Parameters
size The number of vertices in the polygon.
xverts An array of x positions of the vertices.
yverts An array of y positions of the vertices.
color An array of colors for the vertices.
filled Whether the triangle strip should be filled (true) or not (false).
Referenced by tsgl::CartesianCanvas::drawTriangleStrip().
ColorFloat tsgl::Canvas::getBackgroundColor ()
Accessor for the current background color.
Returns
The color that the Canvas clears to when clear() is called.
int tsgl::Canvas::getDisplayHeight () [static]
Accessor for the height of the user's primary monitor.
Returns
The height of the user's primary monitor.
int tsgl::Canvas::getDisplayWidth () [static]
Accessor for the width of the user's primary monitor.
Returns
The width of the user's primary monitor.
float tsgl::Canvas::getFPS ()
Accessor for the current FPS.
Returns
The average number of frames being rendered per second.
int tsgl::Canvas::getFrameNumber ()
Accessor for the current frame number.
Returns
The number of actual draw cycles / frames the Canvas has rendered so far.
See also
getReps()
bool tsgl::Canvas::getIsOpen ()
Accessor for window's closed status.
Returns
Whether the window is still open (that is, the user has not closed it).
Referenced by tsgl::VisualTaskQueue::close(), tsgl::CartesianCanvas::drawFunction(), tsgl::CartesianCanvas::drawPartialFunction(), tsgl::IntegralViewer::rectangleEvaluate(), tsgl::IntegralViewer::trapezoidEvaluate(), and tsgl::IntegralViewer::~IntegralViewer().
int tsgl::Canvas::getMouseX ()
Accessor for the mouse's x-position.
Returns
The x coordinates of the mouse on the Canvas.
int tsgl::Canvas::getMouseY ()
Accessor for the mouse's y-position.
Returns
The y coordinates of the mouse on the Canvas.
ColorInt tsgl::Canvas::getPixel (int row, int col)
Gets the color of the pixel drawn on the current Canvas at the given screen coordinates, specified in row,column format.
Note
(0,0) signifies the top-left of the screen when working with a Canvas object.
(0,0) signifies the bottom-left of the screen when working with a CartesianCanvas.
getPixel() will return only what is currently drawn the screen. Any object waiting to be drawn will not affect what is returned.
Parameters
row The row (y-position) of the pixel to grab.
col The column (x-position) of the pixel to grab.
Returns
A ColorInt containing the color of the pixel at (col,row).
ColorInt tsgl::Canvas::getPoint (int x, int y)
Gets the color of the pixel drawn on the current Canvas at the given screen coordinates, specified in x,y format.
Note
(0,0) signifies the left-top of the screen when working with a Canvas object.
(0,0) signifies the left-bottom of the screen when working with a CartesianCanvas.
getPoint() will return only what is currently drawn the screen. Any object waiting to be drawn will not affect what is returned.
Parameters
x The x position of the pixel to grab.
y The y position of the pixel to grab.
Returns
A ColorInt containing the color of the pixel at (x, y).
Referenced by getPixel().
unsigned int tsgl::Canvas::getReps () const
Accessor for the number of theoretical draw cycles that have elapsed.
This function returns the time elapsed since the Canvas has been opened divided by the drawTimer's period.
Returns
The number of times the drawTimer has expired since starting the Canvas.
See also
getFrameNumber()
uint8_t * tsgl::Canvas::getScreenBuffer ()
Accessor for the Canvas's currently drawn image.
Returns
A pointer to the RGB pixel buffer for the current Canvas.
Note
The array starts in the bottom left corner of the image, and is in row-major ordering.
Deprecated
Deprecated This function returns a pointer directly to the Canvas' screen buffer. This function may be removed in future versions of TSGL. Please use getPixel() or getPoint() get individual pixels.
double tsgl::Canvas::getTime ()
Accessor for the time since the Canvas was initialized.
Returns
The elapsed time in microseconds since the Canvas has started drawing.
double tsgl::Canvas::getTimeBetweenSleeps () const
Accessor that gets the time between two sleep times of the internal drawing timer of a Canvas object.
Returns
The time between two sleep cycles of the internal drawing timer.
int tsgl::Canvas::getWindowHeight ()
Accessor for the Canvas's window height.
Returns
The height in pixels of the Canvas window.
Referenced by tsgl::CartesianCanvas::getCartesianCoordinates(), tsgl::CartesianCanvas::getScreenCoordinates(), tsgl::CartesianCanvas::recomputeDimensions(), and tsgl::VisualTaskQueue::showLegend().
int tsgl::Canvas::getWindowWidth ()
Accessor for the Canvas's window width.
Returns
The width in pixels of the Canvas window.
Referenced by tsgl::CartesianCanvas::getCartesianCoordinates(), tsgl::CartesianCanvas::recomputeDimensions(), and tsgl::VisualTaskQueue::showLegend().
int tsgl::Canvas::getWindowX ()
Accessor for the Canvas's x-position.
Returns
The x coordinate in pixels of the left of the Canvas (0 = left of monitor).
Referenced by tsgl::VisualTaskQueue::showLegend().
int tsgl::Canvas::getWindowY ()
Accessor for the Canvas's y-position.
Returns
The y coordinate in pixels of the top of the Canvas (0 = top of monitor).
Referenced by tsgl::VisualTaskQueue::showLegend().
void tsgl::Canvas::handleIO ()
Manually handles keyboard/mouse I/O.
Note
This function will return immediately if not called from the main thread.
OS X: This function exists for OS X compatibility purposes. This function does nothing on Linux or Windows.
Referenced by sleep(), and sleepFor().
void tsgl::Canvas::pauseDrawing ()
Pauses the rendering thread of the Canvas.
This function forces the calling thread to wait until the Canvas finishes its draw cycle, them prevents the Canvas from rendering further updates until resumeDrawing is called.
Note
This method may be called from any number of threads, so long as a matching number of calls to resumeDrawing() are made.
Warning
This function makes use of a mutex lock. Do not call this without later calling resumeDrawing().
See also
resumeDrawing()
Referenced by tsgl::Spectrogram::draw().
void tsgl::Canvas::recordForNumFrames (unsigned int num_frames)
Records the Canvas for a specified number of frames.
This function starts dumping screenshots of the Canvas to the working directory every draw cycle.
Images are saved as ImageXXXXXX.png, where XXXXXX is the current frame number.
The function automatically terminates after num_frames cycles have completed.
Parameters
num_frames The number of frames to dump screenshots for.
void tsgl::Canvas::reset ()
Resets the internal drawing timer of a Canvas instance.
This function resets the starting time of the Canvas' draw timer to the current time.
void tsgl::Canvas::resumeDrawing ()
Resumes the rendering thread of the Canvas.
This function should be called after pauseDrawing to let the Canvas' rendering thread know that it may resume rendering.
Note
This method may be called from any number of threads, so long as a matching number of calls to pauseDrawing() are made.
Warning
This function makes use of a mutex lock. Do not call this without having first called pauseDrawing().
See also
pauseDrawing()
Referenced by tsgl::Spectrogram::draw().
void tsgl::Canvas::run (void(*)(Canvas &) myFunction) [virtual]
Start the Canvas, run a function on it, and wait for the user to close it.
This function binds another function to the current Canvas, waits until that function is complete, and waits for the user to close the Canvas. This function effectively calls start(), myFunction(), and wait() in sequence.
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
void tsgl::Canvas::run (void(*)(Canvas &, int) myFunction, int i) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
i An integer argument to myFunction
void tsgl::Canvas::run (void(*)(Canvas &, unsigned) myFunction, unsigned u) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
u An unsigned integer argument to myFunction
void tsgl::Canvas::run (void(*)(Canvas &, int, int) myFunction, int i1, int i2) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
i1 An integer argument to myFunction
i2 An integer argument to myFunction
void tsgl::Canvas::run (void(*)(Canvas &, unsigned, unsigned) myFunction, unsigned u1, unsigned u2) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
u1 An unsigned integer argument to myFunction
u2 An unsigned integer argument to myFunction
void tsgl::Canvas::run (void(*)(Canvas &, std::string) myFunction, std::string s) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
s A string argument to myFunction
void tsgl::Canvas::run (void(*)(Canvas &, int, std::string) myFunction, int i, std::string s) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
i An integer argument to myFunction
s A string argument to myFunction
void tsgl::Canvas::run (void(*)(Canvas &, std::string, int) myFunction, std::string s, int i) [virtual]
Overload for run()
Parameters
myFunction The function to run on the Canvas. Must take exactly one parameter of type Canvas&, which is a reference to the Canvas to render to.
s A string argument to myFunction
i An integer argument to myFunction
void tsgl::Canvas::setBackgroundColor (ColorFloat color)
Mutator for the background color.
This function sets the clear color for when Canvas::clear() is called.
Parameters
color The color to clear to.
Note
The alpha channel of the color is ignored.
Referenced by tsgl::CartesianCanvas::runTests(), and runTests().
void tsgl::Canvas::setFont (std::string filename)
Mutator for the currently loaded font.
This function sets the font with the specified filename into memory. Subsequent calls to drawText() will use this font to print.
Parameters
filename The filename of the font to load.
Note
Supports all font types that FreeType supports.
void tsgl::Canvas::setShowFPS (bool b)
Mutator for showing the FPS.
Parameters
b Whether to print the FPS to stdout every draw cycle (for debugging purposes).
void tsgl::Canvas::sleep ()
Sleeps the calling thread to sync with the Canvas.
Tells the calling thread to sleep until the Canvas' drawTimer expires.
Note
It is recommened that you call sleep() at least once before doing any drawing; otherwise, the Canvas may not render the first frame of drawing.
OS X: This function automatically calls handleIO() on OS X.
Referenced by tsgl::CartesianCanvas::sleep().
void tsgl::Canvas::sleepFor (float seconds)
Sleeps the calling thread for a set amount of time.
Tells the calling thread to sleep for seconds seconds.
Parameters
seconds Number of seconds to sleep for
Note
OS X: This function automatically calls handleIO() on OS X.
Referenced by tsgl::CartesianCanvas::drawFunction(), tsgl::CartesianCanvas::drawPartialFunction(), handleIO(), resumeDrawing(), and wait().
int tsgl::Canvas::start ()
Opens the Canvas.
This function opens a GL window and tells the Canvas to start rendering.
Returns
0 if start is successful, -1 if the canvas has already started.
See also
wait(), stop(), close()
Referenced by tsgl::CartesianCanvas::run(), run(), tsgl::CartesianCanvas::runTests(), runTests(), tsgl::VisualTaskQueue::showLegend(), tsgl::Spectrogram::Spectrogram(), and tsgl::VisualTaskQueue::VisualTaskQueue().
void tsgl::Canvas::stop ()
Begins the process of closing the Canvas.
This function calls close() followed by wait() to gracefully close the Canvas at the earliest available opportunity.
See also
start(), wait(), close()
Referenced by tsgl::CartesianCanvas::runTests(), runTests(), and tsgl::IntegralViewer::~IntegralViewer().
void tsgl::Canvas::stopRecording ()
Stops recording the Canvas.
This function tells the Canvas to stop dumping images to the file system.
void tsgl::Canvas::takeScreenShot ()
Takes a screenshot.
This function saves a screenshot of the current Canvas to the working directory.
Images are saved as ImageXXXXXX.png, where XXXXXX is the current frame number.
Bug
Bug Multiple calls to this function in rapid succession render the FPS counter inaccurate.
int tsgl::Canvas::wait ()
Waits for the user to close the Canvas.
This function blocks the calling thread until the user closes the Canvas or until close() is called. This function has no effect if the Canvas has not started.
Returns
0 if exit is successful, -1 if the Canvas has not started yet.
See also
start(), end(), close(), stop().
Referenced by tsgl::VisualTaskQueue::close(), tsgl::Spectrogram::finish(), tsgl::IntegralViewer::rectangleEvaluate(), tsgl::CartesianCanvas::run(), run(), tsgl::CartesianCanvas::runTests(), stop(), and tsgl::IntegralViewer::trapezoidEvaluate().
The documentation for this class was generated from the following files:
Canvas.h
Canvas.cpp