tsgl::TextureHandler Class Reference
Handles saving, loading, and rendering of images and textures.
#include <TextureHandler.h>
Public Member Functions
TextureHandler ()
Default TextureHandler constructor method.
~TextureHandler ()
TextureHandler destructor method.
bool drawText (std::wstring text, unsigned int font_size, float *vertices)
Draws text.
bool loadFont (const std::string &filename)
Loads a font.
GLtexture loadPicture (std::string filename, unsigned int &width, unsigned int &height, GLtexture &texture)
Loads an image.
bool saveImageToFile (std::string filename, GLubyte *pixels, unsigned int width, unsigned int height) const
Saves an Image.
Static Public Member Functions
static void getDimensions (std::string filename, int &width, int &height)
Gets the dimensions of an image.
static void runTests ()
Runs the Unit tests for TextureHandler.
Detailed Description
Handles saving, loading, and rendering of images and textures.
TextureHandler provides an interface for saving, loading, and rendering images and text to Canvas and CartesianCanvas through the use of GLTextures.
Constructor & Destructor Documentation
tsgl::TextureHandler::TextureHandler ()
Default TextureHandler constructor method.
This is the default constructor for theTextureHandler Canvas class.
Returns
A new TextureHandler instance.
tsgl::TextureHandler::~TextureHandler ()
TextureHandler destructor method.
This is the destructor for the TextureHandler class.
Frees up memory that was allocated to a TextureHandler instance.
Member Function Documentation
bool tsgl::TextureHandler::drawText (std::wstring text, unsigned int font_size, float * vertices)
Draws text.
Draws the text specified by its parameters onto a Canvas.
Parameters
text The UTF-8 encoded string of text to be drawn.
font_size The size of the text in pixels.
vertices An array of vertex data for the bonding box of the text.
Note
vertices will be partially automatically set by drawText() itself in order to draw / kern the text properly, but the color, starting position, and texture coordinates will be left unchanged.
If no font is loaded before calling this function, TSGL will attempt to locate a default font at ../assets/freefont/FreeMono.ttf.
Returns
True if successful, false otherwise.
Bug
Bug If the default font cannot be located, TSGL will crash.
Referenced by tsgl::Text::draw().
void tsgl::TextureHandler::getDimensions (std::string filename, int & width, int & height) [static]
Gets the dimensions of an image.
Loads the header of a .png, .jpeg, or .bmp image to read their dimensions.
Parameters
filename The file name of the picture.
width A reference variable for holding the width of the picture.
height A reference variable for holding the height of the picture.
Returns
The texture that created from the loaded image.
Referenced by tsgl::Image::Image().
bool tsgl::TextureHandler::loadFont (const std::string & filename)
Loads a font.
Loads a font from the library given by filename.
Parameters
filename The file name of the font to be loaded.
Warning
If the font cannot be found then an error message is printed out.
If the font library is not correctly installed then an error message is printed out.
If the font is not supported then an error message is printed out.
Returns
True if successful, false otherwise.
Referenced by drawText(), and tsgl::Canvas::setFont().
GLtexture tsgl::TextureHandler::loadPicture (std::string filename, unsigned int & width, unsigned int & height, GLtexture & texture)
Loads an image.
Loads a .png, .jpeg, or .bmp image from a file.
Parameters
filename The file name of the picture.
width A reference variable for holding the width of the picture.
height A reference variable for holding the height of the picture.
texture A reference variable for holding the texture of the picture. (same as return value)
Returns
The texture that created from the loaded image.
Referenced by tsgl::Image::draw().
bool tsgl::TextureHandler::saveImageToFile (std::string filename, GLubyte * pixels, unsigned int width, unsigned int height) const
Saves an Image.
Saves an Image to file that was captured from a Canvas object.
Parameters
filename The name of the file to save the Image to.
pixels The pixel data for the Image.
width The width of the Image.
height The height of the Image.
Returns
True if successful, false otherwise.
The documentation for this class was generated from the following files:
TextureHandler.h
TextureHandler.cpp