LifeFarm Class Reference
Simulate Conway's Game of Life!
#include <LifeFarm.h>
Public Member Functions
LifeFarm (int w, int h, Canvas *can, bool randomize)
Explicitly constructs a LifeFarm object.
~LifeFarm ()
Destroy a LifeFarm object.
void addAnt (int x, int y)
Add an ant.
void moveAnts ()
Move the ants.
void moveAntsOld ()
Move the ants.
void moveAntsNew ()
Move the ants.
void setDrawdead (bool b)
Draw `dead` ants.
void life (int *current, int *fresh)
Give life to the ants!
Public Attributes
int width
int height
int size
Canvas * can
Detailed Description
Simulate Conway's Game of Life!
Contains the data and methods needed in order to simulate Conway's Game of Life.
see https://en.wikipedia.org/wiki/Conway's_Game_of_Life for more details on what Conway's Game of Life is.
Constructor & Destructor Documentation
LifeFarm()
LifeFarm::LifeFarm (int w, int h, Canvas * can, bool randomize)
Explicitly constructs a LifeFarm object.
Explicit constructor for the LifeFarm class.
Parameters
w The width of the LifeFarm object.
h The height of the LifeFarm object.
can Pointer to the Canvas to draw to.
randomize Determines if we should randomize the motion of the ants that are currently in the LifeFarm object.
 LifeFarm()
LifeFarm::~LifeFarm ()
Destroy a LifeFarm object.
Destructor for the LifeFarm class.
Returns
Frees up any allocated memory to a LifeFarm object.
Member Function Documentation
addAnt()
void LifeFarm::addAnt (int x, int y)
Add an ant.
Adds an ant to the LifeFarm object.
Parameters
x The x coordinate of the ant in the LifeFarm object.
y The y coordinate of the ant in the LifeFarm object.
Referenced by LifeFarm(), and moveAntsOld().
life()
void LifeFarm::life (int * current, int * fresh)
Give life to the ants!
Makes the ants come alive by keeping track of their current positions and next state positions.
Parameters
*current A pointer to an array of current states that the ants are in during the game.
*fresh A pointer to an array of next states that the ants are going to be in during the game.
Referenced by moveAntsNew().
moveAnts()
void LifeFarm::moveAnts ()
Move the ants.
Move the ants that are currently in the LifeFarm object.
Note
This method class moveAntsOld().
See also
moveAntsOld()
moveAntsNew()
void LifeFarm::moveAntsNew ()
Move the ants.
This method moves the ants around to new positions.
See also
moveAntsOld()
moveAntsOld()
void LifeFarm::moveAntsOld ()
Move the ants.
This method is called first in order to move the ants around in the LifeFarm object.
See also
moveAntsNew()
Referenced by moveAnts().
setDrawdead()
void LifeFarm::setDrawdead (bool b)
Draw `dead` ants.
Determines if we should draw ants that have `died` in the game.
Parameters
b A boolean that determines if we should draw the dead ants or not.
The documentation for this class was generated from the following files:
/home/rvree/TSGL_2.1/TSGL/src/examples/Conway/LifeFarm.h
/home/rvree/TSGL_2.1/TSGL/src/examples/Conway/LifeFarm.cpp