Philosopher Class Reference
Object representing a philosopher in the Dining Philosophers' problem.
#include <Philosopher.h>
Public Member Functions
Philosopher ()
Explicitly constructs a new Philosopher.
void draw (Canvas &can, float x, float y)
void refreshColor ()
void addMeal ()
bool acquire (Fork &f)
bool release (Fork &f)
void think ()
void eat ()
Resets the Philosopher to thinking after he eats.
void setState (PhilState s)
Mutator for myState.
void setAction (PhilAction a)
Mutator for myAction.
void setId (int i, int nphil)
Mutator for id.
int getMeals ()
PhilState state ()
PhilAction action ()
int getId ()
bool hasCircle ()
Detailed Description
Object representing a philosopher in the Dining Philosophers' problem.
The Philosopher class contains variables and methods necessary for representing a philosopher at a table. Each Philosopher may acquire or release the fork to his left or to his right (or both), with his state changing accordingly.
Constructor & Destructor Documentation
Philosopher()
Philosopher::Philosopher ()
Explicitly constructs a new Philosopher.
Explicit constructor for a new Philosopher object.
Member Function Documentation
acquire()
bool Philosopher::acquire (Fork & f)
Picks up a fork specified by its reference
Referenced by Table::actStep().
action()
PhilAction Philosopher::action () [inline]
Accessor for Philosopher's action.
addMeal()
void Philosopher::addMeal ()
Adds a meal representation to meals and the Canvas
Referenced by Table::drawStep().
draw()
void Philosopher::draw (Canvas & can, float x, float y)
Adds Philosopher to Canvas or refreshes its color.
Referenced by Table::drawStep().
getId()
int Philosopher::getId () [inline]
Accessor for Philosopher's id.
getMeals()
int Philosopher::getMeals () [inline]
Accessor for number of meals Philosopher has consumed.
Referenced by Table::drawStep().
hasCircle()
bool Philosopher::hasCircle () [inline]
Accessor for Philosopher's circle.
refreshColor()
void Philosopher::refreshColor ()
Updates the Philosopher's color based on its state
Referenced by Table::drawStep().
release()
bool Philosopher::release (Fork & f)
Releases a fork specified by its reference
Referenced by Table::actStep().
setAction()
void Philosopher::setAction (PhilAction a) [inline]
Mutator for myAction.
Parameters
s PhilAction to set myAction to.
Referenced by Table::forfeitWhenBlockedMethod(), Table::hierarchyMethod(), Table::nFrameReleaseMethod(), Table::oddEvenMethod(), think(), and Table::waitWhenBlockedMethod().
setId()
void Philosopher::setId (int i, int nphil) [inline]
Mutator for id.
Parameters
i Which philosopher id to mutate
nphil Total number of philosophers.
Referenced by Philosopher(), and Table::Table().
setState()
void Philosopher::setState (PhilState s) [inline]
Mutator for myState.
Parameters
s PhilState to set myState to.
Referenced by Table::forfeitWhenBlockedMethod(), and think().
state()
PhilState Philosopher::state () [inline]
Accessor for Philosopher's state.
Referenced by Table::drawStep().
think()
void Philosopher::think ()
Thinks and switches to hungry state if a random number is a multiple of 3.
Referenced by Table::hierarchyMethod(), Table::nFrameReleaseMethod(), Table::oddEvenMethod(), and Table::waitWhenBlockedMethod().
The documentation for this class was generated from the following files:
/home/rvree/TSGL_2.1/TSGL/src/examples/DiningPhilosophers/Philosopher.h
/home/rvree/TSGL_2.1/TSGL/src/examples/DiningPhilosophers/Philosopher.cpp