Queue< Item > Class Template Reference
#include <Queue.h>
Public Member Functions
Queue ()
Queue (int size, Canvas &can)
void append (Item it, int proId)
Item remove ()
Item * getArray ()
int getCount ()
Item getFirst ()
Item getLast ()
int getCapacity ()
int * getPthreadIds ()
int getLastIndex ()
int getFirstIndex ()
bool isEmpty () const
bool isFull () const
void producerLock ()
void producerUnlock ()
void consumerLock ()
void consumerUnlock ()
~Queue ()
Detailed Description
template<class Item>
class Queue< Item >
Queue class contains the data necessary in order to create a custom Queue object. Used as a shared buffer in the Producer-Consumer visualization.
Constructor & Destructor Documentation
Queue() [1/2]
template<class Item >
Queue< Item >::Queue
Default constructor for the Queue class.
Queue() [2/2]
template<class Item >
Queue< Item >::Queue (int size, Canvas & can)
Explicit-constructor for the Queue class.
Parameters
   size, the size of the Queue.
 Queue()
template<class Item >
Queue< Item >::~Queue
Destructor for the Queue.
Member Function Documentation
append()
template<class Item >
void Queue< Item >::append (Item it, int proId)
append() puts an item into the Queue.
Parameters
   it, an Item to put into the Queue.
   proId, an int representing the pthread id. (Pthread condition variable logic adapted from TS_Queue code given to me by Professor Joel Adams).
Referenced by Producer::act().
consumerLock()
template<class Item >
void Queue< Item >::consumerLock
consumerLock() locks the Queue for the thread to remove an item
Referenced by Consumer::lock().
consumerUnlock()
template<class Item >
void Queue< Item >::consumerUnlock
consumerUnlock() locks the Queue after the thread to removes an item
Referenced by Consumer::unlock().
getArray()
template<class Item >
Item * Queue< Item >::getArray
getArray() is the accessor method for the array of the Queue.
Returns
: array, the array of items in the Queue.
getCapacity()
template<class Item >
int Queue< Item >::getCapacity
getCapacity() is the accessor method for the size of the Queue.
Returns
: size, an int representing the size of the Queue.
getCount()
template<class Item >
int Queue< Item >::getCount
getCount() is the accessor method for the number of elements currently in the Queue.
Returns
: count, an int representing the current number of elements in the Queue.
getFirst()
template<class Item >
Item Queue< Item >::getFirst
getFirst() is the accessor method for the first element in the Queue.
Returns
: first, an Item representing the first element in the Queue.
getLast()
template<class Item >
Item Queue< Item >::getLast
getLast() is the accessor method for the last element in the Queue.
Returns
: last, an Iteme representing the last element in the Queue.
getPthreadIds()
template<class Item >
int * Queue< Item >::getPthreadIds
getPthreadIds() is the accessor method for the stored pthread ids of the Producers. (They are used to determine the color of the Rectangle drawn around the circles in the visualization).
Returns
: ids, the array of stored pthread ids.
isEmpty()
template<class Item >
bool Queue< Item >::isEmpty
isEmpty() determines if the Queue is empty or not.
Returns
: myCount == 0, a boolean expression which evalutes to true or false.
isFull()
template<class Item >
bool Queue< Item >::isFull
isFull() determines if the Queue is full or not.
Returns
: myCount == mySize, a boolean expression which evalutes to true or false.
producerLock()
template<class Item >
void Queue< Item >::producerLock
producerLock() locks the Queue for the thread to append an item
Referenced by Producer::lock().
producerUnlock()
template<class Item >
void Queue< Item >::producerUnlock
producerUnlock() unlocks the Queue after the thread appends an item
Referenced by Producer::unlock().
remove()
template<class Item >
Item Queue< Item >::remove
remove() takes an Item out of the Queue.
Returns
: temp, an Item that was taken out of the Queue. (Pthread condition variable logic adapted from TS_Queue code given to me by Professor Joel Adams).
Referenced by Consumer::act().
The documentation for this class was generated from the following file:
/home/rvree/TSGL_2.1/TSGL/src/examples/ProducerConsumer/Queue.h