tsgl::Timer Class Reference
A class for various timing operations.
#include <Timer.h>
Public Member Functions
Timer (double period)
Default Timer constructor method.
virtual ~Timer ()
Timer destructor method.
unsigned int getReps () const
Gets the number of repetitions since starting the timer.
double getTime () const
Gets the elapsed time since starting the timer.
double getTimeBetweenSleeps () const
Get the elapsed time between sleeps.
bool pastPeriod ()
Check if the Timer's period has elapsed.
void reset (double period=0)
Reset the Timer.
void sleep (bool update=true)
Sleeps the Timer's current thread until its period elapses.
Static Public Member Functions
static void threadSleepFor (double duration)
Sleeps the current thread for the specified duration.
Detailed Description
A class for various timing operations.
Timer provides a simple timer for timing, sleeping threads, and keeping track of the current rendering frame.
Constructor & Destructor Documentation
Timer()
tsgl::Timer::Timer (double period)
Default Timer constructor method.
This is the default constructor for the Timer class.
Parameters
period Time in seconds specifying the maximum amount of time to sleep.
Returns
A new Timer with the specified period.
 Timer()
tsgl::Timer::~Timer () [virtual]
Timer destructor method.
This is the destructor for the Timer class.
Frees up memory that was allocated to a Timer instance.
Member Function Documentation
getReps()
unsigned int tsgl::Timer::getReps () const
Gets the number of repetitions since starting the timer.
Returns
The number of times the period</period> has elapsed since the Timer has been started.
Referenced by tsgl::Canvas::getReps(), and pastPeriod().
getTime()
double tsgl::Timer::getTime () const
Gets the elapsed time since starting the timer.
Returns
The time in seconds since starting the Timer.
Referenced by tsgl::Canvas::getTime().
getTimeBetweenSleeps()
double tsgl::Timer::getTimeBetweenSleeps () const
Get the elapsed time between sleeps.
This function returns the time in seconds between returning from the last two calls to sleep(). This should be the same as period in cases where the Timer is allowed to sleep. If the Timer has yet to sleep twice, getTimeBetweenSleeps() is undefined, but will most likely be less than 0.
Returns
The time in seconds between the last two sleeps.
Referenced by tsgl::Canvas::clearObjectBuffer(), and tsgl::Canvas::getTimeBetweenSleeps().
pastPeriod()
bool tsgl::Timer::pastPeriod ()
Check if the Timer's period has elapsed.
This function returns whether the period of the Timer has elapsed since the last time the function was called.
Returns
True if at least period seconds have elapsed since the last call, false otherwise.
reset()
void tsgl::Timer::reset (double period = 0)
Reset the Timer.
This function resets the starting time, repetitions, and period of the timer.
Parameters
period The new period for the Timer. Setting this less than or equal to 0 will keep the current period.
Referenced by tsgl::Canvas::reset(), and Timer().
sleep()
void tsgl::Timer::sleep (bool update = true)
Sleeps the Timer's current thread until its period elapses.
This function tells the currently executing thread to sleep until the rest of the Timer instance's remaining period expires.
If the Timer's period has elapsed since last call, the thread will continue execution normally until the next call to sleep().
Parameters
update Whether to update the timer's last_rep status or not.
Note
This function does not guarantee the thread will resume immediately after the time expires. Depending on your OS, the thread may sleep for longer.
See also
getTimeBetweenSleeps(), to get the actual elapsed time between sleeps.
Referenced by tsgl::Canvas::clearObjectBuffer(), and tsgl::Canvas::sleep().
threadSleepFor()
void tsgl::Timer::threadSleepFor (double duration) [static]
Sleeps the current thread for the specified duration.
This function tells the currently executing thread to sleep for duration seconds.
Note
This function does not guarantee the thread will resume immediately after duration expires. Depending on your OS, the thread may sleep for longer.
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp