Table Class Reference
Object managing the forks and philosophers in the Dining Philosophers' problem.
#include <Table.h>
Public Member Functions
Table (Canvas &can, int p, PhilMethod m)
Creates a new Table of dining philosophers.
~Table ()
Destructor for Table.
void forfeitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher should get.
void waitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher should get.
void nFrameReleaseMethod (int id)
Method for determining which fork a Philosopher should get.
void hierarchyMethod (int id)
Method for determining which fork a Philosopher should get.
void oddEvenMethod (int id)
Method for determining which fork a Philosopher should get.
void checkStep ()
Method for determining which method of resolution the philosopher is using.
void actStep ()
Method for philosopher to act based on myAction.
void drawStep ()
Method calculating angles calling draw methods of a philosopher and its fork or forks.
Detailed Description
Object managing the forks and philosophers in the Dining Philosophers' problem.
The Table class keeps track of the forks and philosophers in the Dining Philosophers' problem; it additionally manages the actions of the philosophers.
Each step of the problem is broken up into two phases. In the checking phase, the philosophers look at the table around them and, without communicating with the other philosophers, determine an action to take based on their state and the states of their adjacent forks.
In the action phase, each philosopher attempts to execute the action previously determined in the checking phase. If unsuccessful, the philosopher does nothing; otherwise, the philosopher's state changes depending on the action taken.
Constructor & Destructor Documentation
Table()
Table::Table (Canvas & can, int p, PhilMethod m)
Creates a new Table of dining philosophers.
Explicit constructor for a new Table object.
Parameters
can The Canvas on which the Table is to be drawn.
p Integer denoting the number of Philosophers at the Table
m PhilMethod denoting how the Philosophers should interact.
Member Function Documentation
forfeitWhenBlockedMethod()
void Table::forfeitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher should get.
Store the id numbers for the left and the right Philsopher's state.
Switch for the state of a Philosopher:
Philosopher has no fork:
If the right fork is free, try to get that fork.
Else, if the left fork is free, try to get that fork.
Else, do nothing.
Philosopher has right fork:
If the left fork is free, try to get that fork.
Philosopher has the left fork:
If the right fork is free, try to get that fork.
Else, release the left fork.
Philosopher has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher.
Note
This is an example of Deadlock amongst threads.
Referenced by checkStep().
hierarchyMethod()
void Table::hierarchyMethod (int id)
Method for determining which fork a Philosopher should get.
Store the states for the left and right Philosophers.
Switch statement for the state of the current Philosopher.
Philosopher has no forks:
If the right Philosopher's id is less than the left Philsopher's id:
If the right fork is free, try to get that fork.
Else, do nothing.
Else, if the left fork is free then try and get that fork.
Else, do nothing.
Philosopher has the right fork:
If the left fork is free, try and get that fork.
Else, do nothing.
Philosopher has the left fork:
If the right fork is free, try and get that fork.
Else, do nothing.
Philosopher has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher.
Referenced by checkStep().
nFrameReleaseMethod()
void Table::nFrameReleaseMethod (int id)
Method for determining which fork a Philosopher should get.
Store the states of the left and right Philosophers.
Switch statement for the current Philosopher:
Philosopher has no forks:
If the right fork is free, try to get that fork.
Else, if the left fork is free, try to get that fork.
Else, do nothing.
Philosopher has right fork:
If the left fork is free, try to get that fork.
Else, if the id of the current Philosopher is equal to the frame number of the Canvas modulo the number of Philosophers+1, then release the right fork.
Else, do nothing.
Philosopher has the left fork:
If the right fork is free, try and get that fork.
Else, if the id of the current Philosopher is equal to the frame number of the Canvas modulo the number of Philosophers+1, then release the left fork.
Else, do nothing.
Philosopher has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher.
Referenced by checkStep().
oddEvenMethod()
void Table::oddEvenMethod (int id)
Method for determining which fork a Philosopher should get.
Switch statement for the current Philosopher:
Philosopher has no forks:
If the Philosopher's id is even
Philosopher has right fork (odd id):
If the Philsopher's id modulo 2 is equal to the Canvas' current frame number modulo 2, then try and get the left fork.
Else, release the right fork.
Philosopher has left fork (even id):
If the Philsopher's id modulo 2 is equal to the Canvas' current frame number modulo 2, then try and get the right fork.
Else, release the left fork.
Philosopher has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher.
Note
This method is the one that works best.
Referenced by checkStep().
waitWhenBlockedMethod()
void Table::waitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher should get.
Store the states of the left and right Philosophers.
Switch for the state of the current Philosopher:
Philosopher has no forks:
If the right fork is free, try to get that fork.
Else if the left fork is free, try to get that fork.
Else, do nothing.
Philosopher has right fork:
If the left fork is free, try to get that fork.
Else, do nothing.
Philosopher has the left fork:
If the right fork is free, try to get that fork.
Else, do nothing.
Philosopher has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher.
Note
This is an example of Livelock amongst threads.
Referenced by checkStep().
The documentation for this class was generated from the following files:
/home/rvree/TSGL_2.1/TSGL/src/examples/DiningPhilosophers/Table.h
/home/rvree/TSGL_2.1/TSGL/src/examples/DiningPhilosophers/Table.cpp