tsgl::Line Class Reference
Draw a simple line.
#include <Line.h>
Public Member Functions
Line (float x, float y, float z, GLfloat length, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new Line.
Line (float x, float y, float z, GLfloat length, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new Line.
Line (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new Line.
Line (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new Line.
void setFirstEndpoint (float x, float y, float z)
Moves the line's first endpoint to the parameter coordinates.
void setSecondEndpoint (float x, float y, float z)
Moves the line's second endpoint to the parameter coordinates.
void setLength (GLfloat length)
Mutates the line's length to the new parameter value.
void changeLengthBy (GLfloat delta)
Mutates the line's length by the parameter value.
GLfloat getLength ()
Returns the length of the line.
GLfloat getFirstEndpointX ()
Returns the x-coordinate of the line's first endpoint.
GLfloat getFirstEndpointY ()
Returns the y-coordinate of the line's first endpoint.
GLfloat getFirstEndpointZ ()
Returns the z-coordinate of the line's first endpoint.
GLfloat getSecondEndpointX ()
Returns the x-coordinate of the line's second endpoint.
GLfloat getSecondEndpointY ()
Returns the y-coordinate of the line's second endpoint.
GLfloat getSecondEndpointZ ()
Returns the z-coordinate of the line's second endpoint.
Additional Inherited Members
Detailed Description
Draw a simple line.
Line is a class for holding vertex data for a simple line.
Constructor & Destructor Documentation
Line() [1/4]
tsgl::Line::Line (float x, float y, float z, GLfloat length, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new Line.
This is the constructor for the Line class.
Parameters
x The x coordinate of the center of the line.
y The y coordinate of the center of the line.
z The z coordinate of the center of the line.
length The length of the line.
yaw The yaw of the line.
pitch The pitch of the line.
roll The roll of the line.
color The reference variable to the color of the Line.
Returns
A new Line with the specified length and color.
Note
At 0,0,0 yaw,pitch,roll, the line will be drawn directly parallel to the x-axis.
Line() [2/4]
tsgl::Line::Line (float x, float y, float z, GLfloat length, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new Line.
This is the constructor for the Line class.
Parameters
x The x coordinate of the center of the line.
y The y coordinate of the center of the line.
z The z coordinate of the center of the line.
length The length of the line.
yaw The yaw of the line.
pitch The pitch of the line.
roll The roll of the line.
color The reference variable to the colors of the Line.
Returns
A new Line with the specified length and color.
Note
At 0,0,0 yaw,pitch,roll, the line will be drawn directly parallel to the x-axis.
Line() [3/4]
tsgl::Line::Line (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new Line.
This is the constructor for the Line class.
Parameters
x1 The x coordinate of the first endpoint of the line.
y1 The y coordinate of the first endpoint of the line.
z1 The z coordinate of the first endpoint of the line.
x2 The x coordinate of the second endpoint of the line.
y2 The y coordinate of the second endpoint of the line.
z2 The z coordinate of the second endpoint of the line.
yaw The yaw of the line.
pitch The pitch of the line.
roll The roll of the line.
color The reference variable to the color of the Line.
Returns
A new Line with the specified length and color.
Line() [4/4]
tsgl::Line::Line (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new Line.
This is the constructor for the Line class.
Parameters
x1 The x coordinate of the first endpoint of the line.
y1 The y coordinate of the first endpoint of the line.
z1 The z coordinate of the first endpoint of the line.
x2 The x coordinate of the second endpoint of the line.
y2 The y coordinate of the second endpoint of the line.
z2 The z coordinate of the second endpoint of the line.
yaw The yaw of the line.
pitch The pitch of the line.
roll The roll of the line.
color The reference variable to the colors of the Line.
Returns
A new Line with the specified length and color.
Member Function Documentation
changeLengthBy()
void tsgl::Line::changeLengthBy (GLfloat delta)
Mutates the line's length by the parameter value.
Parameters
delta The difference between the new and old line lengths.
getFirstEndpointX()
GLfloat tsgl::Line::getFirstEndpointX ()
Returns the x-coordinate of the line's first endpoint.
Returns the value of the endpointX1 instance variable.
Returns
x-coordinate of the Line's first endpoint.
Referenced by getLength().
getFirstEndpointY()
GLfloat tsgl::Line::getFirstEndpointY ()
Returns the y-coordinate of the line's first endpoint.
Returns the value of the endpointY1 instance variable.
Returns
y-coordinate of the Line's first endpoint.
Referenced by getLength().
getFirstEndpointZ()
GLfloat tsgl::Line::getFirstEndpointZ ()
Returns the z-coordinate of the line's first endpoint.
Returns the value of the endpointZ1 instance variable.
Returns
z-coordinate of the Line's first endpoint.
Referenced by getLength().
getLength()
GLfloat tsgl::Line::getLength () [inline]
Returns the length of the line.
Returns the value of the myLength instance variable.
Returns
Length of the Line.
getSecondEndpointX()
GLfloat tsgl::Line::getSecondEndpointX ()
Returns the x-coordinate of the line's second endpoint.
Returns the value of the endpointX2 instance variable.
Returns
x-coordinate of the Line's second endpoint.
Referenced by getLength().
getSecondEndpointY()
GLfloat tsgl::Line::getSecondEndpointY ()
Returns the y-coordinate of the line's second endpoint.
Returns the value of the endpointY2 instance variable.
Returns
y-coordinate of the Line's second endpoint.
Referenced by getLength().
getSecondEndpointZ()
GLfloat tsgl::Line::getSecondEndpointZ ()
Returns the z-coordinate of the line's second endpoint.
Returns the value of the endpointZ2 instance variable.
Returns
z-coordinate of the Line's second endpoint.
Referenced by getLength().
setFirstEndpoint()
void tsgl::Line::setFirstEndpoint (float x, float y, float z)
Moves the line's first endpoint to the parameter coordinates.
Parameters
x The Line's first endpoint's new x-coordinate.
y The Line's first endpoint's new y-coordinate.
z The Line's first endpoint's new z-coordinate.
Warning
Upon altering an endpoint, center coordinates will be altered accordingly, yaw, pitch, and roll will be reset to 0, and rotation point coordinates will be adjusted if they previously matched the center of the line.
setLength()
void tsgl::Line::setLength (GLfloat length)
Mutates the line's length to the new parameter value.
Parameters
length The Line's new length.
setSecondEndpoint()
void tsgl::Line::setSecondEndpoint (float x, float y, float z)
Moves the line's second endpoint to the parameter coordinates.
Parameters
x The Line's second endpoint's new x-coordinate.
y The Line's second endpoint's new y-coordinate.
z The Line's second endpoint's new z-coordinate.
Warning
Upon altering an endpoint, center coordinates will be altered accordingly, yaw, pitch, and roll will be reset to 0, and rotation point coordinates will be adjusted if they previously matched the center of the line.
The documentation for this class was generated from the following files:
Line.h
Line.cpp