tsgl::CartesianBackground Class Reference
Draw a procedurally drawn CartesianBackground for the Canvas.
#include <CartesianBackground.h>
Public Member Functions
CartesianBackground (GLint width, GLint height, Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax, const ColorFloat &c=WHITE)
Explicitly constructs a new CartesianBackground.
virtual void draw ()
Draw the CartesianBackground.
virtual void drawAxes (Decimal originX, Decimal originY, Decimal spacingX, Decimal spacingY)
Draws axes on the Cartesian Background.
void drawFunction (const Function &function, ColorFloat color=BLACK)
Plots a function on the screen.
void drawFunction (functionPointer &function, ColorFloat color=BLACK)
Plots a function on the screen.
void drawPartialFunction (functionPointer &function, Decimal min, Decimal max, ColorFloat color=BLACK)
Plots part of a function on the screen.
virtual void drawPixel (float x, float y, ColorInt c)
Draws a single pixel, specified in x,y format, at the given Cartesian coordinates.
Decimal getCartHeight ()
Accessor for the CartesianBackground's Cartesian height.
Decimal getCartWidth ()
Accessor for the CartesianBackground's Cartesian width.
Decimal getMaxX ()
Accessor for the CartesianBackground's right bound.
Decimal getMaxY ()
Accessor for the CartesianBackground's top bound.
Decimal getMinX ()
Accessor for the CartesianBackground's left bound.
Decimal getMinY ()
Accessor for the CartesianBackground's bottom bound.
virtual ColorInt getPixel (float x, float y)
Gets the color of the pixel drawn on the current Background at the given x and y Cartesian coordinates.
void zoom (Decimal x, Decimal y, Decimal scale)
Zoom the CartesianBackground with a given center.
void zoom (Decimal x1, Decimal y1, Decimal x2, Decimal y2)
Zoom the CartesianBackground with the given bounding (Cartesian) coordinates.
Protected Member Functions
virtual void selectShaders (unsigned int sType) override
Activates the corresponding Shader for a given Drawable.
Protected Attributes
Decimal myCartWidth
Decimal myCartHeight
Decimal myXMin
Decimal myXMax
Decimal myYMin
Decimal myYMax
Decimal pixelWidth
Decimal pixelHeight
Detailed Description
Draw a procedurally drawn CartesianBackground for the Canvas.
CartesianBackground is a class for holding a framebuffer of color data.
Constructor & Destructor Documentation
CartesianBackground()
tsgl::CartesianBackground::CartesianBackground (GLint width, GLint height, Decimal xMin, Decimal yMin, Decimal xMax, Decimal yMax, const ColorFloat & clearColor = WHITE)
Explicitly constructs a new CartesianBackground.
Creates a Background whose world dimensions don't have to match its pixel dimensions.
Parameters
width CartesianBackground's width in pixels.
height CartesianBackground's height in pixels.
xMin x value of the left side of the CartesianBackground in world coordinates.
xMax x value of the right side of the CartesianBackground in world coordinates.
yMin y value of the bottom side of the CartesianBackground in world coordinates.
yMax y value of the top side of the CartesianBackground in world coordinates.
c A ColorFloat for the CartesianBackground's original color.
Warning
An invariant is held where if xMax or xMin isn't greater than its respective min then an error message is given.
Returns
A new CartesianBackground to which Drawables and Pixels can be drawn procedurally.
Member Function Documentation
draw()
void tsgl::CartesianBackground::draw () [virtual]
Draw the CartesianBackground.
This function actually draws the CartesianBackground to the Canvas.
Note
On each draw cycle, first any Drawables that have been newly added to the CartesianBackground will be rendered, and then any new calls to drawPixel will be processed.
Reimplemented from tsgl::Background.
drawAxes()
void tsgl::CartesianBackground::drawAxes (Decimal originX, Decimal originY, Decimal spacingX, Decimal spacingY) [virtual]
Draws axes on the Cartesian Background.
This function draws axes (with tick marks) on the CartesianBackground, centered at the given (Cartesian) coordinates
Parameters
originX The horizontal location of the y-axis line.
originY The vertical location of the x-axis line.
spacingX The distance between marks on the x-axis.
spacingY The distance between marks on the y-axis.
Referenced by tsgl::IntegralViewer::~IntegralViewer().
drawFunction() [1/2]
void tsgl::CartesianBackground::drawFunction (const Function & function, ColorFloat color = BLACK)
Plots a function on the screen.
This function receives a TSGL Function instance as a parameter and plots the function on the CartesianCanvas.
Parameters
function Reference to the Function to plot.
color The color of the vertices of the plotted function (set to BLACK by default).
drawFunction() [2/2]
void tsgl::CartesianBackground::drawFunction (functionPointer & function, ColorFloat color = BLACK)
Plots a function on the screen.
This function receives a pointer to a function method as a parameter and plots the function on the CartesianCanvas.
Parameters
function Pointer to the function-drawing method to plot.
color The color of the vertices of the plotted function (set to BLACK by default).
Note
function must receive exactly one Decimal x parameter, and return a Decimal y parameter.
drawPartialFunction()
void tsgl::CartesianBackground::drawPartialFunction (functionPointer & function, Decimal min, Decimal max, ColorFloat color = BLACK)
Plots part of a function on the screen.
This function receives a pointer to a function method as a parameter and plots the function on the CartesianCanvas between the specified minimum and maximum coordinates.
Parameters
function Pointer to the function-drawing method to plot.
min Minimum x value to evaluate and plot
max Maximum x value to evaluate and plot
color The color of the vertices of the plotted function (set to BLACK by default).
Note
function must receive exactly one Decimal x parameter, and return a Decimal y parameter.
Referenced by drawFunction(), and tsgl::IntegralViewer::~IntegralViewer().
drawPixel()
void tsgl::CartesianBackground::drawPixel (float x, float y, ColorInt c) [virtual]
Draws a single pixel, specified in x,y format, at the given Cartesian coordinates.
This function alters the value at the specified x, y offset within the Background's buffer variable.
Note
x and y must be given in world (Cartesian coordinates).
Parameters
x The Cartesian x-position of the pixel.
y The Cartesian y-position of the pixel.
color The color of the point.
Reimplemented from tsgl::Background.
Referenced by Julia::draw(), Nova::draw(), GradientMandelbrot::draw(), and Mandelbrot::draw().
getCartHeight()
Decimal tsgl::CartesianBackground::getCartHeight () [inline]
Accessor for the CartesianBackground's Cartesian height.
Returns
The Cartesian height of the CartesianBackground.
getCartWidth()
Decimal tsgl::CartesianBackground::getCartWidth () [inline]
Accessor for the CartesianBackground's Cartesian width.
Returns
The Cartesian width of the CartesianBackground.
getMaxX()
Decimal tsgl::CartesianBackground::getMaxX () [inline]
Accessor for the CartesianBackground's right bound.
Returns
The real number corresponding the right of the CartesianBackground.
Referenced by Mandelbrot::draw().
getMaxY()
Decimal tsgl::CartesianBackground::getMaxY () [inline]
Accessor for the CartesianBackground's top bound.
Returns
The real number corresponding the top of the CartesianBackground.
getMinX()
Decimal tsgl::CartesianBackground::getMinX () [inline]
Accessor for the CartesianBackground's left bound.
Returns
The real number corresponding the left of the CartesianBackground.
Referenced by Mandelbrot::draw().
getMinY()
Decimal tsgl::CartesianBackground::getMinY () [inline]
Accessor for the CartesianBackground's bottom bound.
Returns
The real number corresponding the bottom of the CartesianBackground.
getPixel()
ColorInt tsgl::CartesianBackground::getPixel (float x, float y) [virtual]
Gets the color of the pixel drawn on the current Background at the given x and y Cartesian coordinates.
Note
x and y must be given in world (Cartesian coordinates).
Parameters
x The Cartesian x-position of the pixel to grab.
y The Cartesian y-position of the pixel to grab.
Returns
A ColorInt containing the color of the pixel at (x,y).
Reimplemented from tsgl::Background.
Referenced by getMinY().
selectShaders()
void tsgl::CartesianBackground::selectShaders (unsigned int sType) [override], [protected], [virtual]
Activates the corresponding Shader for a given Drawable.
Parameters
sType Unsigned int with a corresponding value for each type of Shader.
Reimplemented from tsgl::Background.
Referenced by draw().
zoom() [1/2]
void tsgl::CartesianBackground::zoom (Decimal x, Decimal y, Decimal scale)
Zoom the CartesianBackground with a given center.
This function will re-center the CartesianBackground at the given coordinates, then zoom with respect to the given scale.
Parameters
x The coordinate to re-center the screen on.
y The coordinate to re-center the screen on.
scale The zoom scale compared to the original. Less than 1 zooms in, greater than 1 zooms out.
Note
This function will automatically maintain the current aspect ratio.
Referenced by getMinY(), zoom(), and tsgl::CartesianCanvas::zoom().
zoom() [2/2]
void tsgl::CartesianBackground::zoom (Decimal x1, Decimal y1, Decimal x2, Decimal y2)
Zoom the CartesianBackground with the given bounding (Cartesian) coordinates.
This function will zoom the CartesianBackground with respect to the given bounding coordinates.
Parameters
x1 The left Cartesian bound.
y1 The bottom Cartesian bound.
x2 The right Cartesian bound.
y2 The top Cartesian bound.
Note
Setting the right bound lower than the left bound or the top lower than the bottom will just swap the variables.
Warning
This function will NOT automatically maintain the previous aspect ratio.
Change the aspect ratio on-the-fly only with caution.
The documentation for this class was generated from the following files:
CartesianBackground.h
CartesianBackground.cpp