tsgl::Image Class Reference
Draw an image to the Canvas.
#include <Image.h>
Public Member Functions
Image (float x, float y, float z, std::string filename, GLfloat width, GLfloat height, float yaw, float pitch, float roll, float alpha=1.0f)
Explicitly constructs a new Image.
virtual void draw (Shader *shader)
Draw the Image.
GLfloat getHeight ()
Accessor for the image's height.
GLfloat getWidth ()
Accessor for the image's width.
void setWidth (GLfloat width)
Mutates the distance from the left side of the Image base to its right side.
void setHeight (GLfloat height)
Mutates the distance from the top side of the Image base to its bottom side.
void changeWidthBy (GLfloat delta)
Mutates the distance from the left side of the Image base to its right side by the parameter amount.
void changeHeightBy (GLfloat delta)
Mutates the distance from the top side of the Image base to its bottom side by the parameter amount.
void changeFile (std::string filename)
Alters the file the Image draws.
void setAlpha (float newAlpha)
Alters the Image's transparency.
GLint getPixelHeight ()
GLint getPixelWidth ()
Static Public Member Functions
static void getFileResolution (std::string filename, int &width, int &height)
Gets the dimensions of an image.
Additional Inherited Members
Detailed Description
Draw an image to the Canvas.
Image is a class which provides a simple interface for loading and drawing images. The Image class currently supports files in the .png, .bmp, and .jpg formats.
Note
For the time being, there is no way to measure the size of an image once it's loaded. Therefore, the width and height must be specified manually, and stretching may occur if the input dimensions don't match the images actual dimensions.
Warning
Aside from an error message output to stderr, Image gives no indication if an image failed to load.
Constructor & Destructor Documentation
Image()
tsgl::Image::Image (float x, float y, float z, std::string filename, GLfloat width, GLfloat height, float yaw, float pitch, float roll, float alpha = 1.0f)
Explicitly constructs a new Image.
This is the explicit constructor for the Image class.
Parameters
x The x coordinate of the center of the Image.
y The y coordinate of the center of the Image.
z The z coordinate of the center of the Image.
filename The filename of the image to load, a std::string
width The width of the Image.
height The height of the Image.
yaw The yaw orientation of the Image.
pitch The pitch orientation of the Image.
roll The roll orientation of the Image.
alpha The alpha of the Image.
Returns
A new Image is drawn with the specified coordinates, dimensions, and transparency.
Note
IMPORTANT: In CartesianCanvas, y specifies the bottom, not the top, of the image.
Member Function Documentation
changeFile()
void tsgl::Image::changeFile (std::string filename)
Alters the file the Image draws.
Alters the values of the myFile, myWidth, myHeight, and mutates vertices.
Parameters
filename New string value for myFile.
width New width of the Image.
height New height of the Image.
Referenced by getWidth().
changeHeightBy()
void tsgl::Image::changeHeightBy (GLfloat delta)
Mutates the distance from the top side of the Image base to its bottom side by the parameter amount.
Parameters
delta The amount by which to change the height of the Image.
Referenced by getWidth().
changeWidthBy()
void tsgl::Image::changeWidthBy (GLfloat delta)
Mutates the distance from the left side of the Image base to its right side by the parameter amount.
Parameters
delta The amount by which to change the width of the Image.
Referenced by getWidth().
draw()
void tsgl::Image::draw (Shader * shader) [virtual]
Draw the Image.
This function actually draws the Image to the Canvas.
Implements tsgl::Drawable.
getFileResolution()
void tsgl::Image::getFileResolution (std::string filename, int & width, int & height) [static]
Gets the dimensions of an image.
Loads the header of a .png, .jpeg, or .bmp image to read their dimensions.
Parameters
filename The file name of the picture.
width A reference variable for holding the width of the picture.
height A reference variable for holding the height of the picture.
Referenced by getWidth().
getHeight()
GLfloat tsgl::Image::getHeight () [inline]
Accessor for the image's height.
Returns
The height of the Image.
getWidth()
GLfloat tsgl::Image::getWidth () [inline]
Accessor for the image's width.
Returns
The width of the Image.
setAlpha()
void tsgl::Image::setAlpha (float alpha)
Alters the Image's transparency.
Parameters
delta The Image's new alpha value.
Note
If parameter not 0.0 <= alpha <= 1.0 then this method will have no effect.
Referenced by getWidth().
setHeight()
void tsgl::Image::setHeight (GLfloat height)
Mutates the distance from the top side of the Image base to its bottom side.
Parameters
height The Image's new height.
Referenced by getWidth().
setWidth()
void tsgl::Image::setWidth (GLfloat width)
Mutates the distance from the left side of the Image base to its right side.
Parameters
width The Image's new width.
Referenced by getWidth().
The documentation for this class was generated from the following files:
Image.h
Image.cpp