tsgl::Circle Class Reference
Draw a circle.
#include <Circle.h>
Public Member Functions
Circle (float x, float y, float z, GLfloat radius, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new monocolored filled Circle.
Circle (float x, float y, float z, GLfloat radius, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new multicolored filled Circle.
void setRadius (GLfloat radius)
Mutates the radius of the Circle.
void changeRadiusBy (GLfloat delta)
Mutates the radius of the Circle by the parameter amount.
GLfloat getRadius ()
Accessor for the radius of the Circle.
void setColor (ColorFloat c)
Sets the Shape to a new color.
void setColor (ColorFloat c[])
Sets the Circle to a new array of colors.
virtual void getColors (std::vector< ColorFloat > &colorVec)
Accessor for Circle's colors.
Protected Attributes
GLfloat myRadius
GLfloat verticesPerColor
Additional Inherited Members
Detailed Description
Draw a circle.
Circle is a class for holding Shape data for a circle.
Constructor & Destructor Documentation
Circle() [1/2]
tsgl::Circle::Circle (float x, float y, float z, GLfloat radius, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new monocolored filled Circle.
This function draws a circle with the given center, radius, 3D rotation, color.
Parameters
x The x coordinate of the circle's center.
y The y coordinate of the circle's center.
z The z coordinate of the circle's center.
radius The radius of the circle in pixels.
yaw The circle's yaw in 3D space.
pitch The circle's pitch in 3D space.
roll The circle's roll in 3D space.
color The color of the circle's fill
Circle() [2/2]
tsgl::Circle::Circle (float x, float y, float z, GLfloat radius, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new multicolored filled Circle.
This function draws a circle with the given center, radius, roation, and fill color.
Parameters
x The x coordinate of the circle's center.
y The y coordinate of the circle's center.
z The z coordinate of the circle's center.
radius The radius of the circle in pixels.
yaw The circle's yaw in 3D space.
pitch The circle's pitch in 3D space.
roll The circle's roll in 3D space.
color An array of colors for the Circle's fill
Member Function Documentation
changeRadiusBy()
void tsgl::Circle::changeRadiusBy (GLfloat delta)
Mutates the radius of the Circle by the parameter amount.
Parameters
delta The amount by which to change the radius of the Circle.
getColors()
void tsgl::Circle::getColors (std::vector< ColorFloat > & colorVec) [virtual]
Accessor for Circle's colors.
Populates the reference parameter vector with a ColorFloat for each section of Circle.
Parameters
colorVec A vector of ColorFloats to which the ColorFloats associated with Circle will be pushed.
Note
Overrides Shape::getColors().
Reimplemented from tsgl::Shape.
Referenced by setColor().
getRadius()
GLfloat tsgl::Circle::getRadius () [inline]
Accessor for the radius of the Circle.
Returns the value of the myRadius private variable, a GLfloat.
setColor() [1/2]
void tsgl::Circle::setColor (ColorFloat c) [inline], [virtual]
Sets the Shape to a new color.
Parameters
c The new ColorFloat.
Reimplemented from tsgl::Shape.
Referenced by Reader::Reader(), Philosopher::refreshColor(), and Writer::Writer().
setColor() [2/2]
void tsgl::Circle::setColor (ColorFloat c[]) [virtual]
Sets the Circle to a new array of colors.
Parameters
c An array of the new ColorFloats.
Reimplemented from tsgl::Shape.
setRadius()
void tsgl::Circle::setRadius (GLfloat radius)
Mutates the radius of the Circle.
Parameters
radius The Circle's new radius.
The documentation for this class was generated from the following files:
Circle.h
Circle.cpp