tsgl::Shape Class Reference
A class for drawing shapes onto a Canvas or CartesianCanvas.
#include <Shape.h>
Public Member Functions
Shape (float x, float y, float z, float yaw, float pitch, float roll)
Constructs a new Shape.
virtual void draw (Shader *shader)
Draw the Shape.
virtual void setColor (ColorFloat c)
Sets the Shape to a new color.
virtual void setColor (ColorFloat c[])
Sets the Shape to a new array of colors.
virtual void setOutlineColor (ColorFloat c)
Sets the Shape's outline to a new color.
virtual ColorFloat getColor ()
Accessor for Shape's color.
virtual void getColors (std::vector< ColorFloat > &colorVec)
Accessor for Shape's colors.
virtual bool isProcessed ()
Accessor that returns if Drawable is processed and ready to be drawn.
virtual void setIsFilled (bool status)
Set whether or not the Shape will be filled.
virtual void setIsOutlined (bool status)
Set whether or not the Shape will be outlined.
Protected Member Functions
virtual void addVertex (GLfloat x, GLfloat y, GLfloat z, const ColorFloat &color=WHITE)
Adds another vertex to a Shape.
virtual void addOutlineVertex (GLfloat x, GLfloat y, GLfloat z, const ColorFloat &color=WHITE)
Adds another outline vertex to a Shape.
Protected Attributes
int numberOfVertices
int currentVertex = 0
GLenum geometryType
bool isFilled = true
int numberOfOutlineVertices
int currentOutlineVertex = 0
GLenum outlineGeometryType
GLfloat * outlineVertices
bool isOutlined = true
bool outlineInit = false
Detailed Description
A class for drawing shapes onto a Canvas or CartesianCanvas.
Warning
Though extending this class must be allowed due to the way the code is set up, attempting to do so could potentially mess up the internal GL calls the library uses. Proceed with great caution.
Shape provides a base class for drawing shapes to a Canvas or CartesianCanvas.
Note
Shape is abstract, and must be extended by the user.
vertices should be an array of floating point values in TSGL's vertex format. One vertex consists of 6 floating point values, signifying x,y,red,green,blue,and alpha components respectively. E.g., to draw a triangle, you would need 3 vertices = 18 floats -> vertices should be an array of length 18.
numberofvertices should be the actual integer number of vertices to be drawn (e.g., 3 for a triangle).
drawingmode should be one of GL's primitive drawing modes. See https://www.opengl.org/sdk/docs/man2/xhtml/glBegin.xml for further information.
Theoretically, you could potentially extend the Shape class so that you can create another Shape class that suits your needs.
However, this is not recommended for normal use of the TSGL library.
Constructor & Destructor Documentation
Shape()
tsgl::Shape::Shape (float x, float y, float z, float yaw, float pitch, float roll)
Constructs a new Shape.
Usually vertices is filled with floating point values that represent the vertices of the shape to be drawn.
You may define other items in the constructor that pertain to the attributes of the subclass that is extending Shape.
At a minimum, you MUST fill an array of floating point values that pertain to the vertices of the shape.
Warning
You must inherit the parent's constructor if you are extending Shape.
Note
Refer to the Shape class description for more details.
Member Function Documentation
addOutlineVertex()
void tsgl::Shape::addOutlineVertex (GLfloat x, GLfloat y, GLfloat z, const ColorFloat & color = WHITE) [protected], [virtual]
Adds another outline vertex to a Shape.
This function initializes the next vertex in the Shape and adds it to a Shape buffer.
Parameters
x The x position of the vertex.
y The y position of the vertex.
z The z position of the vertex.
color The reference variable of the color of the vertex.
Note
This function does nothing if the vertex buffer is already full.
A message is given indicating that the vertex buffer is full.
Referenced by tsgl::Arrow::Arrow(), tsgl::Circle::Circle(), tsgl::ConcavePolygon::ConcavePolygon(), tsgl::ConvexPolygon::ConvexPolygon(), tsgl::Cube::Cube(), tsgl::Cuboid::Cuboid(), tsgl::Ellipse::Ellipse(), tsgl::Ellipsoid::Ellipsoid(), tsgl::Prism::Prism(), tsgl::Pyramid::Pyramid(), tsgl::Rectangle::Rectangle(), tsgl::RegularPolygon::RegularPolygon(), tsgl::Sphere::Sphere(), tsgl::Square::Square(), tsgl::Star::Star(), tsgl::Triangle::Triangle(), and tsgl::TriangleStrip::TriangleStrip().
addVertex()
void tsgl::Shape::addVertex (GLfloat x, GLfloat y, GLfloat z, const ColorFloat & color = WHITE) [protected], [virtual]
Adds another vertex to a Shape.
This function initializes the next vertex in the Shape and adds it to a Shape buffer.
Parameters
x The x position of the vertex.
y The y position of the vertex.
z The z position of the vertex.
color The reference variable of the color of the vertex.
Note
This function does nothing if the vertex buffer is already full.
A message is given indicating that the vertex buffer is full.
Referenced by tsgl::Arrow::Arrow(), tsgl::Circle::Circle(), tsgl::ConcavePolygon::ConcavePolygon(), tsgl::ConvexPolygon::ConvexPolygon(), tsgl::Cube::Cube(), tsgl::Cuboid::Cuboid(), tsgl::Ellipse::Ellipse(), tsgl::Ellipsoid::Ellipsoid(), tsgl::Prism::Prism(), tsgl::Pyramid::Pyramid(), tsgl::Rectangle::Rectangle(), tsgl::RegularPolygon::RegularPolygon(), tsgl::Sphere::Sphere(), tsgl::Square::Square(), tsgl::Star::Star(), tsgl::Triangle::Triangle(), and tsgl::TriangleStrip::TriangleStrip().
draw()
void tsgl::Shape::draw (Shader * shader) [virtual]
Draw the Shape.
This function actually draws the Shape to the Canvas.
Note
This function does nothing if the vertex buffer is not yet full.
A message indicating that the Shape cannot be drawn yet will be given if the above condition is met (vertex buffer = not full).
Implements tsgl::Drawable.
Reimplemented in tsgl::ConcavePolygon.
Referenced by tsgl::ProgressBar::~ProgressBar().
getColor()
ColorFloat tsgl::Shape::getColor () [virtual]
Accessor for Shape's color.
Returns the color of Shape's first vertex.
Note
For multicolored Shapes, use getColors() to access a vector of all relevant colors.
Referenced by Consumer::act(), Reader::Reader(), Producer::wait(), and Writer::Writer().
getColors()
void tsgl::Shape::getColors (std::vector< ColorFloat > & colorVec) [virtual]
Accessor for Shape's colors.
Populates the reference parameter vector with a ColorFloat for each vertex of Shape.
Parameters
colorVec A vector of ColorFloats to which the ColorFloats associated with Shape will be pushed.
Reimplemented in tsgl::Arrow, tsgl::Cuboid, tsgl::Prism, tsgl::Pyramid, tsgl::Ellipse, tsgl::Ellipsoid, tsgl::Cube, tsgl::Circle, and tsgl::Sphere.
isProcessed()
virtual bool tsgl::Shape::isProcessed () [inline], [virtual]
Accessor that returns if Drawable is processed and ready to be drawn.
This function returns true only if all vertices have been inserted into an array.
Reimplemented from tsgl::Drawable.
setColor() [1/2]
void tsgl::Shape::setColor (ColorFloat c) [virtual]
Sets the Shape to a new color.
Parameters
c The new ColorFloat.
Reimplemented in tsgl::Arrow, tsgl::Cuboid, tsgl::Prism, tsgl::Pyramid, tsgl::Ellipse, tsgl::Ellipsoid, tsgl::Cube, tsgl::Circle, and tsgl::Sphere.
Referenced by Consumer::act(), Consumer::lock(), Producer::lock(), Paddle::Paddle(), tsgl::Circle::setColor(), tsgl::Cube::setColor(), tsgl::Ellipse::setColor(), tsgl::Prism::setColor(), tsgl::Cuboid::setColor(), tsgl::Arrow::setColor(), Producer::wait(), and Writer::Writer().
setColor() [2/2]
void tsgl::Shape::setColor (ColorFloat c[]) [virtual]
Sets the Shape to a new array of colors.
Parameters
c The new array of ColorFloats.
Reimplemented in tsgl::Arrow, tsgl::Cuboid, tsgl::Prism, tsgl::Pyramid, tsgl::Ellipse, tsgl::Ellipsoid, tsgl::Cube, tsgl::Circle, and tsgl::Sphere.
setIsFilled()
virtual void tsgl::Shape::setIsFilled (bool status) [inline], [virtual]
Set whether or not the Shape will be filled.
Sets the isFilled instance variable to the value of the parameter.
Parameters
status Boolean value to which isFilled will be set equivalent.
Warning
Disabling fill on some 3D Shapes, like Cone and Cylinder, can be awkward visually.
setIsOutlined()
virtual void tsgl::Shape::setIsOutlined (bool status) [inline], [virtual]
Set whether or not the Shape will be outlined.
Sets the isOutlined instance variable to the value of the parameter.
Parameters
status Boolean value to which isOutlined will be set equivalent.
Warning
Disabling outlines on monocolored 3D Shapes can be awkward visually.
Referenced by tsgl::Background::drawArrow(), tsgl::Background::drawCircle(), tsgl::Background::drawConcavePolygon(), tsgl::Background::drawConvexPolygon(), tsgl::Background::drawEllipse(), tsgl::Background::drawRectangle(), tsgl::Background::drawRegularPolygon(), tsgl::Background::drawSquare(), tsgl::Background::drawStar(), Table3D::drawStep(), tsgl::Background::drawTriangle(), tsgl::Background::drawTriangleStrip(), and tsgl::ProgressBar::ProgressBar().
setOutlineColor()
void tsgl::Shape::setOutlineColor (ColorFloat c) [virtual]
Sets the Shape's outline to a new color.
Parameters
c The new ColorFloat.
The documentation for this class was generated from the following files:
Shape.h
Shape.cpp