Philosopher3D Class Reference
Object representing a 3D philosopher in the Dining Philosophers' problem.
#include <Philosopher3D.h>
Public Member Functions
Philosopher3D ()
Explicitly constructs a new Philosopher3D.
void draw (Canvas &can, float x, float y)
void refreshColor ()
void addMeal (float x, float y, float z)
Pyramid * getLastMeal ()
bool acquire (Fork3D &f)
bool release (Fork3D &f)
void think ()
void eat ()
Resets the Philosopher3D to thinking after he eats.
void setState (PhilState s)
Mutator for myState.
void setAction (PhilAction a)
Mutator for myAction.
void setId (int i, int nphil)
Mutator for id.
int getMeals ()
PhilState state ()
PhilAction action ()
int getId ()
bool hasCylinder ()
Detailed Description
Object representing a 3D philosopher in the Dining Philosophers' problem.
The Philosopher3D class contains variables and methods necessary for representing a philosopher at a table. Each Philosopher3D may acquire or release the fork to his left or to his right (or both), with his state changing accordingly.
Constructor & Destructor Documentation
Philosopher3D()
Philosopher3D::Philosopher3D ()
Explicitly constructs a new Philosopher3D.
Explicit constructor for a new Philosopher3D object.
Member Function Documentation
acquire()
bool Philosopher3D::acquire (Fork3D & f)
Picks up a fork specified by its reference
Referenced by Table3D::actStep().
action()
PhilAction Philosopher3D::action () [inline]
Accessor for Philosopher3D's action.
addMeal()
void Philosopher3D::addMeal (float x, float y, float z)
Adds a meal representation to meals and the Canvas
Referenced by Table3D::drawStep().
draw()
void Philosopher3D::draw (Canvas & can, float x, float y)
Adds Philosopher3D to Canvas or refreshes its color.
Referenced by Table3D::drawStep().
getId()
int Philosopher3D::getId () [inline]
Accessor for Philosopher3D's id.
getMeals()
int Philosopher3D::getMeals () [inline]
Accessor for number of meals Philosopher3D has consumed.
Referenced by Table3D::drawStep().
hasCylinder()
bool Philosopher3D::hasCylinder () [inline]
Accessor for Philosopher3D's cylinder.
refreshColor()
void Philosopher3D::refreshColor ()
Updates the Philosopher3D's color based on its state
Referenced by Table3D::drawStep().
release()
bool Philosopher3D::release (Fork3D & f)
Releases a fork specified by its reference
Referenced by Table3D::actStep().
setAction()
void Philosopher3D::setAction (PhilAction a) [inline]
Mutator for myAction.
Parameters
s PhilAction to set myAction to.
Referenced by Table3D::forfeitWhenBlockedMethod(), Table3D::hierarchyMethod(), Table3D::nFrameReleaseMethod(), Table3D::oddEvenMethod(), think(), and Table3D::waitWhenBlockedMethod().
setId()
void Philosopher3D::setId (int i, int nphil) [inline]
Mutator for id.
Parameters
i Which philosopher id to mutate
nphil Total number of philosophers.
Referenced by Philosopher3D(), and Table3D::Table3D().
setState()
void Philosopher3D::setState (PhilState s) [inline]
Mutator for myState.
Parameters
s PhilState to set myState to.
Referenced by Table3D::forfeitWhenBlockedMethod(), and think().
state()
PhilState Philosopher3D::state () [inline]
Accessor for Philosopher3D's state.
Referenced by Table3D::drawStep().
think()
void Philosopher3D::think ()
Thinks and switches to hungry state if a random number is a multiple of 3.
Referenced by Table3D::hierarchyMethod(), Table3D::nFrameReleaseMethod(), Table3D::oddEvenMethod(), and Table3D::waitWhenBlockedMethod().
The documentation for this class was generated from the following files:
/home/rvree/TSGL_2.1/TSGL/src/examples/DiningPhilosophers3D/Philosopher3D.h
/home/rvree/TSGL_2.1/TSGL/src/examples/DiningPhilosophers3D/Philosopher3D.cpp