tsgl::Background Class Reference
Draw a Background for the Canvas with colored pixels.
#include <Background.h>
Public Member Functions
Background (GLint width, GLint height, const ColorFloat &c=WHITE)
Explicitly constructs a new Background.
virtual void init (Shader *shapeS, Shader *textS, Shader *textureS, Camera *camera, GLFWwindow *window)
Assigns Drawable shaders and initializes framebuffers within the parameter window's context.
virtual bool isInitialized ()
virtual void clear ()
virtual void draw ()
Draw the Background.
virtual void drawArrow (float x, float y, float z, float length, float width, float yaw, float pitch, float roll, ColorFloat color, bool doubleArrow=false, bool outlined=false)
Procedurally draws an Arrow to the Background.
virtual void drawArrow (float x, float y, float z, float length, float width, float yaw, float pitch, float roll, ColorFloat color[], bool doubleArrow=false, bool outlined=false)
Procedurally draws an Arrow to the Background.
virtual void drawCircle (float x, float y, float z, float radius, float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a Circle to the Background.
virtual void drawCircle (float x, float y, float z, float radius, float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a Circle to the Background.
virtual void drawConcavePolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a ConcavePolygon to the Background.
virtual void drawConcavePolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a ConcavePolygon to the Background.
virtual void drawConvexPolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a ConvexPolygon to the Background.
virtual void drawConvexPolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a ConvexPolygon to the Background.
virtual void drawEllipse (float x, float y, float z, float xRadius, float yRadius, float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws an Ellipse to the Background.
virtual void drawEllipse (float x, float y, float z, float xRadius, float yRadius, float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws an Ellipse to the Background.
virtual void drawImage (float x, float y, float z, std::string filename, float width, float height, float yaw, float pitch, float roll, float alpha=1.0f)
Procedurally draws an Image to the Background.
virtual void drawLine (float x1, float y1, float z1, float x2, float y2, float z2, float yaw, float pitch, float roll, ColorFloat color)
Procedurally draws a Line to the Background.
virtual void drawLine (float x1, float y1, float z1, float x2, float y2, float z2, float yaw, float pitch, float roll, ColorFloat color[])
Procedurally draws a Line to the Background.
virtual void drawLine (float x, float y, float z, float length, float yaw, float pitch, float roll, ColorFloat color)
Procedurally draws a Line to the Background.
virtual void drawLine (float x, float y, float z, float length, float yaw, float pitch, float roll, ColorFloat color[])
Procedurally draws a Line to the Background.
virtual void drawPixel (float x, float y, ColorInt c)
Draws a single pixel, specified in x,y format.
virtual void drawPolyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color)
Procedurally draws a Polyline to the Background.
virtual void drawPolyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color[])
Procedurally draws a Polyline to the Background.
virtual void drawRectangle (float x, float y, float z, float width, float height, float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a Rectangle to the Background.
virtual void drawRectangle (float x, float y, float z, float width, float height, float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a Rectangle to the Background.
virtual void drawRegularPolygon (float x, float y, float z, float radius, int sides, float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a RegularPolygon to the Background.
virtual void drawRegularPolygon (float x, float y, float z, float radius, int sides, float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a RegularPolygon to the Background.
virtual void drawSquare (float x, float y, float z, float sidelength, float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a Square to the Background.
virtual void drawSquare (float x, float y, float z, float sidelength, float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a Square to the Background.
virtual void drawStar (float x, float y, float z, float radius, int points, float yaw, float pitch, float roll, ColorFloat color, bool ninja=false, bool outlined=false)
Procedurally draws a Star to the Background.
virtual void drawStar (float x, float y, float z, float radius, int points, float yaw, float pitch, float roll, ColorFloat color[], bool ninja=false, bool outlined=false)
Procedurally draws a Star to the Background.
virtual void drawText (float x, float y, float z, std::string text, std::string fontFilename, float size, float yaw, float pitch, float roll, const ColorFloat &color)
Procedurally draws Text to the Background.
virtual void drawText (float x, float y, float z, std::wstring text, std::string fontFilename, float size, float yaw, float pitch, float roll, const ColorFloat &color)
Procedurally draws Text to the Background.
virtual void drawTriangle (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a Triangle to the Background.
virtual void drawTriangle (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a Triangle to the Background.
virtual void drawTriangleStrip (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float z[], float yaw, float pitch, float roll, ColorFloat color, bool outlined=false)
Procedurally draws a TriangleStrip to the Background.
virtual void drawTriangleStrip (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float z[], float yaw, float pitch, float roll, ColorFloat color[], bool outlined=false)
Procedurally draws a TriangleStrip to the Background.
virtual GLint getWidth ()
Accessor for the pixel width of the Background.
virtual GLint getHeight ()
Accessor for the pixel height of the Background.
virtual ColorInt getPixel (float x, float y)
Gets the color of the pixel drawn on the current Background at the given x and y.
virtual ColorFloat getClearColor ()
Accessor for color which is used to clear the Background when clear() is called.
virtual void setClearColor (ColorFloat c)
Mutator for the color used to clear the Background when clear() is called.
virtual ~Background ()
Destructor for the Background.
Protected Member Functions
virtual void selectShaders (unsigned int sType)
Activates the corresponding Shader for a given Drawable.
Protected Attributes
GLint myWidth
GLint myHeight
GLint framebufferWidth
GLint framebufferHeight
GLfloat myWorldZ
GLuint multisampledTexture
GLuint intermediateTexture
GLuint multisampledFBO
GLuint intermediateFBO
GLuint RBO
Array< Drawable * > * myDrawables
Camera * myCamera
Shader * textShader
Shader * shapeShader
Shader * textureShader
ColorFloat baseColor
bool toClear
std::mutex readPixelMutex
uint8_t * readPixelBuffer
std::mutex pixelBufferMutex
GLuint pixelTexture
uint8_t * pixelTextureBuffer
bool newPixelsDrawn
bool complete
std::mutex attribMutex
std::mutex drawableMutex
GLfloat * vertices
Detailed Description
Draw a Background for the Canvas with colored pixels.
Background is a class for holding colored pixel data.
Constructor & Destructor Documentation
Background()
tsgl::Background::Background (GLint width, GLint height, const ColorFloat & clearColor = WHITE)
Explicitly constructs a new Background.
Explicit constructor for a Background object.
Parameters
width Background's width in pixels.
height Background's height in pixels.
c A ColorFloat for the Background's original color.
Warning
An invariant is held where if width or height isn't positive then an error message is given.
Returns
A new Background to which Drawables and Pixels can be drawn procedurally.
Member Function Documentation
draw()
void tsgl::Background::draw () [virtual]
Draw the Background.
This function actually draws the Background to the Canvas.
Note
On each draw cycle, first any Drawables that have been newly added to the Background will be rendered, and then any new calls to drawPixel will be processed.
Reimplemented in tsgl::CartesianBackground.
drawArrow() [1/2]
void tsgl::Background::drawArrow (float x, float y, float z, float length, float width, float yaw, float pitch, float roll, ColorFloat color, bool doubleArrow = false, bool outlined = false) [virtual]
Procedurally draws an Arrow to the Background.
Initializes a new Arrow based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Arrow's center location.
y The y coordinate of the Arrow's center location.
z The z coordinate of the Arrow's center location.
length Length of the Arrow.
width Width of the Arrow.
yaw The Arrow's yaw rotation.
pitch The Arrow's pitch rotation.
roll The Arrow's roll rotation.
color ColorFloat for the Arrow's vertices.
outlined Boolean indicating if the Arrow should be outlined or not, defaulting to not.
drawArrow() [2/2]
void tsgl::Background::drawArrow (float x, float y, float z, float length, float width, float yaw, float pitch, float roll, ColorFloat color[], bool doubleArrow = false, bool outlined = false) [virtual]
Procedurally draws an Arrow to the Background.
Initializes a new Arrow based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Arrow's center location.
y The y coordinate of the Arrow's center location.
z The z coordinate of the Arrow's center location.
length Length of the Arrow.
width Width of the Arrow.
yaw The Arrow's yaw rotation.
pitch The Arrow's pitch rotation.
roll The Arrow's roll rotation.
color Array of ColorFloats for the Arrow's vertices.
outlined Boolean indicating if the Arrow should be outlined or not, defaulting to not.
drawCircle() [1/2]
void tsgl::Background::drawCircle (float x, float y, float z, float radius, float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a Circle to the Background.
Initializes a new Circle based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Circle's center location.
y The y coordinate of the Circle's center location.
z The z coordinate of the Circle's center location.
radius Radius of the Circle.
yaw The Circle's yaw rotation.
pitch The Circle's pitch rotation.
roll The Circle's roll rotation.
color Array of ColorFloats for the Circle's vertices.
outlined Boolean indicating if the Circle should be outlined or not, defaulting to not.
Referenced by Table::Table().
drawCircle() [2/2]
void tsgl::Background::drawCircle (float x, float y, float z, float radius, float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a Circle to the Background.
Initializes a new Circle based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Circle's center location.
y The y coordinate of the Circle's center location.
z The z coordinate of the Circle's center location.
radius Radius of the Circle.
yaw The Circle's yaw rotation.
pitch The Circle's pitch rotation.
roll The Circle's roll rotation.
color ColorFloat for the Circle's vertices.
outlined Boolean indicating if the Circle should be outlined or not, defaulting to not.
drawConcavePolygon() [1/2]
void tsgl::Background::drawConcavePolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a ConcavePolygon to the Background.
Initializes a new ConcavePolygon based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
centerX The x coordinate of the ConcavePolygon's center location.
centerY The y coordinate of the ConcavePolygon's center location.
centerZ The z coordinate of the ConcavePolygon's center location.
numVertices The number of vertices to be drawn for the ConcavePolygon.
x Float array containing the ConcavePolygon's x vertices.
y Float array containing the ConcavePolygon's y vertices.
yaw The ConcavePolygon's yaw rotation.
pitch The ConcavePolygon's pitch rotation.
roll The ConcavePolygon's roll rotation.
color ColorFloat for the ConcavePolygon's vertices.
outlined Boolean indicating if the ConcavePolygon should be outlined or not, defaulting to not.
Warning
Can sometimes incorrectly render; if this occurs, try shifting your last vertex to be your first vertex, or otherwise adjusting vertex order.
drawConcavePolygon() [2/2]
void tsgl::Background::drawConcavePolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a ConcavePolygon to the Background.
Initializes a new ConcavePolygon based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
centerX The x coordinate of the ConcavePolygon's center location.
centerY The y coordinate of the ConcavePolygon's center location.
centerZ The z coordinate of the ConcavePolygon's center location.
numVertices The number of vertices to be drawn for the ConcavePolygon.
x Float array containing the ConcavePolygon's x vertices.
y Float array containing the ConcavePolygon's y vertices.
yaw The ConcavePolygon's yaw rotation.
pitch The ConcavePolygon's pitch rotation.
roll The ConcavePolygon's roll rotation.
color Array of ColorFloats for the ConcavePolygon's vertices.
outlined Boolean indicating if the ConcavePolygon should be outlined or not, defaulting to not.
Warning
Can sometimes incorrectly render; if this occurs, try shifting your last vertex to be your first vertex, or otherwise adjusting vertex order.
drawConvexPolygon() [1/2]
void tsgl::Background::drawConvexPolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a ConvexPolygon to the Background.
Initializes a new ConvexPolygon based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
centerX The x coordinate of the ConvexPolygon's center location.
centerY The y coordinate of the ConvexPolygon's center location.
centerZ The z coordinate of the ConvexPolygon's center location.
numVertices The number of vertices to be drawn for the ConvexPolygon.
x Float array containing the ConvexPolygon's x vertices.
y Float array containing the ConvexPolygon's y vertices.
yaw The ConvexPolygon's yaw rotation.
pitch The ConvexPolygon's pitch rotation.
roll The ConvexPolygon's roll rotation.
color ColorFloat for the ConvexPolygon's vertices.
outlined Boolean indicating if the ConvexPolygon should be outlined or not, defaulting to not.
Referenced by tsgl::Spectrogram::draw(), and tsgl::IntegralViewer::trapezoidEvaluate().
drawConvexPolygon() [2/2]
void tsgl::Background::drawConvexPolygon (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a ConvexPolygon to the Background.
Initializes a new ConvexPolygon based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
centerX The x coordinate of the ConvexPolygon's center location.
centerY The y coordinate of the ConvexPolygon's center location.
centerZ The z coordinate of the ConvexPolygon's center location.
numVertices The number of vertices to be drawn for the ConvexPolygon.
x Float array containing the ConvexPolygon's x vertices.
y Float array containing the ConvexPolygon's y vertices.
yaw The ConvexPolygon's yaw rotation.
pitch The ConvexPolygon's pitch rotation.
roll The ConvexPolygon's roll rotation.
color Array of ColorFloats for the ConvexPolygon's vertices.
outlined Boolean indicating if the ConvexPolygon should be outlined or not, defaulting to not.
drawEllipse() [1/2]
void tsgl::Background::drawEllipse (float x, float y, float z, float xRadius, float yRadius, float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws an Ellipse to the Background.
Initializes a new Ellipse based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Ellipse's center location.
y The y coordinate of the Ellipse's center location.
z The z coordinate of the Ellipse's center location.
xRadius Horizontal radius of the Ellipse.
yRadius Vertical radius of the Ellipse.
yaw The Ellipse's yaw rotation.
pitch The Ellipse's pitch rotation.
roll The Ellipse's roll rotation.
color ColorFloat for the Ellipse's vertices.
outlined Boolean indicating if the Ellipse should be outlined or not, defaulting to not.
drawEllipse() [2/2]
void tsgl::Background::drawEllipse (float x, float y, float z, float xRadius, float yRadius, float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws an Ellipse to the Background.
Initializes a new Ellipse based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Ellipse's center location.
y The y coordinate of the Ellipse's center location.
z The z coordinate of the Ellipse's center location.
xRadius Horizontal radius of the Ellipse.
yRadius Vertical radius of the Ellipse.
yaw The Ellipse's yaw rotation.
pitch The Ellipse's pitch rotation.
roll The Ellipse's roll rotation.
color Array of ColorFloats for the Ellipse's vertices.
outlined Boolean indicating if the Ellipse should be outlined or not, defaulting to not.
drawImage()
void tsgl::Background::drawImage (float x, float y, float z, std::string filename, float width, float height, float yaw, float pitch, float roll, float alpha = 1.0f) [virtual]
Procedurally draws an Image to the Background.
Initializes a new Image based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Image's center location.
y The y coordinate of the Image's center location.
z The z coordinate of the Image's center location.
filename String containing the file location of the Image.
yaw The Image's yaw rotation.
pitch The Image's pitch rotation.
roll The Image's roll rotation.
alpha Alpha value for the Image's transparency.
Referenced by Table::Table().
drawLine() [1/4]
void tsgl::Background::drawLine (float x, float y, float z, float length, float yaw, float pitch, float roll, ColorFloat color) [virtual]
Procedurally draws a Line to the Background.
Initializes a new Line based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Line's center location.
y The y coordinate of the Line's center location.
z The z coordinate of the Line's center location.
length Length of the Line.
yaw The Line's yaw rotation.
pitch The Line's pitch rotation.
roll The Line's roll rotation.
color ColorFloat for the Line's vertices.
drawLine() [2/4]
void tsgl::Background::drawLine (float x, float y, float z, float length, float yaw, float pitch, float roll, ColorFloat color[]) [virtual]
Procedurally draws a Line to the Background.
Initializes a new Line based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Line's center location.
y The y coordinate of the Line's center location.
z The z coordinate of the Line's center location.
length Length of the Line.
yaw The Line's yaw rotation.
pitch The Line's pitch rotation.
roll The Line's roll rotation.
color Array of ColorFloats for the Line's vertices.
drawLine() [3/4]
void tsgl::Background::drawLine (float x1, float y1, float z1, float x2, float y2, float z2, float yaw, float pitch, float roll, ColorFloat color) [virtual]
Procedurally draws a Line to the Background.
Initializes a new Line based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x1 The x coordinate of the first endpoint of the line.
y1 The y coordinate of the first endpoint of the line.
z1 The z coordinate of the first endpoint of the line.
x2 The x coordinate of the second endpoint of the line.
y2 The y coordinate of the second endpoint of the line.
z2 The z coordinate of the second endpoint of the line.
yaw The yaw of the line.
pitch The pitch of the line.
roll The roll of the line.
color The reference variable to the color of the Line.
Referenced by tsgl::Spectrogram::draw(), and tsgl::CartesianBackground::drawAxes().
drawLine() [4/4]
void tsgl::Background::drawLine (float x1, float y1, float z1, float x2, float y2, float z2, float yaw, float pitch, float roll, ColorFloat color[]) [virtual]
Procedurally draws a Line to the Background.
Initializes a new Line based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x1 The x coordinate of the first endpoint of the line.
y1 The y coordinate of the first endpoint of the line.
z1 The z coordinate of the first endpoint of the line.
x2 The x coordinate of the second endpoint of the line.
y2 The y coordinate of the second endpoint of the line.
z2 The z coordinate of the second endpoint of the line.
yaw The yaw of the line.
pitch The pitch of the line.
roll The roll of the line.
color Array of ColorFloats for the Line's vertices.
drawPixel()
void tsgl::Background::drawPixel (float x, float y, ColorInt c) [virtual]
Draws a single pixel, specified in x,y format.
This function alters the value at the specified x, y offset within the Background's buffer variable.
Note
(0,0) signifies the center of the Background.
Parameters
x The x-position of the pixel.
y The y-position of the pixel.
color The color of the point.
Reimplemented in tsgl::CartesianBackground.
Referenced by ShadedVoronoi::draw(), Voronoi::draw(), tsgl::CartesianBackground::drawPixel(), LifeFarm::life(), and LifeFarm::moveAntsOld().
drawPolyline() [1/2]
void tsgl::Background::drawPolyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color) [virtual]
Procedurally draws a Polyline to the Background.
Initializes a new Polyline based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Polyline's center location.
y The y coordinate of the Polyline's center location.
z The z coordinate of the Polyline's center location.
numVertices The number of vertices to be drawn for the Polyline.
lineVertices Float array containing the Polyline's vertices (x1,y1,z1,x2,y2,z2,x3...).
yaw The Polyline's yaw rotation.
pitch The Polyline's pitch rotation.
roll The Polyline's roll rotation.
color ColorFloat for the Polyline's vertices.
Referenced by tsgl::CartesianBackground::drawFunction(), and tsgl::CartesianBackground::drawPartialFunction().
drawPolyline() [2/2]
void tsgl::Background::drawPolyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color[]) [virtual]
Procedurally draws a Polyline to the Background.
Initializes a new Polyline based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Polyline's center location.
y The y coordinate of the Polyline's center location.
z The z coordinate of the Polyline's center location.
numVertices The number of vertices to be drawn for the Polyline.
lineVertices Float array containing the Polyline's vertices (x1,y1,z1,x2,y2,z2,x3...).
yaw The Polyline's yaw rotation.
pitch The Polyline's pitch rotation.
roll The Polyline's roll rotation.
color Array of ColorFloats corresponding to the Polyline's vertices.
drawRectangle() [1/2]
void tsgl::Background::drawRectangle (float x, float y, float z, float width, float height, float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a Rectangle to the Background.
Initializes a new Rectangle based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Rectangle's center location.
y The y coordinate of the Rectangle's center location.
z The z coordinate of the Rectangle's center location.
width Width of the Rectangle.
height Height of the Rectangle.
yaw The Rectangle's yaw rotation.
pitch The Rectangle's pitch rotation.
roll The Rectangle's roll rotation.
color ColorFloat for the Rectangle's vertices.
outlined Boolean indicating if the Rectangle should be outlined or not, defaulting to not.
Referenced by tsgl::IntegralViewer::rectangleEvaluate().
drawRectangle() [2/2]
void tsgl::Background::drawRectangle (float x, float y, float z, float width, float height, float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a Rectangle to the Background.
Initializes a new Rectangle based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Rectangle's center location.
y The y coordinate of the Rectangle's center location.
z The z coordinate of the Rectangle's center location.
width Width of the Rectangle.
height Height of the Rectangle.
yaw The Rectangle's yaw rotation.
pitch The Rectangle's pitch rotation.
roll The Rectangle's roll rotation.
color Array of ColorFloats corresponding to the Rectangle's vertices.
outlined Boolean indicating if the Rectangle should be outlined or not, defaulting to not.
drawRegularPolygon() [1/2]
void tsgl::Background::drawRegularPolygon (float x, float y, float z, float radius, int sides, float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a RegularPolygon to the Background.
Initializes a new RegularPolygon based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the RegularPolygon's center location.
y The y coordinate of the RegularPolygon's center location.
z The z coordinate of the RegularPolygon's center location.
radius Distance from the RegularPolygon's center to each of its vertices.
points Number of sides on the RegularPolygon.
yaw The RegularPolygon's yaw rotation.
pitch The RegularPolygon's pitch rotation.
roll The RegularPolygon's roll rotation.
color ColorFloat for the RegularPolygon's vertices.
outlined Boolean indicating if the RegularPolygon should be outlined or not, defaulting to not.
Referenced by Table::drawStep(), Table::Table(), and Table3D::Table3D().
drawRegularPolygon() [2/2]
void tsgl::Background::drawRegularPolygon (float x, float y, float z, float radius, int sides, float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a RegularPolygon to the Background.
Initializes a new RegularPolygon based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the RegularPolygon's center location.
y The y coordinate of the RegularPolygon's center location.
z The z coordinate of the RegularPolygon's center location.
radius Distance from the RegularPolygon's center to each of its vertices.
points Number of sides on the RegularPolygon.
yaw The RegularPolygon's yaw rotation.
pitch The RegularPolygon's pitch rotation.
roll The RegularPolygon's roll rotation.
color Array of ColorFloats corresponding to the RegularPolygon's vertices.
outlined Boolean indicating if the RegularPolygon should be outlined or not, defaulting to not.
drawSquare() [1/2]
void tsgl::Background::drawSquare (float x, float y, float z, float sidelength, float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a Square to the Background.
Initializes a new Square based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Square's center location.
y The y coordinate of the Square's center location.
z The z coordinate of the Square's center location.
sidelength Length of each side of the Square.
yaw The Square's yaw rotation.
pitch The Square's pitch rotation.
roll The Square's roll rotation.
color ColorFloat for the Square's vertices.
outlined Boolean indicating if the Square should be outlined or not, defaulting to not.
Referenced by tsgl::VisualTaskQueue::reset(), tsgl::VisualTaskQueue::showLegend(), and tsgl::VisualTaskQueue::update().
drawSquare() [2/2]
void tsgl::Background::drawSquare (float x, float y, float z, float sidelength, float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a Square to the Background.
Initializes a new Square based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Square's center location.
y The y coordinate of the Square's center location.
z The z coordinate of the Square's center location.
sidelength Length of each side of the Square.
yaw The Square's yaw rotation.
pitch The Square's pitch rotation.
roll The Square's roll rotation.
color Array of ColorFloats corresponding to the Square's vertices.
outlined Boolean indicating if the Square should be outlined or not, defaulting to not.
drawStar() [1/2]
void tsgl::Background::drawStar (float x, float y, float z, float radius, int points, float yaw, float pitch, float roll, ColorFloat color, bool ninja = false, bool outlined = false) [virtual]
Procedurally draws a Star to the Background.
Initializes a new Star based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Star's center location.
y The y coordinate of the Star's center location.
z The z coordinate of the Star's center location.
radius Distance from the Star's center to each of its points.
points Number of points on the Star.
yaw The Star's yaw rotation.
pitch The Star's pitch rotation.
roll The Star's roll rotation.
color ColorFloat for the Star's vertices.
ninja Boolean indicating if the Star should be mirror-symmetrical or just rotationally symmetrical.
outlined Boolean indicating if the Star should be outlined or not, defaulting to not.
drawStar() [2/2]
void tsgl::Background::drawStar (float x, float y, float z, float radius, int points, float yaw, float pitch, float roll, ColorFloat color[], bool ninja = false, bool outlined = false) [virtual]
Procedurally draws a Star to the Background.
Initializes a new Star based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Star's center location.
y The y coordinate of the Star's center location.
z The z coordinate of the Star's center location.
radius Distance from the Star's center to each of its points.
points Number of points on the Star.
yaw The Star's yaw rotation.
pitch The Star's pitch rotation.
roll The Star's roll rotation.
color Array of ColorFloats corresponding to the Star's vertices.
ninja Boolean indicating if the Star should be mirror-symmetrical or just rotationally symmetrical.
outlined Boolean indicating if the Star should be outlined or not, defaulting to not.
drawText() [1/2]
void tsgl::Background::drawText (float x, float y, float z, std::string text, std::string fontFilename, float size, float yaw, float pitch, float roll, const ColorFloat & color) [virtual]
Procedurally draws Text to the Background.
Initializes a new Text based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Text's center location.
y The y coordinate of the Text's center location.
z The z coordinate of the Text's center location.
text String containing the characters to be rendered.
fontFilename String containing the filename for the font with which the Text will be rendered.
size The Text's size, relative to worldspace.
yaw The Text's yaw rotation.
pitch The Text's pitch rotation.
roll The Text's roll rotation.
color ColorFloat for the Text.
Referenced by Mandelbrot::draw(), tsgl::VisualTaskQueue::showLegend(), Table::Table(), and Table3D::Table3D().
drawText() [2/2]
void tsgl::Background::drawText (float x, float y, float z, std::wstring text, std::string fontFilename, float size, float yaw, float pitch, float roll, const ColorFloat & color) [virtual]
Procedurally draws Text to the Background.
Initializes a new Text based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x The x coordinate of the Text's center location.
y The y coordinate of the Text's center location.
z The z coordinate of the Text's center location.
text Wide string containing the characters to be rendered.
fontFilename String containing the filename for the font with which the Text will be rendered.
size The Text's size, relative to worldspace.
yaw The Text's yaw rotation.
pitch The Text's pitch rotation.
roll The Text's roll rotation.
color ColorFloat for the Text.
drawTriangle() [1/2]
void tsgl::Background::drawTriangle (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a Triangle to the Background.
Initializes a new Triangle based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x1 The x coordinate of the Triangle's first vertex location.
y1 The y coordinate of the Triangle's first vertex location.
z1 The z coordinate of the Triangle's first vertex location.
x2 The x coordinate of the Triangle's second vertex location.
y2 The y coordinate of the Triangle's second vertex location.
z2 The z coordinate of the Triangle's second vertex location.
x3 The x coordinate of the Triangle's third vertex location.
y3 The y coordinate of the Triangle's third vertex location.
z3 The z coordinate of the Triangle's third vertex location.
yaw The Triangle's yaw rotation.
pitch The Triangle's pitch rotation.
roll The Triangle's roll rotation.
color ColorFloat for the Triangle's vertices.
outlined Boolean indicating if the Triangle should be outlined or not, defaulting to not.
drawTriangle() [2/2]
void tsgl::Background::drawTriangle (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a Triangle to the Background.
Initializes a new Triangle based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
x1 The x coordinate of the Triangle's first vertex location.
y1 The y coordinate of the Triangle's first vertex location.
z1 The z coordinate of the Triangle's first vertex location.
x2 The x coordinate of the Triangle's second vertex location.
y2 The y coordinate of the Triangle's second vertex location.
z2 The z coordinate of the Triangle's second vertex location.
x3 The x coordinate of the Triangle's third vertex location.
y3 The y coordinate of the Triangle's third vertex location.
z3 The z coordinate of the Triangle's third vertex location.
yaw The Triangle's yaw rotation.
pitch The Triangle's pitch rotation.
roll The Triangle's roll rotation.
color Array of ColorFloats corresponding to the Triangle's vertices.
outlined Boolean indicating if the Triangle should be outlined or not, defaulting to not.
drawTriangleStrip() [1/2]
void tsgl::Background::drawTriangleStrip (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float z[], float yaw, float pitch, float roll, ColorFloat color, bool outlined = false) [virtual]
Procedurally draws a TriangleStrip to the Background.
Initializes a new TriangleStrip based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
centerX The x coordinate of the TriangleStrip's center location.
centerY The y coordinate of the TriangleStrip's center location.
centerZ The z coordinate of the TriangleStrip's center location.
numVertices The number of vertices to be drawn for the TriangleStrip.
x Float array containing the TriangleStrip's x vertices.
y Float array containing the TriangleStrip's y vertices.
z Float array containing the TriangleStrip's z vertices.
yaw The TriangleStrip's yaw rotation.
pitch The TriangleStrip's pitch rotation.
roll The TriangleStrip's roll rotation.
color ColorFloat for the TriangleStrip's vertices.
outlined Boolean indicating if the TriangleStrip should be outlined or not, defaulting to not.
drawTriangleStrip() [2/2]
void tsgl::Background::drawTriangleStrip (float centerX, float centerY, float centerZ, int numVertices, float x[], float y[], float z[], float yaw, float pitch, float roll, ColorFloat color[], bool outlined = false) [virtual]
Procedurally draws a TriangleStrip to the Background.
Initializes a new TriangleStrip based on the parameter values, and then adds it to the Array of Drawables to be rendered.
Parameters
centerX The x coordinate of the TriangleStrip's center location.
centerY The y coordinate of the TriangleStrip's center location.
centerZ The z coordinate of the TriangleStrip's center location.
numVertices The number of vertices to be drawn for the TriangleStrip.
x Float array containing the TriangleStrip's x vertices.
y Float array containing the TriangleStrip's y vertices.
z Float array containing the TriangleStrip's z vertices.
yaw The TriangleStrip's yaw rotation.
pitch The TriangleStrip's pitch rotation.
roll The TriangleStrip's roll rotation.
color Array of ColorFloats corresponding to the TriangleStrip's vertices.
outlined Boolean indicating if the TriangleStrip should be outlined or not, defaulting to not.
getClearColor()
virtual ColorFloat tsgl::Background::getClearColor () [inline], [virtual]
Accessor for color which is used to clear the Background when clear() is called.
Returns a ColorInt corresponding to the clear color of the Background.
Referenced by tsgl::Canvas::getBackgroundColor().
getHeight()
virtual GLint tsgl::Background::getHeight () [inline], [virtual]
Accessor for the pixel height of the Background.
Returns the value of the myHeight private variable, a GLint.
getPixel()
ColorInt tsgl::Background::getPixel (float x, float y) [virtual]
Gets the color of the pixel drawn on the current Background at the given x and y.
Note
(0,0) signifies the center of the Background's texture.
Parameters
x The x-position of the pixel to grab.
y The y-position of the pixel to grab.
Returns
A ColorInt containing the color of the pixel at (x,y).
Reimplemented in tsgl::CartesianBackground.
Referenced by tsgl::CartesianBackground::getPixel().
getWidth()
virtual GLint tsgl::Background::getWidth () [inline], [virtual]
Accessor for the pixel width of the Background.
Returns the value of the myWidth private variable, a GLint.
init()
void tsgl::Background::init (Shader * shapeS, Shader * textS, Shader * textureS, Camera * camera, GLFWwindow * window) [virtual]
Assigns Drawable shaders and initializes framebuffers within the parameter window's context.
Assigns shapeShader, textShader, textureShader to parameters and initializes two framebuffers: MSAA and non-MSAA.
Parameters
shapeS Pointer to a shader for Shape Drawables.
textS Pointer to a shader for Text Drawables.
textureS Pointer to a shader for texture rendering.
window GLFWwindow * within whose context the framebuffers will be initialized.
Referenced by tsgl::Canvas::setBackground().
selectShaders()
void tsgl::Background::selectShaders (unsigned int sType) [protected], [virtual]
Activates the corresponding Shader for a given Drawable.
Parameters
sType Unsigned int with a corresponding value for each type of Shader.
Reimplemented in tsgl::CartesianBackground.
Referenced by draw().
setClearColor()
void tsgl::Background::setClearColor (ColorFloat c) [virtual]
Mutator for the color used to clear the Background when clear() is called.
Sets the clear color to the parameter ColorFloat.
Parameters
c ColorFloat assigned to the clear color of the Background.
Referenced by tsgl::Canvas::setBackgroundColor().
The documentation for this class was generated from the following files:
Background.h
Background.cpp