tsgl::Polyline Class Reference
Draw multiple lines chained together.
#include <Polyline.h>
Public Member Functions
Polyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new monocolored Polyline.
Polyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new multicolored Polyline.
virtual void draw (Shader *shader)
Draw the Polyline.
virtual void setColor (ColorFloat c)
Sets the Polyline to a new color.
virtual void setColor (ColorFloat c[])
Sets the Polyline to a new array of colors.
virtual ColorFloat getColor ()
Accessor for Shape's color.
virtual void getColors (std::vector< ColorFloat > &colorVec)
Accessor for Shape's colors.
bool isProcessed ()
Overrides isProcessed() in Drawable.h.
Protected Member Functions
virtual void addVertex (GLfloat x, GLfloat y, GLfloat z, const ColorFloat &color=WHITE)
Adds another vertex to a Polyline.
Polyline (float x, float y, float z, int numVertices, float yaw, float pitch, float roll)
Explicitly constructs a new Polyline.
Protected Attributes
int numberOfVertices
int currentVertex = 0
Detailed Description
Draw multiple lines chained together.
Polyline is a class for holding vertex data for multiple lines whose endpoints are connected.
This method is optimized for long lists and offers a marked improvement over drawing individual Line instances.
Note
The addVertex() method must be called the same number of times as specified in the constructor, unless a float array is also passed.
Calling addVertex() after all vertices have been added will do nothing.
Calling Drawable::draw() before all vertices have been added will do nothing.
Constructor & Destructor Documentation
Polyline() [1/3]
tsgl::Polyline::Polyline (float x, float y, float z, int numVertices, float yaw, float pitch, float roll) [protected]
Explicitly constructs a new Polyline.
Explicit constructor for a new Polyline object.
Parameters
x The x coordinate of the center of the Polyline.
y The y coordinate of the center of the Polyline.
z The z coordinate of the center of the Polyline.
numVertices The number of vertices in the Polyline.
yaw The Polyline's yaw.
pitch The Polyline's pitch.
roll The Polyline's roll.
Warning
An invariant is held where if v is less than 2 then an error message is given.
Returns
A new Polyline with a buffer for storing the specified numbered of vertices.
Polyline() [2/3]
tsgl::Polyline::Polyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a new monocolored Polyline.
Explicit constructor for a new Polyline object.
Parameters
x The x coordinate of the center of the Polyline.
y The y coordinate of the center of the Polyline.
z The z coordinate of the center of the Polyline.
numVertices The number of vertices in the Polyline.
lineVertices An array of vertices for the Polyline. 3 floats * numVertices, x-y-z.
yaw The Polyline's yaw.
pitch The Polyline's pitch.
roll The Polyline's roll.
color Color of the Polyline, as a ColorFloat.
Warning
An invariant is held where if v is less than 2 then an error message is given.
Returns
A new Polyline with a buffer for storing the specified numbered of vertices.
Polyline() [3/3]
tsgl::Polyline::Polyline (float x, float y, float z, int numVertices, float lineVertices[], float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a new multicolored Polyline.
Explicit constructor for a new Polyline object.
Parameters
x The x coordinate of the center of the Polyline.
y The y coordinate of the center of the Polyline.
z The z coordinate of the center of the Polyline.
numVertices The number of vertices in the Polyline.
lineVertices An array of vertices for the Polyline. 3 floats * numVertices, x-y-z.
yaw The Polyline's yaw.
pitch The Polyline's pitch.
roll The Polyline's roll.
color Array of ColorFloats for the Polyline; 1 ColorFloat per vertex.
Warning
An invariant is held where if v is less than 2 then an error message is given.
Returns
A new Polyline with a buffer for storing the specified numbered of vertices.
Member Function Documentation
addVertex()
void tsgl::Polyline::addVertex (GLfloat x, GLfloat y, GLfloat z, const ColorFloat & color = WHITE) [protected], [virtual]
Adds another vertex to a Polyline.
This function initializes the next vertex in the Polyline and adds it to a Polyline buffer.
Parameters
x The x position of the vertex.
y The y position of the vertex.
z The z position of the vertex.
color The reference variable of the color of the vertex.
Note
This function does nothing if the vertex buffer is already full.
A message is given indicating that the vertex buffer is full.
Referenced by tsgl::Line::Line(), and Polyline().
draw()
void tsgl::Polyline::draw (Shader * shader) [virtual]
Draw the Polyline.
This function actually draws the Polyline to the Canvas.
Note
This function does nothing if the vertex buffer is not yet full.
A message indicating that the Polyline cannot be drawn yet will be given if the above condition is met (vertex buffer = not full).
Implements tsgl::Drawable.
Referenced by tsgl::ProgressBar::~ProgressBar().
getColor()
ColorFloat tsgl::Polyline::getColor () [virtual]
Accessor for Shape's color.
Returns the color of Shape's first vertex.
Note
For multicolored Shapes, use getColors() to access a vector of all relevant colors.
getColors()
void tsgl::Polyline::getColors (std::vector< ColorFloat > & colorVec) [virtual]
Accessor for Shape's colors.
Populates the reference parameter vector with a ColorFloat for each vertex of Shape.
Parameters
colorVec A vector of ColorFloats to which the ColorFloats associated with Shape will be pushed.
isProcessed()
bool tsgl::Polyline::isProcessed () [virtual]
Overrides isProcessed() in Drawable.h.
Overrides Drawable::isProcessed() to include invariant.
Reimplemented from tsgl::Drawable.
setColor() [1/2]
void tsgl::Polyline::setColor (ColorFloat c) [virtual]
Sets the Polyline to a new color.
Parameters
c The new ColorFloat.
setColor() [2/2]
void tsgl::Polyline::setColor (ColorFloat c[]) [virtual]
Sets the Polyline to a new array of colors.
Parameters
c The new array of ColorFloats.
The documentation for this class was generated from the following files:
Polyline.h
Polyline.cpp