tsgl::Arrow Class Reference
Draw a simple Arrow.
#include <Arrow.h>
Public Member Functions
Arrow (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, GLfloat width, float yaw, float pitch, float roll, ColorFloat color, bool doubleArrow=false)
Explicitly constructs a new Arrow.
Arrow (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, GLfloat width, float yaw, float pitch, float roll, ColorFloat color[], bool doubleArrow=false)
Explicitly constructs a new Arrow.
Arrow (float x, float y, float z, GLfloat length, GLfloat width, float yaw, float pitch, float roll, ColorFloat color, bool doubleArrow=false)
Explicitly constructs a new Arrow.
Arrow (float x, float y, float z, GLfloat length, GLfloat width, float yaw, float pitch, float roll, ColorFloat color[], bool doubleArrow=false)
Explicitly constructs a new Arrow.
void setLength (GLfloat length)
Replacement mutator for the length of the Arrow.
void changeLengthBy (GLfloat delta)
Alteration mutator for the length of the Arrow.
GLfloat getLength ()
Accessor for the length of the arrow from endpoint to endpoint.
void setWidth (GLfloat width)
Replacement mutator for the width of the Arrow.
void changeWidthBy (GLfloat delta)
Alteration mutator for the width of the Arrow.
GLfloat getWidth ()
Accessor for the width of the arrow from widest point to widest point.
void setFirstEndpoint (GLfloat x, GLfloat y, GLfloat z)
Mutator for the first endpoint coordinates of the Arrow.
void setSecondEndpoint (GLfloat x, GLfloat y, GLfloat z)
Mutator for the second endpoint coordinates of the Arrow.
GLfloat getFirstEndpointX ()
Accessor for the x-coordinate of the Arrow's first endpoint.
GLfloat getFirstEndpointY ()
Accessor for the y-coordinate of the Arrow's first endpoint.
GLfloat getFirstEndpointZ ()
Accessor for the z-coordinate of the Arrow's first endpoint.
GLfloat getSecondEndpointX ()
Accessor for the x-coordinate of the Arrow's second endpoint.
GLfloat getSecondEndpointY ()
Accessor for the y-coordinate of the Arrow's second endpoint.
GLfloat getSecondEndpointZ ()
Accessor for the z-coordinate of the Arrow's second endpoint.
virtual void setColor (ColorFloat c)
Sets the Shape to a new color.
virtual void setColor (ColorFloat c[])
Sets the Arrow to a new color.
virtual void getColors (std::vector< ColorFloat > &colorVec)
Accessor for Arrow's colors.
Additional Inherited Members
Detailed Description
Draw a simple Arrow.
Arrow is a class for holding vertex data for a concave polygon shaped like an Arrow.
Constructor & Destructor Documentation
Arrow() [1/4]
tsgl::Arrow::Arrow (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, GLfloat width, float yaw, float pitch, float roll, ColorFloat color, bool doubleArrow = false)
Explicitly constructs a new Arrow.
This is the constructor for the Arrow class.
Parameters
x1 The x coordinate of the first endpoint of the arrow.
y1 The y coordinate of the first endpoint of the arrow.
z1 The z coordinate of the first endpoint of the arrow.
x2 The x coordinate of the second endpoint of the arrow.
y2 The y coordinate of the second endpoint of the arrow.
z2 The z coordinate of the second endpoint of the arrow.
width The width of the arrow at its widest points.
yaw The yaw of the arrow.
pitch The pitch of the arrow.
roll The roll of the arrow.
color A ColorFloat for the color of the Arrow.
Returns
A new Arrow with the specified endpoints and color.
Arrow() [2/4]
tsgl::Arrow::Arrow (GLfloat x1, GLfloat y1, GLfloat z1, GLfloat x2, GLfloat y2, GLfloat z2, GLfloat width, float yaw, float pitch, float roll, ColorFloat color[], bool doubleArrow = false)
Explicitly constructs a new Arrow.
This is the constructor for the Arrow class.
Parameters
x1 The x coordinate of the first endpoint of the arrow.
y1 The y coordinate of the first endpoint of the arrow.
z1 The z coordinate of the first endpoint of the arrow.
x2 The x coordinate of the second endpoint of the arrow.
y2 The y coordinate of the second endpoint of the arrow.
z2 The z coordinate of the second endpoint of the arrow.
width The width of the arrow at its widest points.
yaw The yaw of the arrow.
pitch The pitch of the arrow.
roll The roll of the arrow.
color An array of ColorFloats for the colors of the Arrow.
Returns
A new Arrow with the specified endpoints and color.
Arrow() [3/4]
tsgl::Arrow::Arrow (float x, float y, float z, GLfloat length, GLfloat width, float yaw, float pitch, float roll, ColorFloat color, bool doubleArrow = false)
Explicitly constructs a new Arrow.
This is the constructor for the Arrow class.
Parameters
x The x coordinate of the center of the arrow.
y The y coordinate of the center of the arrow.
z The z coordinate of the center of the arrow.
length The length of the arrow (from endpoint to endpoint).
width The width of the arrow (between its widest points).
yaw The yaw of the arrow.
pitch The pitch of the arrow.
roll The roll of the arrow.
color A ColorFloat for the color of the Arrow.
Returns
A new Arrow with the specified length and color.
Note
At 0,0,0 yaw,pitch,roll, the arrow will be drawn directly parallel to the x-axis as a plane perpindicular to the z-axis.
Arrow() [4/4]
tsgl::Arrow::Arrow (float x, float y, float z, GLfloat length, GLfloat width, float yaw, float pitch, float roll, ColorFloat color[], bool doubleArrow = false)
Explicitly constructs a new Arrow.
This is the constructor for the Arrow class.
Parameters
x The x coordinate of the center of the arrow.
y The y coordinate of the center of the arrow.
z The z coordinate of the center of the arrow.
length The length of the arrow (from endpoint to endpoint).
width The width of the arrow (between its widest points).
yaw The yaw of the arrow.
pitch The pitch of the arrow.
roll The roll of the arrow.
color An array of ColorFloats for the colors of the Arrow.
Returns
A new Arrow with the specified length and color.
Note
At 0,0,0 yaw,pitch,roll, the arrow will be drawn directly parallel to the x-axis as a plane perpindicular to the z-axis.
Member Function Documentation
changeLengthBy()
void tsgl::Arrow::changeLengthBy (GLfloat delta)
Alteration mutator for the length of the Arrow.
Alters the value of the myLength instance variable by delta and modifies the vertices array accordingly.
Parameters
delta The difference between the old and new lengths of the Arrow.
changeWidthBy()
void tsgl::Arrow::changeWidthBy (GLfloat delta)
Alteration mutator for the width of the Arrow.
Alters the value of the myWidth instance variable by delta and modifies the vertices array accordingly.
Parameters
delta The difference between the old and new widths of the Arrow.
Referenced by getLength().
getColors()
void tsgl::Arrow::getColors (std::vector< ColorFloat > & colorVec) [virtual]
Accessor for Arrow's colors.
Populates the reference parameter vector with a ColorFloat for each end of Arrow.
Parameters
colorVec A vector of ColorFloats to which the ColorFloats associated with Arrow will be pushed.
Note
Overrides Shape::getColors().
Reimplemented from tsgl::Shape.
Referenced by setColor().
getFirstEndpointX()
float tsgl::Arrow::getFirstEndpointX ()
Accessor for the x-coordinate of the Arrow's first endpoint.
Returns the value of the myEndpointX1 instance variable, rotated around myRotationPoint by myCurrentYawPitchRoll.
Returns
myEndpointX1, containing the value of the Arrow's first endpoint's x-coordinate.
Note
See Drawable::getCenterX() documentation for more info.
Referenced by getWidth().
getFirstEndpointY()
float tsgl::Arrow::getFirstEndpointY ()
Accessor for the y-coordinate of the Arrow's first endpoint.
Returns the value of the myEndpointY1 instance variable, rotated around myRotationPoint by myCurrentYawPitchRoll.
Returns
myEndpointY1, containing the value of the Arrow's first endpoint's y-coordinate.
Note
See Drawable::getCenterY() documentation for more info.
Referenced by getWidth().
getFirstEndpointZ()
float tsgl::Arrow::getFirstEndpointZ ()
Accessor for the z-coordinate of the Arrow's first endpoint.
Returns the value of the myEndpointZ1 instance variable, rotated around myRotationPoint by myCurrentYawPitchRoll.
Returns
myEndpointZ1, containing the value of the Arrow's first endpoint's z-coordinate.
Note
See Drawable::getCenterZ() documentation for more info.
Referenced by getWidth().
getLength()
GLfloat tsgl::Arrow::getLength () [inline]
Accessor for the length of the arrow from endpoint to endpoint.
Returns the value of the myLength instance variable.
Returns
myLength, containing the distance in 3D space between the two endpoints.
getSecondEndpointX()
float tsgl::Arrow::getSecondEndpointX ()
Accessor for the x-coordinate of the Arrow's second endpoint.
Returns the value of the myEndpointX2 instance variable, rotated around myRotationPoint by myCurrentYawPitchRoll.
Returns
myEndpointX2, containing the value of the Arrow's second endpoint's x-coordinate.
Note
See Drawable::getCenterX() documentation for more info.
Referenced by getWidth().
getSecondEndpointY()
float tsgl::Arrow::getSecondEndpointY ()
Accessor for the y-coordinate of the Arrow's second endpoint.
Returns the value of the myEndpointY2 instance variable, rotated around myRotationPoint by myCurrentYawPitchRoll.
Returns
myEndpointY2, containing the value of the Arrow's second endpoint's y-coordinate.
Note
See Drawable::getCenterY() documentation for more info.
Referenced by getWidth().
getSecondEndpointZ()
float tsgl::Arrow::getSecondEndpointZ ()
Accessor for the z-coordinate of the Arrow's second endpoint.
Returns the value of the myEndpointZ2 instance variable, rotated around myRotationPoint by myCurrentYawPitchRoll.
Returns
myEndpointZ2, containing the value of the Arrow's second endpoint's z-coordinate.
Note
See Drawable::getCenterZ() documentation for more info.
Referenced by getWidth().
getWidth()
GLfloat tsgl::Arrow::getWidth () [inline]
Accessor for the width of the arrow from widest point to widest point.
Returns the value of the myLength instance variable.
Returns
myLength, containing the distance in 3D space between the two endpoints.
setColor() [1/2]
virtual void tsgl::Arrow::setColor (ColorFloat c) [inline], [virtual]
Sets the Shape to a new color.
Parameters
c The new ColorFloat.
Reimplemented from tsgl::Shape.
setColor() [2/2]
void tsgl::Arrow::setColor (ColorFloat c[]) [virtual]
Sets the Arrow to a new color.
Parameters
c The new array of ColorFloats.
Note
Overrides Shape::setColor(ColorFloat c[]).
Reimplemented from tsgl::Shape.
setFirstEndpoint()
void tsgl::Arrow::setFirstEndpoint (GLfloat x, GLfloat y, GLfloat z)
Mutator for the first endpoint coordinates of the Arrow.
Sets the values of myEndpoint_1 instance variables by the parameters and modifies the vertices array accordingly.
Parameters
x The new x-coordinate of the first endpoint of the Arrow.
y The new y-coordinate of the first endpoint of the Arrow.
z The new z-coordinate of the first endpoint of the Arrow.
Referenced by getWidth().
setLength()
void tsgl::Arrow::setLength (GLfloat length)
Replacement mutator for the length of the Arrow.
Sets the value of the myLength instance variable to the parameter, and modifies the vertices array accordingly.
Parameters
length New length of the Arrow, a float.
setSecondEndpoint()
void tsgl::Arrow::setSecondEndpoint (GLfloat x, GLfloat y, GLfloat z)
Mutator for the second endpoint coordinates of the Arrow.
Sets the values of myEndpoint_2 instance variables by the parameters and modifies the vertices array accordingly.
Parameters
x The new x-coordinate of the second endpoint of the Arrow.
y The new y-coordinate of the second endpoint of the Arrow.
z The new z-coordinate of the second endpoint of the Arrow.
Referenced by getWidth().
setWidth()
void tsgl::Arrow::setWidth (GLfloat width)
Replacement mutator for the width of the Arrow.
Sets the value of the myWidth instance variable to the parameter, and modifies the vertices array accordingly.
Parameters
width New width of the Arrow, a float.
Referenced by getLength().
The documentation for this class was generated from the following files:
Arrow.h
Arrow.cpp