tsgl::VisualTaskQueue Class Reference
Provides a a visualization tool for a parallel queue of elements.
#include <VisualTaskQueue.h>
Public Member Functions
VisualTaskQueue (int elements, int sideLength=12, float aspect=1.0f, int spacing=2, int borderLength=8)
Default VisualTaskQueue constructor method.
~VisualTaskQueue ()
VisualTaskQueue destructor method.
void showLegend (int threads=-1)
Shows a key/legend for the VisualTaskQueue.
void update (int index, VQState state)
Updates the state of the VisualTaskQueue.
void reset ()
Resets all of the elements in the VisualTaskQueue.
void close ()
Closes the visual queue.
void sleep ()
Detailed Description
Provides a a visualization tool for a parallel queue of elements.
VisualTaskQueue is a self-contained Canvas intended to help visualize the progress of a parallel queue of taks or elements.
Given a maximum queue length of N elements, a VisualTaskQueue will display N rectangles on its internal Canvas. These rectangles can be in one of three states: cleared, running, or finished. Cleared elements are always displayed in white, whereas running elements are displayed in a darker shade of the current thread's color, and finished elements are displayed in a lighter shade of the color of the thread the completed the element.
Constructor & Destructor Documentation
VisualTaskQueue()
tsgl::VisualTaskQueue::VisualTaskQueue (int elements, int sideLength = 12, float aspect = 1.0f, int spacing = 2, int borderLength = 8)
Default VisualTaskQueue constructor method.
This is the default constructor for the VisualTaskQueue class.
Parameters
elements The maximum number of elements to be drawn on the VisualTaskQueue. Setting this to higher than the actual number of elements may result in some unused, empty rectangle. Setting this to lower than the actual number of elements may result in some rectangles being drawn off the VisualTaskQueue Canvas.
sideLength The side length in pixels of the task rectangles to be drawn on the VisualTaskQueue Canvas.
aspec The approximate aspect ratio of height/width for the VisualTaskQueue Canvas.
spacing The space in pixels between the rectangles representing elements in the VisualTaskQueue.
borderLength The space in pixels between the outer VisualTaskQueue rectangles and the border of the VisualTaskQueue Canvas.
Returns
A new VisualTaskQueue with the specified maximum number of elements, rectangle side length, approximate aspect ratio, spacing between rectangles, and spacing around the borders.
 VisualTaskQueue()
tsgl::VisualTaskQueue::~VisualTaskQueue ()
VisualTaskQueue destructor method.
This is the destructor for the VisualTaskQueue class.
Frees up memory that was allocated to a VisualTaskQueue instance.
Member Function Documentation
close()
void tsgl::VisualTaskQueue::close ()
Closes the visual queue.
This function closes and destroys the internal Canvas created by the VisualTaskQueue.
Warning
Do not attempt to reset() or update() the VisualTaskQueue after closing it.
Referenced by Julia::draw().
reset()
void tsgl::VisualTaskQueue::reset ()
Resets all of the elements in the VisualTaskQueue.
This function tells VisualTaskQueue to clear the state information of all of the elements.
Referenced by Julia::draw().
showLegend()
void tsgl::VisualTaskQueue::showLegend (int threads = -1)
Shows a key/legend for the VisualTaskQueue.
This function opens up a separate Canvas displaying a legend for the VisualTaskQueue, showing which colors correspond to which threads.
Parameters
threads The number of threads the VisualTaskQueue is using.
Referenced by Julia::draw().
update()
void tsgl::VisualTaskQueue::update (int index, VQState state)
Updates the state of the VisualTaskQueue.
This function updates an element of the VisualTaskQueue with a new state.
Parameters
index The index of the element to update.
state The new state to put the element in. Must be one of RUNNING or FINISHED.
Referenced by Julia::draw().
The documentation for this class was generated from the following files:
VisualTaskQueue.h
VisualTaskQueue.cpp