RWDatabase< Item > Class Template Reference
An abstract database protecting a vector of data.
#include <RWDatabase.h>
Public Member Functions
RWDatabase ()
Default constructor for the RWDatabase class.
RWDatabase (int max)
Explicit constructor for the RWDatabase class.
int getItemCount ()
int getMaxCapacity ()
Item read (unsigned index)
read() returns the Item from the vector at an index
void write (Item it, unsigned index)
write() sets an item at an index
Protected Attributes
std::vector< Item > vec
unsigned maxCapacity
Detailed Description
template<class Item>
class RWDatabase< Item >
An abstract database protecting a vector of data.
Database has its locks and a vector
Locking methods must be implemented in subclass, giving priority to different types of threads.
Constructor & Destructor Documentation
RWDatabase() [1/2]
template<class Item >
RWDatabase< Item >::RWDatabase ()
Default constructor for the RWDatabase class.
Returns
: The constructed RWDatabase object.
RWDatabase() [2/2]
template<class Item >
RWDatabase< Item >::RWDatabase (int max)
Explicit constructor for the RWDatabase class.
Parameters
max,an int describing the maximum size of the contained vector
Returns
: The constructed RWDatabase object.
Member Function Documentation
read()
template<class Item >
Item RWDatabase< Item >::read (unsigned index)
read() returns the Item from the vector at an index
Parameters
index,an index in the vector to access a piece of data
Referenced by Reader::Reader(), and Writer::Writer().
write()
template<class Item>
void RWDatabase< Item >::write (Item it, unsigned index)
write() sets an item at an index
Parameters
it,an Item to add to the vector
index,the index to add the Item it
Referenced by Writer::Writer().
The documentation for this class was generated from the following file:
/home/sth5/test/TSGL/src/examples/ReaderWriter/RWDatabase.h