tsgl::Text Class Reference
Draw a string of text.
#include <Text.h>
Public Member Functions
Text (float x, float y, float z, std::wstring text, std::string fontFilename, float size, float yaw, float pitch, float roll, const ColorFloat &color)
Explicitly constructs a new Text instance.
virtual void draw (Shader *shader)
Draw the Text.
virtual void setText (std::wstring text)
Alter the Text's string.
virtual void setSize (float size)
Alter the Text's font size.
virtual void setFont (std::string filename)
Alter the Text's font.
virtual void setColor (const ColorFloat &color)
Alter the Text's color.
std::wstring getText ()
float getSize ()
GLfloat getWidth ()
GLfloat getHeight ()
ColorFloat getColor ()
Additional Inherited Members
Detailed Description
Draw a string of text.
Text is a class for holding the data necessary for rendering a string of text.
Note
Text is aligned by the upper-left corner.
Fonts supported by FreeType are also supported.
Constructor & Destructor Documentation
Text()
tsgl::Text::Text (float x, float y, float z, std::wstring text, std::string fontFilename, float size, float yaw, float pitch, float roll, const ColorFloat & color)
Explicitly constructs a new Text instance.
This is the constructor for the Text class.
Parameters
x The center x coordinate of the text.
y The center y coordinate of the text.
z The center z coordinate of the text.
text The string to draw.
fontFilename The path of the filename detailing the font the Text will use.
size The height of the text (will be relative to Canvas).
yaw The yaw of the Text in 3D space.
pitch The pitch of the Text in 3D space.
roll The roll of the Text in 3D space.
color A reference to the ColorFloat to use.
Returns
A new Text instance with the specified string, position, and color.
Member Function Documentation
draw()
void tsgl::Text::draw (Shader * shader) [virtual]
Draw the Text.
This function actually draws the Text to the Canvas.
Parameters
shader Pointer to appropriate instance of Shader being used to render the Text.
Implements tsgl::Drawable.
setColor()
void tsgl::Text::setColor (const ColorFloat & color) [virtual]
Alter the Text's color.
This function changes myColor to the parameter ColorFloat
Parameters
color The ColorFloat to change myColor to.
Referenced by Consumer::act(), Consumer::lock(), Producer::lock(), Reader::Reader(), Producer::wait(), and Writer::Writer().
setFont()
void tsgl::Text::setFont (std::string filename) [virtual]
Alter the Text's font.
This function changes myLoader's font to the parameter font.
Parameters
filename The new font file name.
Warning
The center of the text will not change despite any differences in rendered string length.
setSize()
void tsgl::Text::setSize (float size) [virtual]
Alter the Text's font size.
This function changes mySize to the parameter size.
Parameters
size The new size.
Warning
The center of the text will not change despite any differences in rendered string length.
Referenced by Consumer::act(), Producer::act(), Reader::Reader(), and Writer::Writer().
setText()
void tsgl::Text::setText (std::wstring text) [virtual]
Alter the Text's string.
This function changes myString to the parameter text
Parameters
text The text to change myString to.
Warning
The center of the text will not change despite any differences in rendered string length.
Referenced by Consumer::act(), Producer::act(), Reader::Reader(), and Writer::Writer().
The documentation for this class was generated from the following files:
Text.h
Text.cpp