tsgl::Pyramid Class Reference
Draw an arbitrary Pyramid with colored vertices.
#include <Pyramid.h>
Public Member Functions
Pyramid (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c)
Explicitly constructs a new Pyramid.
Pyramid (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c[])
Explicitly constructs a new Pyramid.
virtual void setRadius (float radius)
Mutates the Pyramid's base's radius.
virtual void changeRadiusBy (float delta)
Mutates the Pyramid's base's radius by the parameter amount.
virtual void setHeight (float height)
Mutates the distance from the center of the Pyramid's base to the tip.
virtual void changeHeightBy (float delta)
Mutates the distance from the center of the Pyramid's base to the tip by the parameter amount.
virtual GLfloat getHeight ()
Accessor for the height of the Prism.
virtual GLfloat getRadius ()
Accessor for the radius of the Prism.
virtual void setColor (ColorFloat c)
Sets the Pyramid to a new color.
virtual void setColor (ColorFloat c[])
Sets the Pyramid to an array of new colors.
virtual void getColors (std::vector< ColorFloat > &colorVec)
Accessor for Arrow's colors.
Protected Attributes
GLfloat myHeight
GLfloat myRadius
int mySides
Additional Inherited Members
Detailed Description
Draw an arbitrary Pyramid with colored vertices.
Pyramid is a class for holding vertex data for a pyramid with a base with at least 3 sides.
Constructor & Destructor Documentation
Pyramid() [1/2]
tsgl::Pyramid::Pyramid (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c)
Explicitly constructs a new Pyramid.
Explicit constructor for a Pyramid object.
Parameters
x The x coordinate of the center of the Pyramid.
y The y coordinate of the center of the Pyramid.
z The z coordinate of the center of the Pyramid.
height The distance from the center of the base to tip of the Pyramid.
radius The distance from the center of the Pyramid's base to each vertex of the base.
sides The number of sides of the Pyramid's base.
yaw The Pyramid's yaw.
pitch The Pyramid's pitch.
roll The Pyramid's roll.
c A ColorFloat for the Pyramid's vertex colors.
Warning
An invariant is held where if sides is less than 3 then an error message is given.
An invariant is held where if radius isn't positive then an error message is given.
Returns
A new Pyramid with a buffer for storing the specified numbered of vertices.
Pyramid() [2/2]
tsgl::Pyramid::Pyramid (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c[])
Explicitly constructs a new Pyramid.
Explicit constructor for a Pyramid object.
Parameters
x The x coordinate of the center of the Pyramid.
y The y coordinate of the center of the Pyramid.
z The z coordinate of the center of the Pyramid.
height The distance from the center of the base to tip of the Pyramid.
radius The distance from the center of the Pyramid's base to each vertex of the base.
sides The number of sides of the Pyramid's base.
yaw The Pyramid's yaw.
pitch The Pyramid's pitch.
roll The Pyramid's roll.
c An array of ColorFloats for the Pyramid's vertex colors.
Warning
An invariant is held where if sides is less than 3 then an error message is given.
An invariant is held where if radius isn't positive then an error message is given.
Returns
A new Pyramid with a buffer for storing the specified numbered of vertices.
Member Function Documentation
changeHeightBy()
void tsgl::Pyramid::changeHeightBy (float delta) [virtual]
Mutates the distance from the center of the Pyramid's base to the tip by the parameter amount.
Parameters
delta The amount by which to change the height of the pyramid.
changeRadiusBy()
void tsgl::Pyramid::changeRadiusBy (float delta) [virtual]
Mutates the Pyramid's base's radius by the parameter amount.
Parameters
delta The amount by which to change the radius of the Pyramid's base.
getColors()
void tsgl::Pyramid::getColors (std::vector< ColorFloat > & colorVec) [virtual]
Accessor for Arrow's colors.
Populates the reference parameter vector with a ColorFloat for each end of Arrow.
Parameters
colorVec A vector of ColorFloats to which the ColorFloats associated with Arrow will be pushed.
Note
Overrides Shape::getColors().
Reimplemented from tsgl::Shape.
Referenced by getRadius().
getHeight()
virtual GLfloat tsgl::Pyramid::getHeight () [inline], [virtual]
Accessor for the height of the Prism.
Returns the value of the myHeight private variable, a GLfloat.
getRadius()
virtual GLfloat tsgl::Pyramid::getRadius () [inline], [virtual]
Accessor for the radius of the Prism.
Returns the value of the myRadius private variable, a GLfloat.
setColor() [1/2]
void tsgl::Pyramid::setColor (ColorFloat c) [virtual]
Sets the Pyramid to a new color.
Parameters
c The new ColorFloat.
Reimplemented from tsgl::Shape.
Referenced by getRadius(), and Philosopher3D::refreshColor().
setColor() [2/2]
void tsgl::Pyramid::setColor (ColorFloat c[]) [virtual]
Sets the Pyramid to an array of new colors.
Parameters
c An array of new ColorFloats.
The array should have mySides+2 ColorFloats minimum.
Reimplemented from tsgl::Shape.
setHeight()
void tsgl::Pyramid::setHeight (float height) [virtual]
Mutates the distance from the center of the Pyramid's base to the tip.
Parameters
height The Pyramid's new height.
setRadius()
void tsgl::Pyramid::setRadius (float radius) [virtual]
Mutates the Pyramid's base's radius.
Parameters
radius The new radius of the Pyramid's base.
The documentation for this class was generated from the following files:
Pyramid.h
Pyramid.cpp