tsgl::Drawable Class Reference
A class for drawing objects onto a Canvas or CartesianCanvas.
#include <Drawable.h>
Public Member Functions
Drawable (float x, float y, float z, float yaw, float pitch, float roll)
Constructs a new Drawable.
virtual void draw (Shader *shader)=0
virtual void changeXBy (float deltaX)
Alters the Drawable's x position.
virtual void changeYBy (float deltaY)
Alters the Drawable's y position.
virtual void changeZBy (float deltaZ)
Alters the Drawable's z position.
virtual void changeCenterBy (float deltaX, float deltaY, float deltaZ)
Alters the Drawable's vertex locations.
virtual void setCenterX (float x)
Sets the Drawable's x position.
virtual void setCenterY (float y)
Sets the Drawable's y position.
virtual void setCenterZ (float z)
Sets the Drawable's z position.
virtual void setCenter (float x, float y, float z)
Moves the Drawable to new coordinates.
virtual void setYaw (float yaw)
Mutator for the Drawable's yaw.
virtual void setPitch (float pitch)
Mutator for the Drawable's pitch.
virtual void setRoll (float roll)
Mutator for the Drawable's roll.
virtual void setYawPitchRoll (float yaw, float pitch, float roll)
Mutator for the yaw, pitch, and roll of the Drawable.
virtual void changeYawBy (float deltaYaw)
Alters the Drawable's yaw by a specified amount.
virtual void changePitchBy (float deltaPitch)
Alters the Drawable's pitch by a specified amount.
virtual void changeRollBy (float deltaRoll)
Alters the Drawable's roll by a specified amount.
virtual void changeYawPitchRollBy (float deltaYaw, float deltaPitch, float deltaRoll)
Alters the Drawable's yaw, pitch, and roll by a specified amount.
virtual void setRotationPointX (float x)
Virtual mutator that changes the rotation point of the Drawable's x value.
virtual void setRotationPointY (float y)
Virtual mutator that changes the rotation point of the Drawable's y value.
virtual void setRotationPointZ (float z)
Virtual mutator that changes the rotation point of the Drawable's z value.
virtual void setRotationPoint (float x, float y, float z)
Sets the point around which Drawable is rotated.
virtual float getCenterX ()
Accessor for the center x-coordinate of the Drawable.
virtual float getCenterY ()
Accessor for the center z-coordinate of the Drawable.
virtual float getCenterZ ()
Accessor for the center z-coordinate of the Drawable.
virtual float getYaw ()
Accessor for the Yaw of the Drawable.
virtual float getPitch ()
Accessor for the Pitch of the Drawable.
virtual float getRoll ()
Accessor for the Roll of the Drawable.
virtual float getRotationPointX ()
Accessor for the rotation x-coordinate of the Drawable.
virtual float getRotationPointY ()
Accessor for the rotation y-coordinate of the Drawable.
virtual float getRotationPointZ ()
Accessor for the rotation z-coordinate of the Drawable.
virtual bool isProcessed ()
Accessor that returns if Drawable is processed and ready to be drawn.
virtual unsigned int getShaderType ()
Accessor that returns a value corresponding to a certain shader in Canvas.
virtual float getAlpha ()
Accessor that returns Drawable's alpha value.
Protected Member Functions
bool centerMatchesRotationPoint ()
Protected helper method that determines if the Drawable's center matches its rotation point.
Protected Attributes
std::mutex attribMutex
Protects the attributes of the Drawable from being accessed while simultaneously being changed.
GLfloat * vertices
float myCurrentYaw
float myCurrentPitch
float myCurrentRoll
float myXScale
float myYScale
float myZScale
float myRotationPointX
float myRotationPointY
float myRotationPointZ
float myCenterX
float myCenterY
float myCenterZ
bool init = false
unsigned int shaderType = SHAPE_SHADER_TYPE
GLfloat myAlpha = 0.0
Detailed Description
A class for drawing objects onto a Canvas or CartesianCanvas.
Warning
Though extending this class must be allowed due to the way the code is set up, attempting to do so could potentially mess up the internal GL calls the library uses. Proceed with great caution.
Drawable provides a base class for drawing 3D objects to a Canvas or CartesianCanvas.
Note
Drawable is abstract, and must be extended by the user.
vertices should be an array of floating point values in TSGL's vertex format.
numberofvertices should be the actual integer number of vertices to be drawn (e.g., 36 for a cube).
geometryType should be one of GL's primitive drawing modes. See https://www.opengl.org/sdk/docs/man2/xhtml/glBegin.xml for further information.
Theoretically, you could potentially extend the Drawable class so that you can create another Drawable class that suits your needs.
However, this is not recommended for normal use of the TSGL library.
Constructor & Destructor Documentation
Drawable()
tsgl::Drawable::Drawable (float x, float y, float z, float yaw, float pitch, float roll)
Constructs a new Drawable.
Usually vertices is filled with floating point values that represent the vertices of the Drawable to be drawn.
You may define other items in the constructor that pertain to the attributes of the subclass that is extending Drawable.
At a minimum, you MUST fill an array of floating point values that pertain to the vertices of the Drawable.
Warning
You must inherit the parent's constructor if you are extending Drawable.
Note
Refer to the Drawable class description for more details.
Referenced by centerMatchesRotationPoint().
Member Function Documentation
centerMatchesRotationPoint()
bool tsgl::Drawable::centerMatchesRotationPoint () [inline], [protected]
Protected helper method that determines if the Drawable's center matches its rotation point.
Checks to see if myCenterX == myRotationPointX, myCenterY == myRotationPointY, myCenterZ == myRotationPointZ
Returns
True if all three coordinates match their respective others, false otherwise.
Referenced by changeCenterBy(), changeXBy(), changeYBy(), changeZBy(), getCenterX(), getCenterY(), getCenterZ(), setCenter(), setCenterX(), setCenterY(), setCenterZ(), tsgl::Line::setFirstEndpoint(), tsgl::Arrow::setFirstEndpoint(), tsgl::Line::setSecondEndpoint(), and tsgl::Arrow::setSecondEndpoint().
changeCenterBy()
void tsgl::Drawable::changeCenterBy (float deltaX, float deltaY, float deltaZ) [virtual]
Alters the Drawable's vertex locations.
Parameters
deltaX The difference between the new and old vertex x coordinates.
deltaY The difference between the new and old vertex y coordinates.
deltaZ The difference between the new and old vertex z coordinates.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint().
changePitchBy()
void tsgl::Drawable::changePitchBy (float deltaPitch) [virtual]
Alters the Drawable's pitch by a specified amount.
Parameters
deltaPitch The change in pitch value for Drawable.
Referenced by centerMatchesRotationPoint().
changeRollBy()
void tsgl::Drawable::changeRollBy (float deltaRoll) [virtual]
Alters the Drawable's roll by a specified amount.
Parameters
deltaRoll The change in roll value for Drawable.
Referenced by centerMatchesRotationPoint().
changeXBy()
void tsgl::Drawable::changeXBy (float deltaX) [virtual]
Alters the Drawable's x position.
Parameters
deltaX The difference between the new and old vertex x coordinates.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint().
changeYawBy()
void tsgl::Drawable::changeYawBy (float deltaYaw) [virtual]
Alters the Drawable's yaw by a specified amount.
Parameters
deltaYaw The change in yaw value for Drawable.
Referenced by centerMatchesRotationPoint().
changeYawPitchRollBy()
void tsgl::Drawable::changeYawPitchRollBy (float deltaYaw, float deltaPitch, float deltaRoll) [virtual]
Alters the Drawable's yaw, pitch, and roll by a specified amount.
Parameters
deltaYaw The change in yaw value for Drawable.
deltaPitch The change in pitch value for Drawable.
deltaRoll The change in roll value for Drawable.
Referenced by centerMatchesRotationPoint().
changeYBy()
void tsgl::Drawable::changeYBy (float deltaY) [virtual]
Alters the Drawable's y position.
Parameters
deltaY The difference between the new and old vertex y coordinates.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint(), and Paddle::move().
changeZBy()
void tsgl::Drawable::changeZBy (float deltaZ) [virtual]
Alters the Drawable's z position.
Parameters
deltaZ The difference between the new and old vertex z coordinates.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint().
getAlpha()
virtual float tsgl::Drawable::getAlpha () [inline], [virtual]
Accessor that returns Drawable's alpha value.
Principally designed to be used within Canvas for transparency sorting.
Referenced by tsgl::Canvas::clearObjectBuffer().
getCenterX()
float tsgl::Drawable::getCenterX () [virtual]
Accessor for the center x-coordinate of the Drawable.
Returns the value of the myCenterX private variable, rotated by myCurrentYaw, myCurrentPitch, and myCurrentRoll about myRotationPointX;
Note
See https://math.stackexchange.com/questions/2093314/rotation-matrix-of-rotation-around-a-point-other-than-the-origin
and http://planning.cs.uiuc.edu/node102.html for more more understanding.
Referenced by Consumer::act(), centerMatchesRotationPoint(), tsgl::Canvas::clearObjectBuffer(), Philosopher3D::draw(), PCThread::PCThread(), Reader::Reader(), and Writer::Writer().
getCenterY()
float tsgl::Drawable::getCenterY () [virtual]
Accessor for the center z-coordinate of the Drawable.
Returns the value of the myCenterY private variable, rotated by myCurrentYaw, myCurrentPitch, and myCurrentRoll about myRotationPointY;
Note
See https://math.stackexchange.com/questions/2093314/rotation-matrix-of-rotation-around-a-point-other-than-the-origin
and http://planning.cs.uiuc.edu/node102.html for more more understanding.
Referenced by Consumer::act(), centerMatchesRotationPoint(), tsgl::Canvas::clearObjectBuffer(), Philosopher3D::draw(), PCThread::PCThread(), Reader::Reader(), and Writer::Writer().
getCenterZ()
float tsgl::Drawable::getCenterZ () [virtual]
Accessor for the center z-coordinate of the Drawable.
Returns the value of the myCenterZ private variable, rotated by myCurrentYaw, myCurrentPitch, and myCurrentRoll about myRotationPointZ;
Note
See https://math.stackexchange.com/questions/2093314/rotation-matrix-of-rotation-around-a-point-other-than-the-origin
and http://planning.cs.uiuc.edu/node102.html for more more understanding.
Referenced by centerMatchesRotationPoint(), tsgl::Canvas::clearObjectBuffer(), and Philosopher3D::draw().
getPitch()
virtual float tsgl::Drawable::getPitch () [inline], [virtual]
Accessor for the Pitch of the Drawable.
Returns the value of the myCurrentPitch private variable.
getRoll()
virtual float tsgl::Drawable::getRoll () [inline], [virtual]
Accessor for the Roll of the Drawable.
Returns the value of the myCurrentRoll private variable.
getRotationPointX()
virtual float tsgl::Drawable::getRotationPointX () [inline], [virtual]
Accessor for the rotation x-coordinate of the Drawable.
Returns the value of the myRotationPointX private variable.
getRotationPointY()
virtual float tsgl::Drawable::getRotationPointY () [inline], [virtual]
Accessor for the rotation y-coordinate of the Drawable.
Returns the value of the myRotationPointY private variable.
getRotationPointZ()
virtual float tsgl::Drawable::getRotationPointZ () [inline], [virtual]
Accessor for the rotation z-coordinate of the Drawable.
Returns the value of the myRotationPointZ private variable.
getShaderType()
virtual unsigned int tsgl::Drawable::getShaderType () [inline], [virtual]
Accessor that returns a value corresponding to a certain shader in Canvas.
This function returns the value of the shaderType instance variable.
Referenced by tsgl::Canvas::clearObjectBuffer(), tsgl::CartesianBackground::draw(), and tsgl::Background::draw().
getYaw()
virtual float tsgl::Drawable::getYaw () [inline], [virtual]
Accessor for the Yaw of the Drawable.
Returns the value of the myCurrentYaw private variable.
isProcessed()
virtual bool tsgl::Drawable::isProcessed () [inline], [virtual]
Accessor that returns if Drawable is processed and ready to be drawn.
This function returns true only if all vertices have been inserted into an array.
Reimplemented in tsgl::Shape, and tsgl::Polyline.
Referenced by tsgl::Canvas::clearObjectBuffer(), tsgl::CartesianBackground::draw(), and tsgl::Background::draw().
setCenter()
void tsgl::Drawable::setCenter (float x, float y, float z) [virtual]
Moves the Drawable to new coordinates.
Parameters
x The new center x coordinate.
y The new center y coordinate.
z The new center z coordinate.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by Consumer::act(), Producer::act(), centerMatchesRotationPoint(), Consumer::Consumer(), Ball::move(), PCThread::PCThread(), Producer::Producer(), Reader::Reader(), Writer::Writer(), and tsgl::ProgressBar::~ProgressBar().
setCenterX()
void tsgl::Drawable::setCenterX (float x) [virtual]
Sets the Drawable's x position.
Parameters
x The new center x coordinate.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint(), and Paddle::Paddle().
setCenterY()
void tsgl::Drawable::setCenterY (float y) [virtual]
Sets the Drawable's y position.
Parameters
y The new center y coordinate.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint().
setCenterZ()
void tsgl::Drawable::setCenterZ (float z) [virtual]
Sets the Drawable's z position.
Parameters
z The new center z coordinate.
Warning
This will also alter the Drawable's rotation point similarly if and only if the old rotation point was at the Drawable's old center.
Referenced by centerMatchesRotationPoint().
setPitch()
void tsgl::Drawable::setPitch (float pitch) [virtual]
Mutator for the Drawable's pitch.
Parameters
pitch The new pitch value for Drawable.
Referenced by centerMatchesRotationPoint().
setRoll()
void tsgl::Drawable::setRoll (float roll) [virtual]
Mutator for the Drawable's roll.
Parameters
roll The new roll value for Drawable.
Referenced by centerMatchesRotationPoint().
setRotationPoint()
void tsgl::Drawable::setRotationPoint (float x, float y, float z) [virtual]
Sets the point around which Drawable is rotated.
Parameters
x The x coordinate of the new rotation point.
y The y coordinate of the new rotation point.
z The z coordinate of the new rotation point.
Referenced by centerMatchesRotationPoint(), Philosopher3D::draw(), and tsgl::ProgressBar::~ProgressBar().
setRotationPointX()
void tsgl::Drawable::setRotationPointX (float x) [virtual]
Virtual mutator that changes the rotation point of the Drawable's x value.
Alters myRotationPointX;
Parameters
z myRotationPointX's new float value.
Referenced by centerMatchesRotationPoint().
setRotationPointY()
void tsgl::Drawable::setRotationPointY (float y) [virtual]
Virtual mutator that changes the rotation point of the Drawable's y value.
Alters myRotationPointY;
Parameters
y myRotationPointY's new float value.
Referenced by centerMatchesRotationPoint().
setRotationPointZ()
void tsgl::Drawable::setRotationPointZ (float z) [virtual]
Virtual mutator that changes the rotation point of the Drawable's z value.
Alters myRotationPointZ;
Parameters
z myRotationPointZ's new float value.
Referenced by centerMatchesRotationPoint().
setYaw()
void tsgl::Drawable::setYaw (float yaw) [virtual]
Mutator for the Drawable's yaw.
Parameters
yaw The new yaw value for Drawable.
Referenced by centerMatchesRotationPoint().
setYawPitchRoll()
void tsgl::Drawable::setYawPitchRoll (float yaw, float pitch, float roll) [virtual]
Mutator for the yaw, pitch, and roll of the Drawable.
Parameters
yaw The new yaw value for Drawable.
pitch The new pitch value for Drawable.
roll The new roll value for Drawable.
Referenced by centerMatchesRotationPoint(), and tsgl::ProgressBar::~ProgressBar().
The documentation for this class was generated from the following files:
Drawable.h
Drawable.cpp