tsgl::Colors Class Reference
Color utility class.
#include <Color.h>
Static Public Member Functions
static ColorFloat divideIntoChromaticSections (unsigned int totalSections, unsigned int index, float value, float alpha=1.0f)
Returns an HSVA color with a hue dependent on the number of sections.
static ColorFloat divideIntoChromaticSections (unsigned int totalSections, unsigned int index)
Returns an HSVA color with a hue dependent on the number of sections.
static ColorFloat randomColor (float alpha=0.0f)
Generates a random color.
static ColorFloat blend (ColorFloat c1, ColorFloat c2, float bias=0.5f)
Blends two colors with a given bias towards the latter.
static ColorFloat highContrastColor (unsigned int index, int offset=0)
Returns an HSV color with high contrast.
Detailed Description
Color utility class.
Colors defines color utility methods to construct colors.
Member Function Documentation
blend()
ColorFloat tsgl::Colors::blend (ColorFloat c1, ColorFloat c2, float bias = 0.5f) [static]
Blends two colors with a given bias towards the latter.
This function blends two ColorFloat structs together by taking a linear interpolation between the two and returns the result as a new ColorFloat.
Parameters
c1 A ColorFloat.
c2 Another ColorFloat.
bias A bias between 0 and 1 inclusive. A bias of 0 returns c1, a bias of 1 returns c2, and a bias in between returns a linear interpolation.
Warning
An invariant is held for the bias where if its greater than 1 or less than 0 then an error message is given.
Returns
A ColorFloat linearly interpolated between c1 and c2 using the given bias as a weight.
Referenced by tsgl::VisualTaskQueue::update(), and Voronoi::Voronoi().
divideIntoChromaticSections() [1/2]
ColorFloat tsgl::Colors::divideIntoChromaticSections (unsigned int totalSections, unsigned int index) [static]
Returns an HSVA color with a hue dependent on the number of sections.
This function returns a ColorFloat whose hue is calculated from the provided section number and the total number of sections. This function is used for creating a chromatic gradient from one part of the spectrum to another.
Parameters
totalSections Unsigned integer specifying the total number of sections.
index Unsigned integer specifying the current section.
Returns
A ColorFloat with a hue calculated as 6.0f / sections*section, and a saturation, value, and alpha of 1.0f.
divideIntoChromaticSections() [2/2]
ColorFloat tsgl::Colors::divideIntoChromaticSections (unsigned int totalSections, unsigned int index, float value, float alpha = 1.0f) [static]
Returns an HSVA color with a hue dependent on the number of sections.
This function returns a ColorFloat whose hue is calculated from the provided section number and the total number of sections. This function is used for creating a chromatic gradient from one part of the spectrum to another.
Parameters
totalSections Unsigned integer specifying the total number of sections.
index Unsigned integer specifying the current section.
value Value component, between 0 and 1 inclusive.
alpha Alpha component, between 0 and 1 inclusive (set to 1.0f by default).
Warning
An invariant is held where if value or alpha is greater than 1 or less than 0 then an error message is given.
Returns
A ColorFloat with a hue calculated as 6.0f / sections*section, saturation of 1.0f, and the given value and alpha components.
Referenced by divideIntoChromaticSections().
highContrastColor()
ColorFloat tsgl::Colors::highContrastColor (unsigned int index, int offset = 0) [static]
Returns an HSV color with high contrast.
This function returns a ColorHSV with hue, saturation, and value calculated to contrast highly with colors with nearby indices.
Parameters
index Unsigned integer representing the current color index.
offset Integer offset for the starting position of the calculation.
Returns
A ColorHSV representing a color visually distinct from its neighbors.
Referenced by tsgl::ProgressBar::ProgressBar(), tsgl::IntegralViewer::rectangleEvaluate(), tsgl::VisualTaskQueue::showLegend(), tsgl::IntegralViewer::trapezoidEvaluate(), and tsgl::VisualTaskQueue::update().
randomColor()
ColorFloat tsgl::Colors::randomColor (float alpha = 0.0f) [static]
Generates a random color.
This function uses rand() to generate a random ColorFloat with an optional specified alpha value.
Parameters
alpha Alpha of the random color to generate. An alpha of 0 will set the alpha to a random legal value (set to 0.0f by default).
Warning
An invariant is held for the alpha value where if its greater than 1 or less than 0 then an error message is given.
Returns
A random ColorFloat.
Referenced by Voronoi::Voronoi().
The documentation for this class was generated from the following files:
Color.h
Color.cpp