tsgl::Camera Class Reference
Defines a movable, rotatable camera-like object and its corresponding view matrix.
#include <Camera.h>
Public Member Functions
Camera (glm::vec3 position, glm::vec3 up, glm::vec3 target)
Explicitly constructs a new Camera.
Camera (float posX, float posY, float posZ, float upX, float upY, float upZ, float targetX, float targetY, float targetZ)
Explicitly constructs a new Camera.
Camera (glm::vec3 position, glm::vec3 up, float yaw, float pitch)
Explicitly constructs a new Camera.
Camera (float posX, float posY, float posZ, float upX, float upY, float upZ, float yaw, float pitch)
Explicitly constructs a new Camera.
glm::mat4 getViewMatrix ()
Accessor for the corresponding view matrix for the Camera.
void changeXBy (float delta)
Mutator for Camera's x-coordinate in world space.
void changeYBy (float delta)
Mutator for Camera's y-coordinate in world space.
void changeZBy (float delta)
Mutator for Camera's z-coordinate in world space.
void moveBackward (float delta)
Moves the Camera backward, relative to its orientation, by delta.
void moveForward (float delta)
Moves the Camera forward, relative to its orientation, by delta.
void moveDown (float delta)
Moves the Camera downward, relative to its orientation, by delta.
void moveUp (float delta)
Moves the Camera upward, relative to its orientation, by delta.
void moveLeft (float delta)
Moves the Camera left, relative to its orientation, by delta.
void moveRight (float delta)
Moves the Camera right, relative to its orientation, by delta.
void setPosition (glm::vec3 pos)
Alters the Camera's position in world space.
void setPosition (float x, float y, float z)
Alters the Camera's position in world space.
void setPositionX (float x)
Sets the Camera's x-coordinate in world space.
void setPositionY (float y)
Sets the Camera's y-coordinate co in world space.
void setPositionZ (float z)
Sets the Camera's z-coordinate in world space.
void lookAt (float x, float y, float z)
Alters the point at which the Camera looks in world space.
void changeYawBy (float delta)
Alters the Camera's yaw rotation.
void changePitchBy (float delta)
Alters the Camera's pitch rotation.
float getPitch ()
Accessor for the Camera's pitch.
float getYaw ()
Accessor for the Camera's yaw.
glm::vec3 getPosition ()
Accessor for the Camera's position in world space.
float getPositionX ()
Accessor for the x-coordinate of the Camera's position in world space.
float getPositionY ()
Accessor for the y-coordinate of the Camera's position in world space.
float getPositionZ ()
Accessor for the z-coordinate of the Camera's position in world space.
glm::vec3 getTarget ()
Accessor for the point at which Camera looks in world space.
float getTargetX ()
Accessor for the x-coordinate of the point at which Camera looks in world space.
float getTargetY ()
Accessor for the y-coordinate of the point at which Camera looks in world space.
float getTargetZ ()
Accessor for the z-coordinate of the point at which Camera looks in world space.
Protected Member Functions
void updateCameraAngle ()
Protected helper method that recalculates Camera's myFront vector based on yaw and pitch.
Protected Attributes
glm::vec3 myPosition
glm::vec3 myFront
glm::vec3 myUp
glm::vec3 myRight
glm::vec3 myWorldUp
float myYaw
float myPitch
std::mutex attribMutex
Detailed Description
Defines a movable, rotatable camera-like object and its corresponding view matrix.
Camera is used within TSGL::Canvas to define the view matrix.
Constructor & Destructor Documentation
Camera() [1/4]
tsgl::Camera::Camera (glm::vec3 position, glm::vec3 up, glm::vec3 target)
Explicitly constructs a new Camera.
Explicit constructor for a Camera object.
Parameters
position The Camera's location in 3D space, a glm::vec3.
up A 3D vector indicating the up direction in world space.
target The point at which the Camera will look.
Returns
A new Camera object, used to represent and return a corresponding view matrix.
Camera() [2/4]
tsgl::Camera::Camera (float posX, float posY, float posZ, float upX, float upY, float upZ, float targetX, float targetY, float targetZ)
Explicitly constructs a new Camera.
Explicit constructor for a Camera object.
Parameters
posX The Camera's positional x-coordinate in 3D space, a float.
posY The Camera's positional y-coordinate in 3D space, a float.
posZ The Camera's positional z-coordinate in 3D space, a float.
upX The x-component of a 3D vector indicating the up direction in world space.
upY The y-component of a 3D vector indicating the up direction in world space.
upZ The z-component of a 3D vector indicating the up direction in world space.
targetX The x-coordinate of the point at which the Camera will look.
targetY The y-coordinate of the point at which the Camera will look.
targetZ The z-coordinate of the point at which the Camera will look.
Returns
A new Camera object, used to represent and return a corresponding view matrix.
Camera() [3/4]
tsgl::Camera::Camera (glm::vec3 position, glm::vec3 up, float yaw, float pitch)
Explicitly constructs a new Camera.
Explicit constructor for a Camera object.
Parameters
position The Camera's location in 3D space, a glm::vec3.
up A 3D vector indicating the up direction in world space.
yaw The camera's yaw rotation (horizontal) in degrees.
pitch The camera's pitch rotation (vertical) in degrees.
Note
With position.x and position.y equal to 0 and a positive position.z, a yaw of -90 degrees and pitch of 0 degrees will look at (0,0,0).
pitch is constrained between -89 and 89 degrees.
Returns
A new Camera object, used to represent and return a corresponding view matrix.
Camera() [4/4]
tsgl::Camera::Camera (float posX, float posY, float posZ, float upX, float upY, float upZ, float yaw, float pitch)
Explicitly constructs a new Camera.
Explicit constructor for a Camera object.
Parameters
posX The Camera's positional x-coordinate in 3D space, a float.
posY The Camera's positional y-coordinate in 3D space, a float.
posZ The Camera's positional z-coordinate in 3D space, a float.
upX The x-component of a 3D vector indicating the up direction in world space.
upY The y-component of a 3D vector indicating the up direction in world space.
upZ The z-component of a 3D vector indicating the up direction in world space.
yaw The camera's yaw rotation (horizontal) in degrees.
pitch The camera's pitch rotation (vertical) in degrees.
Note
With posX and posY equal to 0 and a positive posZ, a yaw of -90 degrees and pitch of 0 degrees will look at (0,0,0).
pitch is constrained between -89 and 89 degrees.
Returns
A new Camera object, used to represent and return a corresponding view matrix.
Member Function Documentation
changePitchBy()
void tsgl::Camera::changePitchBy (float delta)
Alters the Camera's pitch rotation.
Based on the original direction the Camera was set to face, the Camera is rotated according to the parameter.
Parameters
delta The amount by which to change the Camera's pitch, in degrees.
Note
pitch is constrained between -89 and 89 degrees.
changeXBy()
void tsgl::Camera::changeXBy (float delta)
Mutator for Camera's x-coordinate in world space.
Alters the x component of Camera's myPosition vector by delta.
Parameters
delta The difference between camera's new and old x-coordinates.
changeYawBy()
void tsgl::Camera::changeYawBy (float delta)
Alters the Camera's yaw rotation.
Based on the original direction the Camera was set to face, the Camera is rotated according to the parameter.
Parameters
delta The amount by which to change the Camera's yaw, in degrees.
changeYBy()
void tsgl::Camera::changeYBy (float delta)
Mutator for Camera's y-coordinate in world space.
Alters the y component of Camera's myPosition vector by delta.
Parameters
delta The difference between camera's new and old y-coordinates.
changeZBy()
void tsgl::Camera::changeZBy (float delta)
Mutator for Camera's z-coordinate in world space.
Alters the z component of Camera's myPosition vector by delta.
Parameters
delta The difference between camera's new and old z-coordinates.
getPitch()
float tsgl::Camera::getPitch ()
Accessor for the Camera's pitch.
Returns the value of the myPitch instance variable
getPosition()
glm::vec3 tsgl::Camera::getPosition ()
Accessor for the Camera's position in world space.
Returns the value of the myPosition instance variable
getPositionX()
float tsgl::Camera::getPositionX ()
Accessor for the x-coordinate of the Camera's position in world space.
Returns the x component of the myPosition instance variable
Referenced by tsgl::Canvas::clearObjectBuffer().
getPositionY()
float tsgl::Camera::getPositionY ()
Accessor for the y-coordinate of the Camera's position in world space.
Returns the y component of the myPosition instance variable
Referenced by tsgl::Canvas::clearObjectBuffer().
getPositionZ()
float tsgl::Camera::getPositionZ ()
Accessor for the z-coordinate of the Camera's position in world space.
Returns the z component of the myPosition instance variable
Referenced by tsgl::Canvas::clearObjectBuffer().
getTarget()
glm::vec3 tsgl::Camera::getTarget ()
Accessor for the point at which Camera looks in world space.
Returns the sum of the myPosition and myFront instance variables
getTargetX()
float tsgl::Camera::getTargetX ()
Accessor for the x-coordinate of the point at which Camera looks in world space.
Returns the x component of the sum of the myPosition and myFront instance variables
getTargetY()
float tsgl::Camera::getTargetY ()
Accessor for the y-coordinate of the point at which Camera looks in world space.
Returns the y component of the sum of the myPosition and myFront instance variables
getTargetZ()
float tsgl::Camera::getTargetZ ()
Accessor for the z-coordinate of the point at which Camera looks in world space.
Returns the z component of the sum of the myPosition and myFront instance variables
getViewMatrix()
glm::mat4 tsgl::Camera::getViewMatrix ()
Accessor for the corresponding view matrix for the Camera.
Returns a glm::mat4 based on Camera's position and orientation.
Returns
A glm::mat4 calculated by glm::lookAt().
Referenced by tsgl::CartesianBackground::selectShaders(), tsgl::Background::selectShaders(), tsgl::CartesianCanvas::selectShaders(), and tsgl::Canvas::takeScreenShot().
getYaw()
float tsgl::Camera::getYaw ()
Accessor for the Camera's yaw.
Returns the value of the myYaw instance variable
lookAt()
void tsgl::Camera::lookAt (float x, float y, float z)
Alters the point at which the Camera looks in world space.
Sets Camera's myFront vector, myRight vector, myUp vector, myPitch, and myYaw based on the parameters.
Parameters
x The new x-coordinate at which Camera looks, in world space.
y The new y-coordinate at which Camera looks, in world space.
z The new z-coordinate at which Camera looks, in world space.
moveBackward()
void tsgl::Camera::moveBackward (float delta)
Moves the Camera backward, relative to its orientation, by delta.
Alters Camera's myPosition vector by delta, in the opposite direction of its myFront vector.
Parameters
delta How far backwards to move the Camera, in world space.
moveDown()
void tsgl::Camera::moveDown (float delta)
Moves the Camera downward, relative to its orientation, by delta.
Alters Camera's myPosition vector by delta, in the opposite direction of its myUp vector.
Parameters
delta How far downward to move the Camera, in world space.
moveForward()
void tsgl::Camera::moveForward (float delta)
Moves the Camera forward, relative to its orientation, by delta.
Alters Camera's myPosition vector by delta, in the same direction as its myFront vector.
Parameters
delta How far forward to move the Camera, in world space.
moveLeft()
void tsgl::Camera::moveLeft (float delta)
Moves the Camera left, relative to its orientation, by delta.
Alters Camera's myPosition vector by delta, in the opposite direction of its myRight vector.
Parameters
delta How far left to move the Camera, in world space.
moveRight()
void tsgl::Camera::moveRight (float delta)
Moves the Camera right, relative to its orientation, by delta.
Alters Camera's myPosition vector by delta, in the same direction as its myUp vector.
Parameters
delta How far right to move the Camera, in world space.
moveUp()
void tsgl::Camera::moveUp (float delta)
Moves the Camera upward, relative to its orientation, by delta.
Alters Camera's myPosition vector by delta, in the same direction as its myUp vector.
Parameters
delta How far upward to move the Camera, in world space.
setPosition() [1/2]
void tsgl::Camera::setPosition (glm::vec3 pos)
Alters the Camera's position in world space.
Sets the x, y, and z components of Camera's myPosition vector according to the parameters.
Parameters
pos 3D vector containing Camera's new x, y, and z positional coordinates.
Referenced by tsgl::CartesianCanvas::recomputeDimensions().
setPosition() [2/2]
void tsgl::Camera::setPosition (float x, float y, float z)
Alters the Camera's position in world space.
Sets the x, y, and z components of Camera's myPosition vector according to the parameters.
Parameters
x The Camera's new x-coordinate in world space.
y The Camera's new y-coordinate in world space.
z The Camera's new z-coordinate in world space.
setPositionX()
void tsgl::Camera::setPositionX (float x)
Sets the Camera's x-coordinate in world space.
Sets the x component of Camera's myPosition vector equal to the parameter.
Parameters
x The Camera's new x-coordinate in world space.
setPositionY()
void tsgl::Camera::setPositionY (float y)
Sets the Camera's y-coordinate co in world space.
Sets the y component of Camera's myPosition vector equal to the parameter.
Parameters
y The Camera's new y-coordinate in world space.
setPositionZ()
void tsgl::Camera::setPositionZ (float z)
Sets the Camera's z-coordinate in world space.
Sets the z component of Camera's myPosition vector equal to the parameter.
Parameters
z The Camera's new z-coordinate in world space.
updateCameraAngle()
void tsgl::Camera::updateCameraAngle () [protected]
Protected helper method that recalculates Camera's myFront vector based on yaw and pitch.
Alters myFront, myRight, and myUp according to yaw and pitch.
Referenced by Camera(), changePitchBy(), and changeYawBy().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp