tsgl::Prism Class Reference
Draw an arbitrary Prism with colored vertices.
#include <Prism.h>
Public Member Functions
Prism (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c)
Explicitly constructs a new Prism.
Prism (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c[])
Explicitly constructs a new Prism.
virtual void setHeight (GLfloat height)
Mutates the distance from the Prism's bottom to its top.
virtual void changeHeightBy (GLfloat delta)
Mutates the distance from the Prism's bottom to its top by the parameter amount.
virtual void setRadius (GLfloat radius)
Mutates the distance from the center of the Prism's base to the corners.
virtual void changeRadiusBy (GLfloat delta)
Mutates the distance from the center of the Prism's base to the corner by the parameter amount.
virtual GLfloat getRadius ()
Accessor for the radius of the Prism.
virtual GLfloat getHeight ()
Accessor for the height of the Prism.
virtual void setColor (ColorFloat c)
Sets the Shape to a new color.
virtual void setColor (ColorFloat c[])
Mutator. Sets the Prism to a new array of colors.
virtual void getColors (std::vector< ColorFloat > &colorVec)
Accessor for Arrow's colors.
Protected Attributes
GLfloat myHeight
GLfloat myRadius
int mySides
Additional Inherited Members
Detailed Description
Draw an arbitrary Prism with colored vertices.
Prism is a class for holding vertex data for a Prism with a base with at least 3 sides.
Constructor & Destructor Documentation
Prism() [1/2]
tsgl::Prism::Prism (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c)
Explicitly constructs a new Prism.
Explicit constructor for a Prism object.
Parameters
x The x coordinate of the center of the Prism.
y The y coordinate of the center of the Prism.
z The z coordinate of the center of the Prism.
sides The number of sides of the Prism's base.
yaw The Prism's yaw.
pitch The Prism's pitch.
roll The Prism's roll.
c A ColorFloat for the Prism's vertex colors.
Warning
An invariant is held where if sides is less than 3 then an error message is given.
An invariant is held where if radius isn't positive then an error message is given.
An invariant is held where if all points in vertices are not in the same plane then an error message is given.
Returns
A new Prism with a buffer for storing the specified numbered of vertices.
Referenced by tsgl::Cylinder::Cylinder().
Prism() [2/2]
tsgl::Prism::Prism (float x, float y, float z, int sides, GLfloat height, GLfloat radius, float yaw, float pitch, float roll, ColorFloat c[])
Explicitly constructs a new Prism.
Explicit constructor for a Prism object.
Parameters
x The x coordinate of the center of the Prism.
y The y coordinate of the center of the Prism.
z The z coordinate of the center of the Prism.
sides The number of sides of the Prism's base.
yaw The Prism's yaw.
pitch The Prism's pitch.
roll The Prism's roll.
c An array of ColorFloats for the Prism's vertex colors.
Warning
An invariant is held where if sides is less than 3 then an error message is given.
An invariant is held where if radius isn't positive then an error message is given.
An invariant is held where if all points in vertices are not in the same plane then an error message is given.
Returns
A new Prism with a buffer for storing the specified numbered of vertices.
Member Function Documentation
changeHeightBy()
void tsgl::Prism::changeHeightBy (GLfloat delta) [virtual]
Mutates the distance from the Prism's bottom to its top by the parameter amount.
Parameters
delta The amount by which to change the height of the Prism.
changeRadiusBy()
void tsgl::Prism::changeRadiusBy (GLfloat delta) [virtual]
Mutates the distance from the center of the Prism's base to the corner by the parameter amount.
Parameters
delta The amount by which to change the radius of the Prism.
getColors()
void tsgl::Prism::getColors (std::vector< ColorFloat > & colorVec) [virtual]
Accessor for Arrow's colors.
Populates the reference parameter vector with a ColorFloat for each end of Arrow.
Parameters
colorVec A vector of ColorFloats to which the ColorFloats associated with Arrow will be pushed.
Note
Overrides Shape::getColors().
Reimplemented from tsgl::Shape.
Referenced by setColor().
getHeight()
virtual GLfloat tsgl::Prism::getHeight () [inline], [virtual]
Accessor for the height of the Prism.
Returns the value of the myHeight private variable, a GLfloat.
getRadius()
virtual GLfloat tsgl::Prism::getRadius () [inline], [virtual]
Accessor for the radius of the Prism.
Returns the value of the myRadius private variable, a GLfloat.
setColor() [1/2]
virtual void tsgl::Prism::setColor (ColorFloat c) [inline], [virtual]
Sets the Shape to a new color.
Parameters
c The new ColorFloat.
Reimplemented from tsgl::Shape.
Referenced by Philosopher3D::refreshColor().
setColor() [2/2]
void tsgl::Prism::setColor (ColorFloat c[]) [virtual]
Mutator. Sets the Prism to a new array of colors.
Parameters
c The array of new ColorFloats.
The array should have 5 ColorFloats minimum: for the top middle, top outside, sides, bottom outside, and bottom middle respectively.
Reimplemented from tsgl::Shape.
setHeight()
void tsgl::Prism::setHeight (GLfloat height) [virtual]
Mutates the distance from the Prism's bottom to its top.
Parameters
height The Prism's new height.
setRadius()
void tsgl::Prism::setRadius (GLfloat radius) [virtual]
Mutates the distance from the center of the Prism's base to the corners.
Parameters
radius The Prism's new radius.
The documentation for this class was generated from the following files:
Prism.h
Prism.cpp