tsgl::Rectangle Class Reference
Draw a simple Rectangle.
#include <Rectangle.h>
Public Member Functions
Rectangle (float x, float y, float z, GLfloat width, GLfloat height, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a Rectangle with monocolored fill.
Rectangle (float x, float y, float z, GLfloat width, GLfloat height, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a Rectangle with multicolored fill.
GLfloat getWidth ()
Accessor for the width of the Rectangle.
GLfloat getHeight ()
Accessor for the height of the Rectangle.
void setWidth (GLfloat width)
Mutates the distance from the left side of the Rectangle base to its right side.
void setHeight (GLfloat height)
Mutates the distance from the top side of the Rectangle base to its bottom side.
void changeWidthBy (GLfloat delta)
Mutates the distance from the left side of the Rectangle base to its right side by the parameter amount.
void changeHeightBy (GLfloat delta)
Mutates the distance from the top side of the Rectangle base to its bottom side by the parameter amount.
Additional Inherited Members
Detailed Description
Draw a simple Rectangle.
Rectangle is a class for holding vertex data for a simple rectangle.
Constructor & Destructor Documentation
Rectangle() [1/2]
tsgl::Rectangle::Rectangle (float x, float y, float z, GLfloat width, GLfloat height, float yaw, float pitch, float roll, ColorFloat color)
Explicitly constructs a Rectangle with monocolored fill.
This is the constructor for the Rectangle class.
Parameters
x The x coordinate of the Rectangle's center.
y The y coordinate of the Rectangle's center.
z The z coordinate of the Rectangle's center.
width The width of the Rectangle.
height The height of the Rectangle.
yaw The Rectangle's yaw in 3D space.
pitch The Rectangle's pitch in 3D space.
roll The Rectangle's roll in 3D space.
color The color of the Rectangle.
Returns
A new Rectangle with the specified top left corner, dimensions, and color.
Rectangle() [2/2]
tsgl::Rectangle::Rectangle (float x, float y, float z, GLfloat width, GLfloat height, float yaw, float pitch, float roll, ColorFloat color[])
Explicitly constructs a Rectangle with multicolored fill.
This is the constructor for the Rectangle class.
Parameters
x The x coordinate of the Rectangle's center.
y The y coordinate of the Rectangle's center.
z The z coordinate of the Rectangle's center.
width The width of the Rectangle.
height The height of the Rectangle.
yaw The Rectangle's yaw in 3D space.
pitch The Rectangle's pitch in 3D space.
roll The Rectangle's roll in 3D space.
color An array of colors for the vertices of the Rectangle.
Returns
A new Rectangle with the specified top left corner, dimensions, and colors.
Member Function Documentation
changeHeightBy()
void tsgl::Rectangle::changeHeightBy (GLfloat delta)
Mutates the distance from the top side of the Rectangle base to its bottom side by the parameter amount.
Parameters
delta The amount by which to change the height of the Rectangle.
Referenced by getHeight().
changeWidthBy()
void tsgl::Rectangle::changeWidthBy (GLfloat delta)
Mutates the distance from the left side of the Rectangle base to its right side by the parameter amount.
Parameters
delta The amount by which to change the width of the Rectangle.
Referenced by getHeight().
getHeight()
GLfloat tsgl::Rectangle::getHeight () [inline]
Accessor for the height of the Rectangle.
Returns the value of the myHeight private variable, a GLfloat.
getWidth()
GLfloat tsgl::Rectangle::getWidth () [inline]
Accessor for the width of the Rectangle.
Returns the value of the myWidth private variable, a GLfloat.
setHeight()
void tsgl::Rectangle::setHeight (GLfloat height)
Mutates the distance from the top side of the Rectangle base to its bottom side.
Parameters
height The Rectangle's new height.
Referenced by getHeight().
setWidth()
void tsgl::Rectangle::setWidth (GLfloat width)
Mutates the distance from the left side of the Rectangle base to its right side.
Parameters
width The Rectangle's new width.
Referenced by getHeight(), and tsgl::ProgressBar::update().
The documentation for this class was generated from the following files:
Rectangle.h
Rectangle.cpp