Table3D Class Reference
Object managing the forks and philosophers in the Dining Philosophers' problem.
#include <Table3D.h>
Public Member Functions
Table3D (Canvas &can, int p, PhilMethod m)
Creates a new 3D Table of dining Philosopher3Ds.
~Table3D ()
Destructor for Table3D.
void forfeitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher3D should get.
void waitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher3D should get.
void nFrameReleaseMethod (int id)
Method for determining which fork a Philosopher3D should get.
void hierarchyMethod (int id)
Method for determining which fork a Philosopher3D should get.
void oddEvenMethod (int id)
Method for determining which fork a Philosopher3D should get.
void checkStep ()
Method for determining which method of resolution the philosopher is using.
void actStep ()
Method for philosopher to act based on myAction.
void drawStep ()
Method calculating angles calling draw methods of a philosopher and its fork or forks.
Detailed Description
Object managing the forks and philosophers in the Dining Philosophers' problem.
The Table3D class keeps track of the forks and philosophers in the Dining Philosophers' problem; it additionally manages the actions of the philosophers.
Each step of the problem is broken up into two phases. In the checking phase, the philosophers look at the 3D table around them and, without communicating with the other philosophers, determine an action to take based on their state and the states of their adjacent forks.
In the action phase, each philosopher attempts to execute the action previously determined in the checking phase. If unsuccessful, the philosopher does nothing; otherwise, the philosopher's state changes depending on the action taken.
Constructor & Destructor Documentation
Table3D()
Table3D::Table3D (Canvas & can, int p, PhilMethod m)
Creates a new 3D Table of dining Philosopher3Ds.
Explicit constructor for a new Table3D object.
Parameters
can The Canvas on which the Table3D is to be drawn.
p Integer denoting the number of Philosopher3Ds at the Table3D
m PhilMethod denoting how the Philosopher3Ds should interact.
Member Function Documentation
forfeitWhenBlockedMethod()
void Table3D::forfeitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher3D should get.
Store the id numbers for the left and the right Philsopher's state.
Switch for the state of a Philosopher3D:
Philosopher3D has no fork:
If the right fork is free, try to get that fork.
Else, if the left fork is free, try to get that fork.
Else, do nothing.
Philosopher3D has right fork:
If the left fork is free, try to get that fork.
Philosopher3D has the left fork:
If the right fork is free, try to get that fork.
Else, release the left fork.
Philosopher3D has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher3D.
Note
This is an example of Deadlock amongst threads.
Referenced by checkStep().
hierarchyMethod()
void Table3D::hierarchyMethod (int id)
Method for determining which fork a Philosopher3D should get.
Store the states for the left and right Philosopher3Ds.
Switch statement for the state of the current Philosopher3D.
Philosopher3D has no forks:
If the right Philosopher3D's id is less than the left Philsopher's id:
If the right fork is free, try to get that fork.
Else, do nothing.
Else, if the left fork is free then try and get that fork.
Else, do nothing.
Philosopher3D has the right fork:
If the left fork is free, try and get that fork.
Else, do nothing.
Philosopher3D has the left fork:
If the right fork is free, try and get that fork.
Else, do nothing.
Philosopher3D has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher3D.
Referenced by checkStep().
nFrameReleaseMethod()
void Table3D::nFrameReleaseMethod (int id)
Method for determining which fork a Philosopher3D should get.
Store the states of the left and right Philosopher3Ds.
Switch statement for the current Philosopher3D:
Philosopher3D has no forks:
If the right fork is free, try to get that fork.
Else, if the left fork is free, try to get that fork.
Else, do nothing.
Philosopher3D has right fork:
If the left fork is free, try to get that fork.
Else, if the id of the current Philosopher3D is equal to the frame number of the Canvas modulo the number of Philosopher3Ds+1, then release the right fork.
Else, do nothing.
Philosopher3D has the left fork:
If the right fork is free, try and get that fork.
Else, if the id of the current Philosopher3D is equal to the frame number of the Canvas modulo the number of Philosopher3Ds+1, then release the left fork.
Else, do nothing.
Philosopher3D has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher3D.
Referenced by checkStep().
oddEvenMethod()
void Table3D::oddEvenMethod (int id)
Method for determining which fork a Philosopher3D should get.
Switch statement for the current Philosopher3D:
Philosopher3D has no forks:
If the Philosopher3D's id is even
Philosopher3D has right fork (odd id):
If the Philsopher's id modulo 2 is equal to the Canvas' current frame number modulo 2, then try and get the left fork.
Else, release the right fork.
Philosopher3D has left fork (even id):
If the Philsopher's id modulo 2 is equal to the Canvas' current frame number modulo 2, then try and get the right fork.
Else, release the left fork.
Philosopher3D has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher3D.
Note
This method is the one that works best.
Referenced by checkStep().
waitWhenBlockedMethod()
void Table3D::waitWhenBlockedMethod (int id)
Method for determining which fork a Philosopher3D should get.
Store the states of the left and right Philosopher3Ds.
Switch for the state of the current Philosopher3D:
Philosopher3D has no forks:
If the right fork is free, try to get that fork.
Else if the left fork is free, try to get that fork.
Else, do nothing.
Philosopher3D has right fork:
If the left fork is free, try to get that fork.
Else, do nothing.
Philosopher3D has the left fork:
If the right fork is free, try to get that fork.
Else, do nothing.
Philosopher3D has both forks:
Release both of them.
Parameters
id The id number of the current Philosopher3D.
Note
This is an example of Livelock amongst threads.
Referenced by checkStep().
The documentation for this class was generated from the following files:
/home/sth5/test/TSGL/src/examples/DiningPhilosophers3D/Table3D.h
/home/sth5/test/TSGL/src/examples/DiningPhilosophers3D/Table3D.cpp