tsgl::ColorFloat Struct Reference
Floating point RGBA color struct.
#include <Color.h>
Public Member Functions
ColorFloat ()
Default ColorFloat constructor method.
ColorFloat (GLfloat v, GLfloat a=1.0f)
Basic explicit ColorFloat constructor method.
ColorFloat (GLfloat r, GLfloat g, GLfloat b, GLfloat a=1.0f)
Full explicit ColorFloat constructor method.
std::string asString ()
Returns a string representation of the ColorFloat.
operator ColorHSV ()
Implicit conversion from ColorFloat to ColorHSV.
operator ColorInt ()
Implicit conversion from ColorFloat to ColorInt.
ColorFloat operator* (float f)
Multiplies the values of a ColorFloat by a float.
bool operator== (ColorFloat &c2)
Determines if two ColorFloats are equivalent.
bool operator!= (ColorFloat &c2)
Determines if two ColorFloats are NOT equivalent.
ColorFloat getContrast ()
Public Attributes
GLfloat R
GLfloat G
GLfloat B
GLfloat A
Detailed Description
Floating point RGBA color struct.
ColorFloat defines a color with floating point red, green, blue, and alpha components.
Parameters
R Red component, between 0 and 1 inclusive.
G Green component, between 0 and 1 inclusive.
B Blue component, between 0 and 1 inclusive.
A Alpha component, between 0 and 1 inclusive.
Constructor & Destructor Documentation
ColorFloat() [1/3]
tsgl::ColorFloat::ColorFloat ()
Default ColorFloat constructor method.
This is the default constructor for the ColorFloat struct.
Note
R, G, B, and A are all set to 1.0f by default.
Returns
A ColorFloat struct with default R, G, B, and A values.
Referenced by tsgl::Colors::blend(), tsgl::ColorInt::operator ColorFloat(), tsgl::ColorInt::operator ColorHSV(), tsgl::ColorHSV::operator ColorInt(), operator*(), and tsgl::Colors::randomColor().
ColorFloat() [2/3]
tsgl::ColorFloat::ColorFloat (GLfloat v, GLfloat a = 1.0f)
Basic explicit ColorFloat constructor method.
This is the basic explicit constructor for the ColorFloat struct.
Parameters
v The value component of the color.
a The alpha component of the struct (set to 1.0f by default).
Warning
An invariant is set where if any of the specified R, G, B, or A values is out of the range 0 - 1 inclusive then an error message is given.
Returns
A ColorFloat struct with equal R, G, and B values set to v, and the specified A value.
ColorFloat() [3/3]
tsgl::ColorFloat::ColorFloat (GLfloat r, GLfloat g, GLfloat b, GLfloat a = 1.0f)
Full explicit ColorFloat constructor method.
This is the full explicit constructor for the ColorFloat struct.
Parameters
r The red component of the struct.
g The green component of the struct.
b The blue component of the struct.
a The alpha component of the struct (set to 1.0f by default).
Warning
An invariant is set where if any of the specified R, G, B, or A values is out of the range 0 - 1 inclusive then an error message is given.
Returns
A ColorFloat struct with the specified R, G, B, and A values.
Member Function Documentation
asString()
std::string tsgl::ColorFloat::asString ()
Returns a string representation of the ColorFloat.
This function returns a std::string representation of the ColorFloat.
Returns
A string representation of the ColorFloat.
operator ColorHSV()
tsgl::ColorFloat::operator ColorHSV ()
Implicit conversion from ColorFloat to ColorHSV.
This defines the implicit conversion operator from a floating point color type (ColorFloat) to an HSV color type (ColorHSV).
operator ColorInt()
tsgl::ColorFloat::operator ColorInt ()
Implicit conversion from ColorFloat to ColorInt.
This defines the implicit conversion operator from a floating point color type (ColorFloat) to an integer color type (ColorInt).
operator!=()
bool tsgl::ColorFloat::operator!= (ColorFloat & c2)
Determines if two ColorFloats are NOT equivalent.
Inequality operator for two ColorFloats. Determines if they are NOT equivalent.
Parameters
c2 Reference to the ColorFloat struct that is the second one in the inequality comparison.
Note
This function relies on (*this), which is a dereferenced pointer to the first ColorFloat struct in the inequality comparison. (its the one on the left side of the != sign).
Returns
true if the two ColorFloats are not equivalent, false if otherwise.
operator*()
ColorFloat tsgl::ColorFloat::operator* (float f)
Multiplies the values of a ColorFloat by a float.
This operator multiplies each of the components of a ColorFloat by amount f.
Parameters
f Amount to multiply each component by
Returns
A new ColorFloat constructed as ColorFloat(orig.R*f, orig.G*f, orig.b*f, orig.A*f)
Note
Individual channels are clamped between 0 and 1.
operator==()
bool tsgl::ColorFloat::operator== (ColorFloat & c2)
Determines if two ColorFloats are equivalent.
Equality operator for two ColorFloats. Determines if they are equivalent.
Parameters
c2 Reference to the ColorFloat struct that is the second one in the equivalence comparison.
Note
This function relies on (*this), which is a dereferenced pointer to the first ColorFloat struct in the comparison. (its the one on the left side of the == sign).
Returns
true if the two ColorFloats are equivalent, false if otherwise.
The documentation for this struct was generated from the following files:
Color.h
Color.cpp